'use strict';
const $=s=>document.querySelector(s),canvas=$('#world'),ctx=canvas.getContext('2d');
const MODES={chill:{gap:236,speed:166,spacing:300,wave:13},flow:{gap:200,speed:207,spacing:325,wave:19},warp:{gap:175,speed:244,spacing:345,wave:22}};
const WORLDS=[{name:'ACID GARDEN',bg:'#160e23',deep:'#342044',a:'#d6f58c',b:'#e898d7',c:'#8970d8'},{name:'VIOLET OCEAN',bg:'#101329',deep:'#232b55',a:'#8bf2e3',b:'#bba3ff',c:'#657ed2'},{name:'SOLAR DREAM',bg:'#211125',deep:'#522d49',a:'#ffd58b',b:'#fd9ba5',c:'#ac79be'}];
const KEY='lucid-loop-v1';let saved={best:{chill:0,flow:0,warp:0},runs:0,total:0,perfects:0,streak:0,history:[],mode:'flow',sound:false,calm:matchMedia('(prefers-reduced-motion: reduce)').matches,palette:0};let storageOK=true;
function clean(n){return Math.min(1e9,Math.max(0,Math.floor(Number(n)||0)));}
try{const v=JSON.parse(localStorage.getItem(KEY));if(v&&typeof v==='object'){for(const m of Object.keys(MODES))saved.best[m]=clean(v.best?.[m]);for(const k of ['runs','total','perfects','streak'])saved[k]=clean(v[k]);if(MODES[v.mode])saved.mode=v.mode;for(const k of ['sound','calm'])if(typeof v[k]==='boolean')saved[k]=v[k];if([0,1,2].includes(v.palette))saved.palette=v.palette;if(Array.isArray(v.history))saved.history=v.history.filter(x=>x&&MODES[x.mode]&&Number.isFinite(x.score)&&Number.isFinite(x.perfects)&&Number.isFinite(x.at)).map(x=>({mode:x.mode,score:clean(x.score),perfects:clean(x.perfects),at:x.at})).slice(0,6);}}catch{storageOK=false;}
function persist(){try{localStorage.setItem(KEY,JSON.stringify(saved));}catch{if(storageOK)toast('Storage unavailable. Records will last for this visit only.');storageOK=false;}}
let width=1100,height=600,mode=saved.mode,state='ready',score=0,perfects=0,streak=0,maxStreak=0,focus=1,focusHeld=false,focusLocked=false,gates=[],motes=[],trail=[],clock=0,travel=0,serial=0,player={x:240,y:300,vy:0},last=0,acc=0,oldBest=0,cueTime=0,pulse=0,toastTimer,audio=null,ended=0;
let colors={...WORLDS[saved.palette]};
function toast(text){$('#toast').textContent=text;$('#toast').hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').hidden=true,3500);}
function announce(text){$('#announcement').textContent=text;}
function note(kind){if(!saved.sound)return;try{audio??=new(window.AudioContext||window.webkitAudioContext)();if(audio.state==='suspended')audio.resume().catch(()=>{});const now=audio.currentTime;const scale=[261.63,293.66,329.63,392,440,523.25];const root=scale[score%scale.length];const specs={flap:[root*.5,root,.13],pass:[root,root*1.5,.32],perfect:[root*1.5,root*2,.45],end:[196,98,.5],start:[261.63,523.25,.4]};const [a,b,d]=specs[kind]||specs.flap;const osc=audio.createOscillator(),gain=audio.createGain();osc.type='sine';osc.frequency.setValueAtTime(a,now);osc.frequency.exponentialRampToValueAtTime(b,now+d);gain.gain.setValueAtTime(.001,now);gain.gain.linearRampToValueAtTime(.05,now+.015);gain.gain.exponentialRampToValueAtTime(.001,now+d);osc.connect(gain);gain.connect(audio.destination);osc.start(now);osc.stop(now+d+.02);}catch{saved.sound=false;syncSettings();}}
function worldIndex(){return (saved.palette+Math.floor(score/8))%3;}
function blendColor(a,b,t){let av=parseInt(a.slice(1),16),bv=parseInt(b.slice(1),16);let out=0;for(const sh of [16,8,0])out|=Math.round(((av>>sh)&255)*(1-t)+((bv>>sh)&255)*t)<<sh;return '#'+out.toString(16).padStart(6,'0');}
function paletteStep(dt){const target=WORLDS[worldIndex()],a=1-Math.exp(-dt*3);for(const k of ['bg','deep','a','b','c'])colors[k]=blendColor(colors[k],target[k],a);$('#realm-name').textContent=String(worldIndex()+1).padStart(2,'0')+' / '+target.name;}
function syncSettings(){$('#audio-toggle').setAttribute('aria-pressed',saved.sound);$('#audio-toggle').setAttribute('aria-label',saved.sound?'Turn sound off':'Turn sound on');$('#audio-lines').setAttribute('d',saved.sound?'M14 7q7 5 0 10M18 3q10 9 0 18':'m15 8 7 8m0-8-7 8');$('#sound-setting').checked=saved.sound;$('#calm-setting').checked=saved.calm;$('#palette').value=saved.palette;document.body.classList.toggle('calm',saved.calm);}
function hud(){$('#distance').textContent=String(score).padStart(3,'0');$('#best').textContent=String(saved.best[mode]).padStart(3,'0');$('#combo').textContent=streak?'✧ '+streak+' PERFECT STREAK':'FIND YOUR FLOW';$('#summary').textContent=saved.runs?saved.runs+' trips · '+saved.total+' portals · '+saved.perfects+' perfect passes':'Every strange journey starts at zero.';}
function focusHUD(){const v=Math.round(focus*100);$('#focus-value').textContent=v+'%';$('#focus-fill').style.width=v+'%';$('#focus-meter').setAttribute('aria-valuenow',v);$('#touch-focus').classList.toggle('active',focusHeld&&!focusLocked&&focus>0&&state==='playing');}
function controls(){document.querySelectorAll('[data-mode]').forEach(b=>{b.disabled=state==='playing'||state==='paused';b.setAttribute('aria-pressed',b.dataset.mode===mode);});$('#pause').disabled=!['playing','paused'].includes(state);$('#pause').setAttribute('aria-label',state==='paused'?'Resume game':'Pause game');$('#touch-focus').disabled=state!=='playing';$('#status').textContent={ready:'THE UNIVERSE CAN WAIT. YOU GO FIRST.',playing:'BREATHE IN. FLOAT ON.',paused:'A MOMENT BETWEEN UNIVERSES.',over:'THE LOOP ENDS. THE NEXT ONE IS YOURS.'}[state];}
function setMode(m){if(!MODES[m]||state==='playing'||state==='paused')return;mode=m;saved.mode=m;persist();controls();hud();}
function resize(){const rect=canvas.getBoundingClientRect(),next=height*rect.width/rect.height;if(state==='playing'&&Math.abs(next-width)>8)pause();width=next;const dpr=Math.min(devicePixelRatio||1,2);canvas.width=Math.round(rect.width*dpr);canvas.height=Math.round(rect.height*dpr);ctx.setTransform(canvas.width/width,0,0,canvas.height/height,0,0);player.x=Math.max(82,Math.min(width*.25,280));}
function spawn(x){const prev=gates.at(-1),cfg=MODES[mode];const base=prev?Math.max(170,Math.min(430,prev.base+(Math.random()-.5)*120)):300;serial++;gates.push({x,w:54,base,center:base,gap:cfg.gap,phase:Math.random()*Math.PI*2,passed:false,n:serial});}
function start(){if($('dialog[open]'))return;state='playing';score=0;perfects=0;streak=0;maxStreak=0;focus=1;focusHeld=false;focusLocked=false;clock=0;travel=0;serial=0;gates=[];motes=[];trail=[];pulse=0;cueTime=0;$('#cue').textContent='';player={x:Math.max(82,Math.min(width*.25,280)),y:300,vy:-300};oldBest=saved.best[mode];spawn(Math.max(width+65,player.x+440));acc=0;last=performance.now();$('#veil').hidden=true;hud();focusHUD();controls();note('start');canvas.focus({preventScroll:true});announce(mode+' trip started.');}
function flap(){if($('dialog[open]'))return;if(state==='ready'){start();return;}if(state!=='playing')return;player.vy=-335;pulse=1;note('flap');if(!saved.calm)for(let i=0;i<4;i++)motes.push({x:player.x-9,y:player.y+10,vx:-40-Math.random()*40,vy:10+Math.random()*35,life:.5,color:colors.b});}
function holdFocus(on){if(!on){focusHeld=false;focusLocked=false;}else if(state==='playing'&&!focusLocked)focusHeld=true;focusHUD();}
function pause(){if(state!=='playing')return;state='paused';holdFocus(false);$('#veil').hidden=false;$('#veil').className='veil';$('#card').className='result';$('#card').innerHTML='<span class="pill">THE COSMOS IS ON HOLD</span><h2>Just a little<br>space to breathe.</h2><p>Your trip is safe. Pick up where you floated off.</p><div class="result-actions"><button class="primary" id="resume">Keep floating ↗</button><button class="secondary" id="end-trip">End trip</button></div><div class="start-hint">P / ESC TO RESUME</div>';$('#resume').onclick=resume;$('#end-trip').onclick=()=>finish(true);controls();announce('Trip paused.');$('#resume').focus({preventScroll:true});}
function resume(){if(state!=='paused'||$('dialog[open]'))return;state='playing';$('#veil').hidden=true;last=performance.now();acc=0;holdFocus(false);controls();canvas.focus({preventScroll:true});announce('Trip resumed.');}
function finish(quit=false){if(!['playing','paused'].includes(state))return;state='over';holdFocus(false);ended=performance.now();saved.runs++;saved.total+=score;saved.perfects+=perfects;saved.streak=Math.max(saved.streak,maxStreak);saved.best[mode]=Math.max(saved.best[mode],score);saved.history.unshift({mode,score,perfects,at:Date.now()});saved.history=saved.history.slice(0,6);persist();hud();controls();if(!quit)note('end');$('#veil').hidden=false;$('#veil').className='veil';$('#card').className='result';$('#card').innerHTML='<span class="pill">'+(score>oldBest?'A NEW PERSONAL UNIVERSE':quit?'TRANSMISSION COMPLETE':'YOU BECAME ONE WITH THE SCENERY')+'</span><h2>'+(score>oldBest?'A beautiful<br>new distance.':'Nothing ends.<br>It just loops.')+'</h2><div class="result-stats"><div><strong>'+score+'</strong><small>PORTALS</small></div><div><strong>'+perfects+'</strong><small>PERFECT</small></div><div><strong>'+maxStreak+'</strong><small>BEST STREAK</small></div></div><p>'+mode.toUpperCase()+' personal best: '+saved.best[mode]+'<br>A new universe is only one tap away.</p><div class="result-actions"><button class="primary" id="retry">Another trip ↗</button><button class="secondary" id="share">Share the weird</button></div><div class="start-hint">R TO RETRY · CHANGE INTENSITY ABOVE</div>';$('#retry').onclick=start;$('#share').onclick=share;$('#retry').focus({preventScroll:true});announce('Trip ended. '+score+' portals, '+perfects+' perfect passes. Best '+saved.best[mode]+'.');}
async function share(){const text='I floated through '+score+' portals on '+mode.toUpperCase()+' with '+perfects+' perfect passes in LUCID LOOP. Stay a little strange: '+location.href.split('?')[0];try{if(navigator.share)await navigator.share({title:'LUCID LOOP',text});else if(navigator.clipboard){await navigator.clipboard.writeText(text);toast('Trip stats and link copied. Send someone to the other side.');}else toast(text);}catch(e){if(e.name!=='AbortError')toast('Sharing unavailable. Copy the page address to share this universe.');}}
function step(realDt){if(state!=='playing')return;const focusing=focusHeld&&!focusLocked&&focus>0;if(focusing){focus=Math.max(0,focus-realDt/2.5);if(focus<=0){focusLocked=true;focusHeld=false;}}else focus=Math.min(1,focus+realDt/10);const dt=realDt*(focusing?.45:1);clock+=dt;cueTime=Math.max(0,cueTime-realDt);if(!cueTime)$('#cue').textContent='';pulse=Math.max(0,pulse-dt*4);const speed=MODES[mode].speed+Math.min(score*1.1,35);travel+=speed*dt;player.vy+=1000*dt;player.y+=player.vy*dt;trail.push({x:player.x,y:player.y});if(trail.length>24)trail.shift();if(player.y<17||player.y>height-17){finish();return;}for(const g of gates){g.x-=speed*dt;g.center=g.base+(saved.calm?0:Math.sin(clock*.8+g.phase)*MODES[mode].wave);const top=g.center-g.gap/2,bottom=g.center+g.gap/2;if(player.x+12>g.x&&player.x-12<g.x+g.w&&(player.y-12<top||player.y+12>bottom)){finish();return;}if(!g.passed&&g.x+g.w<player.x-12){g.passed=true;score++;if(Math.abs(player.y-g.center)<=22){perfects++;streak++;maxStreak=Math.max(maxStreak,streak);focus=Math.min(1,focus+.15);cueTime=1.1;$('#cue').textContent=streak>1?'PERFECT × '+streak:'PERFECT';note('perfect');}else{streak=0;note('pass');}saved.best[mode]=Math.max(saved.best[mode],score);persist();hud();if(score%8===0){toast('Entering '+WORLDS[worldIndex()].name.toLowerCase()+'. Keep floating.');}}}
gates=gates.filter(g=>g.x+g.w>-20);if(!gates.length||gates.at(-1).x<width-MODES[mode].spacing)spawn(width+25);for(const p of motes){p.x+=p.vx*dt;p.y+=p.vy*dt;p.life-=dt;}motes=motes.filter(p=>p.life>0);focusHUD();}
function ellipse(x,y,rx,ry,fill,stroke,rotation=0){ctx.beginPath();ctx.ellipse(x,y,Math.max(.1,rx),Math.max(.1,ry),rotation,0,Math.PI*2);if(fill){ctx.fillStyle=fill;ctx.fill();}if(stroke){ctx.strokeStyle=stroke;ctx.stroke();}}
function mushroom(x,y,size,t){ctx.save();ctx.translate(x,y);ctx.scale(size,size);ctx.strokeStyle=colors.b+'55';ctx.lineWidth=4;ctx.beginPath();ctx.moveTo(0,0);ctx.bezierCurveTo(-17,-30,12,-53,1,-86);ctx.stroke();const gr=ctx.createLinearGradient(0,-115,0,-75);gr.addColorStop(0,colors.c+'77');gr.addColorStop(1,colors.b+'10');ctx.fillStyle=gr;ctx.beginPath();ctx.moveTo(-48,-75);ctx.bezierCurveTo(-30,-125,29,-130,52,-75);ctx.bezierCurveTo(22,-61,-19,-64,-48,-75);ctx.fill();ctx.lineWidth=1;ctx.strokeStyle=colors.b+'66';ctx.stroke();for(let i=-3;i<=3;i++){ctx.beginPath();ctx.moveTo(i*12,-78);ctx.quadraticCurveTo(i*7,-90,0,-110);ctx.stroke();}ctx.fillStyle=colors.a+'55';for(let i=0;i<5;i++)ellipse((i-2)*15,-88-Math.sin(i*1.5)*8,2,1.5,colors.a+'77');ctx.restore();}
function backdrop(t){ctx.fillStyle=colors.bg;ctx.fillRect(0,0,width,height);const glow=ctx.createRadialGradient(width*.74,height*.43,5,width*.65,height*.5,width*.7);glow.addColorStop(0,colors.deep);glow.addColorStop(1,colors.bg);ctx.fillStyle=glow;ctx.fillRect(0,0,width,height);const motion=saved.calm?0:t;ctx.save();ctx.lineWidth=1;const cx=width*.72+Math.sin(motion*.13)*12,cy=height*.44;for(let i=0;i<10;i++){const r=38+i*31;ctx.strokeStyle=(i%2?colors.b:colors.c)+(saved.calm?'18':'27');ctx.beginPath();ctx.ellipse(cx,cy,r*1.4,r,.35+Math.sin(motion*.15+i*.2)*.13,0,Math.PI*2);ctx.stroke();}ctx.restore();for(let i=0;i<62;i++){let x=((Math.sin(i*72.53)*.5+.5)*width-(travel*.04)%(width)+width)%width;let y=(Math.cos(i*37.83)*.5+.5)*(height-60)+25;ctx.globalAlpha=.15+(i%4)*.09;ctx.fillStyle=i%3?colors.b:colors.a;let r=i%11===0?2:1;ctx.fillRect(x,y,r,r);}ctx.globalAlpha=1;ctx.save();ctx.translate(width*.86,115);ctx.rotate(-.4);ctx.lineWidth=1;ellipse(0,0,36,36,colors.c+'27',colors.b+'55');ellipse(0,0,62,12,null,colors.a+'55');ctx.restore();ctx.save();ctx.strokeStyle=colors.c+'25';ctx.lineWidth=1;for(let i=0;i<12;i++){ctx.beginPath();for(let x=0;x<=width;x+=14){const y=height-25-i*8+Math.sin(x*.009+i*.4+motion*.24)*12;x?ctx.lineTo(x,y):ctx.moveTo(x,y);}ctx.stroke();}ctx.restore();const off=(travel*.12)%180;for(let i=-1;i<width/180+1;i++)mushroom(i*180-off,height+10,.65+(i%3+3)%3*.2,motion);ctx.fillStyle=colors.a+'25';ctx.fillRect(0,0,width,2);ctx.fillRect(0,height-2,width,2);}
function gateArt(g,t){const top=g.center-g.gap/2,bottom=g.center+g.gap/2;ctx.save();for(const [y,h,edge] of [[-30,top+30,top],[bottom,height-bottom+30,bottom]]){ctx.save();ctx.beginPath();ctx.roundRect(g.x,y,g.w,h,13);ctx.clip();const gr=ctx.createLinearGradient(g.x,0,g.x+g.w,0);gr.addColorStop(0,colors.c+'55');gr.addColorStop(.5,colors.deep);gr.addColorStop(1,colors.b+'70');ctx.fillStyle=gr;ctx.fillRect(g.x,y,g.w,h);ctx.lineWidth=1;for(let n=0;n<6;n++){ctx.strokeStyle=n%2?colors.b+'65':colors.a+'40';ctx.beginPath();for(let yy=Math.max(0,y);yy<Math.min(height,y+h);yy+=8){const xx=g.x+6+n*9+Math.sin(yy*.024+n*.7+t*.35)*5;yy===Math.max(0,y)?ctx.moveTo(xx,yy):ctx.lineTo(xx,yy);}ctx.stroke();}ctx.restore();ctx.strokeStyle=colors.b+'80';ctx.lineWidth=1;ctx.beginPath();ctx.roundRect(g.x,y,g.w,h,13);ctx.stroke();ctx.save();ctx.shadowColor=colors.a;ctx.shadowBlur=saved.calm?0:12;ellipse(g.x+g.w/2,edge,g.w/2,5,colors.a+'22',colors.a);ctx.restore();}ctx.strokeStyle=colors.a+'30';ctx.setLineDash([2,8]);ctx.beginPath();ctx.moveTo(g.x+g.w/2,top+18);ctx.lineTo(g.x+g.w/2,bottom-18);ctx.stroke();ctx.setLineDash([]);ctx.save();ctx.translate(g.x+g.w/2,g.center);ctx.rotate(Math.PI/4);ctx.strokeStyle=colors.a+'aa';ctx.lineWidth=1;ctx.strokeRect(-4,-4,8,8);ctx.restore();ctx.restore();}
function jelly(x,y,size,t,tilt=0){ctx.save();ctx.translate(x,y);ctx.rotate(tilt);ctx.scale(size,size);const wiggle=saved.calm?0:t;for(let i=0;i<7;i++){const ox=(i-3)*7;ctx.strokeStyle=i%2?colors.b:colors.a+'aa';ctx.lineWidth=i%2?1.3:1.7;ctx.beginPath();ctx.moveTo(ox,5);ctx.bezierCurveTo(ox+Math.sin(wiggle*3+i)*12,25,ox+Math.cos(wiggle*2+i)*16,42,ox+Math.sin(wiggle*2.5+i)*14,50+Math.sin(i)*7);ctx.stroke();}const gr=ctx.createRadialGradient(-7,-16,1,0,-3,32);gr.addColorStop(0,'#fff6dd');gr.addColorStop(.25,colors.a);gr.addColorStop(.8,colors.b);gr.addColorStop(1,colors.c);ctx.fillStyle=gr;ctx.shadowColor=colors.b;ctx.shadowBlur=saved.calm?0:17;ctx.beginPath();ctx.moveTo(-27,5);ctx.bezierCurveTo(-27,-32,27,-34,29,5);ctx.bezierCurveTo(15,13,-16,13,-27,5);ctx.fill();ctx.shadowBlur=0;ctx.strokeStyle=colors.a+'dd';ctx.lineWidth=1;ctx.stroke();ctx.strokeStyle='#ffffff44';for(let i=-1;i<=1;i++){ctx.beginPath();ctx.moveTo(i*16,5);ctx.quadraticCurveTo(i*9,-20,0,-25);ctx.stroke();}ellipse(0,5,27,6,colors.b+'55',colors.a+'77');ctx.fillStyle='#271631';ellipse(-7,-4,2,3,'#271631');ellipse(8,-4,2,3,'#271631');ctx.strokeStyle='#3e234a';ctx.lineWidth=1.5;ctx.beginPath();ctx.arc(1,0,3,.2,Math.PI-.2);ctx.stroke();ellipse(-13,-15,5,2,'#fff9e977',null,-.5);ctx.restore();}
function draw(now=performance.now()){const t=state==='ready'?now/1000:clock;backdrop(t);if(state==='ready'){const x=width*.74,y=height*.43+(saved.calm?0:Math.sin(t*.9)*12);ctx.save();ctx.strokeStyle=colors.a+'25';ctx.lineWidth=1;for(let r=1;r<4;r++)ellipse(x,y+15,65*r,21*r,null,colors.b+'20',-.25);ctx.restore();jelly(x,y,Math.min(3.8,width/200),t,-.13);if(width>700){ctx.save();ctx.translate(x+40,y+160);ctx.rotate(-.12);ctx.fillStyle=colors.b+'aa';ctx.font='9px monospace';ctx.fillText('SPECIMEN 001 / MOSTLY VIBES',-100,0);ctx.restore();}}else{for(const g of gates)gateArt(g,saved.calm?0:t);if(!saved.calm){for(let i=0;i<trail.length;i++){const p=trail[i];ctx.globalAlpha=i/trail.length*.13;ellipse(p.x-(trail.length-i)*4,p.y,10*i/trail.length,7*i/trail.length,colors.b);}ctx.globalAlpha=1;}if(focusHeld&&!focusLocked&&state==='playing'){ctx.strokeStyle=colors.a+'99';ctx.lineWidth=1;ellipse(player.x,player.y,34,34,null,colors.a+'77');ellipse(player.x,player.y,42,42,null,colors.a+'22');}jelly(player.x,player.y,.56*(1+pulse*.07),t,Math.max(-.22,Math.min(.4,player.vy/1100)));if(!saved.calm)for(const p of motes){ctx.globalAlpha=Math.max(0,p.life);ellipse(p.x,p.y,2,2,p.color);}ctx.globalAlpha=1;}}
function frame(now){const dt=Math.min(.05,(now-last)/1000||0);last=now;if(state==='playing'){acc+=dt;while(acc>=1/120){step(1/120);acc-=1/120;}}paletteStep(dt);draw(now);requestAnimationFrame(frame);}
function records(){let html='<div class="record-grid">';for(const m of Object.keys(MODES))html+='<div><strong>'+saved.best[m]+'</strong><span>'+m+' best</span></div>';html+='</div><p class="fine-print">'+saved.runs+' trips · '+saved.total+' portals<br>'+saved.perfects+' perfect passes · '+saved.streak+' longest streak</p><h3 class="log-heading">LAST 6 TRIPS</h3>';if(!saved.history.length)html+='<p class="fine-print">Nothing on the radar. Take your first trip.</p>';for(const h of saved.history)html+='<div class="log-row"><span>'+h.mode.toUpperCase()+' · '+new Date(h.at).toLocaleDateString()+'</span><strong>'+h.score+' portals · '+h.perfects+' perfect</strong></div>';$('#record-content').innerHTML=html;}
function openDialog(id){pause();if(id==='records')records();$('#'+id).showModal();}
$('#enter').onclick=start;$('#pause').onclick=()=>state==='playing'?pause():resume();$('#guide-open').onclick=()=>openDialog('guide');$('#settings-open').onclick=()=>openDialog('settings');$('#records-open').onclick=()=>openDialog('records');document.querySelectorAll('dialog .close').forEach(b=>b.onclick=()=>b.closest('dialog').close());document.querySelectorAll('dialog').forEach(d=>d.addEventListener('click',e=>{if(e.target===d){const r=d.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)d.close();}}));document.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>setMode(b.dataset.mode));
function toggleSound(on){saved.sound=on;syncSettings();persist();if(on)note('pass');}
$('#audio-toggle').onclick=()=>toggleSound(!saved.sound);$('#sound-setting').onchange=e=>toggleSound(e.target.checked);$('#calm-setting').onchange=e=>{saved.calm=e.target.checked;syncSettings();persist();};$('#palette').onchange=e=>{saved.palette=Number(e.target.value);persist();};
canvas.addEventListener('pointerdown',e=>{if(e.button!==0)return;e.preventDefault();flap();});const focusButton=$('#touch-focus');focusButton.addEventListener('pointerdown',e=>{if(e.button!==0||state!=='playing')return;e.preventDefault();focusButton.setPointerCapture(e.pointerId);holdFocus(true);});for(const event of ['pointerup','pointercancel','lostpointercapture'])focusButton.addEventListener(event,()=>holdFocus(false));focusButton.addEventListener('keydown',e=>{if(e.key===' '||e.key==='Enter'){e.preventDefault();holdFocus(true);}});focusButton.addEventListener('keyup',e=>{if(e.key===' '||e.key==='Enter'){e.preventDefault();holdFocus(false);}});focusButton.addEventListener('blur',()=>holdFocus(false));
document.addEventListener('keydown',e=>{if($('dialog[open]')||e.ctrlKey||e.metaKey||e.altKey||e.target.matches('input,select,textarea'))return;const key=e.key.toLowerCase();if(e.repeat){if(key===' '||key==='arrowup')e.preventDefault();return;}if(key==='shift'){holdFocus(true);return;}if(key==='p'||key==='escape'){e.preventDefault();state==='playing'?pause():resume();}else if(key==='m')toggleSound(!saved.sound);else if(key==='r'&&state==='over'&&performance.now()-ended>250)start();else if((key===' '||key==='arrowup')&&!e.target.closest('button,a')){e.preventDefault();flap();}});document.addEventListener('keyup',e=>{if(e.key==='Shift')holdFocus(false);});document.addEventListener('visibilitychange',()=>{if(document.hidden)pause();});window.addEventListener('blur',()=>{holdFocus(false);pause();});window.addEventListener('pagehide',persist);new ResizeObserver(resize).observe($('#stage'));syncSettings();controls();hud();focusHUD();resize();requestAnimationFrame(frame);if(!storageOK)toast('Browser storage is blocked. Records last for this visit only.');
