import{MOODS,defaults,validate,hash,geometry,description,svgArt,notePlan,scheduleNote,wavFromBuffer,tempo}from'./engine.mjs';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const STORE='sonder.collection.v1',DRAFT='sonder.draft.v1';let state=defaults(),history=[],future=[],collection=[],phase=0,frame=0,lastFrame=0,dirty=true,paths=[],savedTimer,toastTimer,deleted=null,ctxAudio=null,audioBus=null,audioTimer=null,soundOn=false,renderCounter=0;const reduce=matchMedia('(prefers-reduced-motion: reduce)');let paused=reduce.matches;const canvas=$('#art'),ctx=canvas.getContext('2d');let storageOK=true;
function read(key,fallback){try{const x=localStorage.getItem(key);return x?JSON.parse(x):fallback}catch{return fallback}}
function write(key,value){try{localStorage.setItem(key,JSON.stringify(value));return true}catch{storageOK=false;return false}}
function clone(s=state){return{...s}}
function toast(text,undo=false){clearTimeout(toastTimer);$('#toast span').textContent=text;$('#toast-undo').hidden=!undo;$('#toast').hidden=false;toastTimer=setTimeout(()=>{$('#toast').hidden=true},undo?10000:5000)}
function remember(){history.push(clone());if(history.length>60)history.shift();future=[];updateHistory()}
function updateHistory(){$('#undo').disabled=!history.length;$('#redo').disabled=!future.length}
function persist(){clearTimeout(savedTimer);savedTimer=setTimeout(()=>{if(!write(DRAFT,state))toast('Browser storage is unavailable. Export a project to keep your work.');},400)}
function commit(patch,{record=true}={}){if(record)remember();state={...state,...patch};phase=0;dirty=true;sync();persist();if(soundOn)restartSound()}
function sync(){const mood=MOODS[state.mood];$$('[data-mood]').forEach(b=>{const active=b.dataset.mood===state.mood;b.classList.toggle('selected',active);b.setAttribute('aria-pressed',active)});$$('[data-form]').forEach(b=>{const active=b.dataset.form===state.form;b.classList.toggle('selected',active);b.setAttribute('aria-pressed',active)});for(const id of['energy','detail']){$('#'+id).value=state[id];$('#'+id+'-value').textContent=state[id];$('#'+id).style.setProperty('--progress',((state[id]-Number($('#'+id).min))/(Number($('#'+id).max)-Number($('#'+id).min))*100+'%')}if(document.activeElement!==$('#moment'))$('#moment').value=state.moment;$('#char-count').textContent=state.moment.length+' / 160';$('#art-title').textContent=state.title;$('#art-edition').textContent='01 — '+mood.name.toUpperCase()+' / '+state.form.toUpperCase();$('#art-description').textContent=description(state);canvas.setAttribute('aria-label',state.title+'. '+description(state));updateHistory();syncSoundLabel()}
function init(){const draft=validate(read(DRAFT,null));if(draft)state=draft;const stored=read(STORE,[]);if(Array.isArray(stored))collection=stored.filter(x=>x&&typeof x.id==='string'&&validate(x.state)).slice(0,24).map(x=>({id:x.id,date:typeof x.date==='string'?x.date:'',state:validate(x.state)}));try{if(location.hash.startsWith('#art=')){const raw=location.hash.slice(5);if(raw.length>3000)throw new Error();const shared=validate(JSON.parse(atob(raw)));if(!shared)throw new Error();state=shared;toast('A feeling, passed to you. Make this composition your own.')}}catch{toast('This remix link could not be opened. Your previous work is still here.')}$('#collection-count').textContent=collection.length;sync();setPaused(paused);resize();requestAnimationFrame(animate);if(!ctx)toast('Your browser cannot draw the canvas. Descriptions, sound, and SVG exports still work.');if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js',{scope:'./'}).catch(()=>{});}
function resize(){const rect=canvas.getBoundingClientRect(),ratio=Math.min(devicePixelRatio||1,1.6);canvas.width=Math.max(1,Math.round(rect.width*ratio));canvas.height=Math.max(1,Math.round(rect.height*ratio));dirty=true}
function paint(time=phase){if(!ctx)return;const w=canvas.width,h=canvas.height;ctx.setTransform(1,0,0,1,0,0);ctx.clearRect(0,0,w,h);let bg=ctx.createRadialGradient(w*.5,h*.46,0,w*.5,h*.46,Math.max(w,h)*.7);bg.addColorStop(0,'#25362f');bg.addColorStop(.58,'#17221d');bg.addColorStop(1,'#111715');ctx.fillStyle=bg;ctx.fillRect(0,0,w,h);const isExpanded=document.fullscreenElement||$('#canvas-wrap').classList.contains('expanded');const scale=isExpanded?Math.min(w/1000,h/850):Math.max(w/1000,h/850)*.94;ctx.translate(w/2,h/2);ctx.scale(scale,scale);ctx.translate(-500,-425);paths=geometry(state,time);ctx.globalCompositeOperation='screen';for(const p of paths){ctx.strokeStyle=p.color;ctx.globalAlpha=p.alpha;ctx.lineWidth=p.width;ctx.stroke(new Path2D(p.d))}ctx.globalAlpha=1;ctx.globalCompositeOperation='source-over';ctx.setTransform(1,0,0,1,0,0);renderCounter++}
function animate(now){frame=requestAnimationFrame(animate);if(document.hidden)return;if(dirty||(!paused&&now-lastFrame>80)){if(!paused)phase+=Math.min((now-lastFrame)/1000,.12)*(.2+state.energy*.004);paint();lastFrame=now;dirty=false}}
function setPaused(value){paused=value;$('#pause').setAttribute('aria-label',paused?'Resume animation':'Pause animation');$('#pause').title=paused?'Resume animation':'Pause animation';$('#pause use').setAttribute('href',paused?'#i-play':'#i-pause');$('#motion-state').textContent=paused?'STILL FRAME':'LIVING ART';dirty=true}
function undo(){if(!history.length)return;future.push(clone());state=history.pop();phase=0;dirty=true;sync();persist();if(soundOn)restartSound();toast('Last change undone.')}
function redo(){if(!future.length)return;history.push(clone());state=future.pop();phase=0;dirty=true;sync();persist();if(soundOn)restartSound();toast('Change restored.')}
$$('[data-mood]').forEach(b=>b.addEventListener('click',()=>{if(state.mood!==b.dataset.mood)commit({mood:b.dataset.mood,title:MOODS[b.dataset.mood].title})}));$$('[data-form]').forEach(b=>b.addEventListener('click',()=>{if(state.form!==b.dataset.form)commit({form:b.dataset.form})}));
for(const id of['energy','detail']){const el=$('#'+id);let previous=null;el.addEventListener('focus',()=>previous=clone());el.addEventListener('pointerdown',()=>previous=clone());el.addEventListener('input',()=>{if(!previous)previous=clone();state[id]=+el.value;dirty=true;sync()});el.addEventListener('change',()=>{if(previous&&previous[id]!==state[id]){history.push(previous);future=[];updateHistory();persist();if(soundOn)restartSound()}previous=clone()})}
let typingBefore=null,typingTimer;function finishTyping(){clearTimeout(typingTimer);if(typingBefore&&typingBefore.moment!==state.moment){history.push(typingBefore);future=[];updateHistory();persist();if(soundOn)restartSound()}typingBefore=null}
$('#moment').addEventListener('input',e=>{if(!typingBefore)typingBefore=clone();state.moment=e.target.value.slice(0,160);state.seed=state.moment?hash(state.moment):827391;dirty=true;sync();clearTimeout(typingTimer);typingTimer=setTimeout(finishTyping,600)});$('#moment').addEventListener('blur',finishTyping);
const prompts=['Sunlight finding its way through the curtains.','The quiet after the rain.','A conversation I wish could last a little longer.','Walking somewhere new with nowhere to be.','The first deep breath after a long day.','A small kindness I did not expect.'];let promptIndex=0;
$('#inspire').addEventListener('click',()=>{finishTyping();const moment=prompts[promptIndex++%prompts.length];commit({moment,seed:hash(moment)});toast('A starting point. Change these words to make them yours.')});
$('#remix').addEventListener('click',()=>{finishTyping();const bytes=new Uint32Array(1);crypto.getRandomValues(bytes);commit({seed:bytes[0]});toast('A new possibility. Undo takes you back.')});$('#undo').addEventListener('click',undo);$('#redo').addEventListener('click',redo);$('#pause').addEventListener('click',()=>setPaused(!paused));reduce.addEventListener('change',e=>{if(e.matches)setPaused(true)});
let expandedFocus=null;async function expand(){const wrap=$('#canvas-wrap');if(document.fullscreenElement){await document.exitFullscreen();return}if(wrap.classList.contains('expanded')){wrap.classList.remove('expanded');document.body.classList.remove('art-expanded');$('#fullscreen').setAttribute('aria-label','Expand artwork');$('#fullscreen use').setAttribute('href','#i-expand');resize();expandedFocus?.focus();return}expandedFocus=document.activeElement;if(wrap.requestFullscreen){try{await wrap.requestFullscreen();return}catch{}}wrap.classList.add('expanded');document.body.classList.add('art-expanded');$('#fullscreen').setAttribute('aria-label','Exit expanded artwork');$('#fullscreen use').setAttribute('href','#i-close');resize();$('#fullscreen').focus()}
$('#fullscreen').addEventListener('click',expand);document.addEventListener('fullscreenchange',()=>{$('#fullscreen').setAttribute('aria-label',document.fullscreenElement?'Exit expanded artwork':'Expand artwork');$('#fullscreen use').setAttribute('href',document.fullscreenElement?'#i-close':'#i-expand');resize()});new ResizeObserver(resize).observe($('#canvas-wrap'));
function openDialog(id){finishTyping();const d=$('#'+id);d.showModal();return d}
$$('[data-dialog]').forEach(b=>b.addEventListener('click',()=>openDialog(b.dataset.dialog)));$$('.close-dialog').forEach(b=>b.addEventListener('click',()=>b.closest('dialog').close()));$$('dialog').forEach(d=>{d.addEventListener('click',e=>{if(e.target===d){const r=d.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)d.close()}});d.addEventListener('close',()=>{if('speechSynthesis'in window){speechSynthesis.cancel();$('#read-description span').textContent='Read aloud'}})});$('#open-guide').addEventListener('click',()=>openDialog('guide-dialog'));
$('#describe').addEventListener('click',()=>{const panel=$('#description-panel');panel.hidden=!panel.hidden;$('#describe').setAttribute('aria-expanded',!panel.hidden);if(!panel.hidden)panel.scrollIntoView({block:'nearest',behavior:reduce.matches?'instant':'smooth'})});$('#describe').setAttribute('aria-expanded','false');$('#describe').setAttribute('aria-controls','description-panel');
$('#read-description').addEventListener('click',()=>{if(!('speechSynthesis'in window)){toast('Read-aloud is unavailable in this browser. The full description is shown here.');return}if(speechSynthesis.speaking){speechSynthesis.cancel();$('#read-description span').textContent='Read aloud';return}const utterance=new SpeechSynthesisUtterance(description(state));utterance.rate=.9;utterance.onend=utterance.onerror=()=>{$('#read-description span').textContent='Read aloud'};speechSynthesis.speak(utterance);$('#read-description span').textContent='Stop reading'});
function syncSoundLabel(){$('#sound').setAttribute('aria-pressed',soundOn);$('#sound-label').textContent=soundOn?'You’re listening to '+MOODS[state.mood].name.toLowerCase()+'.':'There’s a sound to this feeling.';$('#sound-subtitle').textContent=soundOn?tempo(state)+' BPM · generated from your artwork · tap to stop':'Put on your headphones. Tap to listen.'}
async function startSound(){try{if(!ctxAudio){const AudioContext=window.AudioContext||window.webkitAudioContext;if(!AudioContext)throw new Error();ctxAudio=new AudioContext()}await ctxAudio.resume();if(ctxAudio.state!=='running')throw new Error();soundOn=true;queueSound();syncSoundLabel()}catch{soundOn=false;syncSoundLabel();toast('Sound is unavailable. Try another browser, or explore the artwork description.')}}
function queueSound(){if(!soundOn)return;if(audioBus){const old=audioBus;old.gain.setTargetAtTime(0,ctxAudio.currentTime,.08);setTimeout(()=>old.disconnect(),500)}audioBus=ctxAudio.createGain();audioBus.gain.value=.38;audioBus.connect(ctxAudio.destination);const start=ctxAudio.currentTime+.07;for(const n of notePlan(state,12))scheduleNote(ctxAudio,audioBus,n,start);audioTimer=setTimeout(queueSound,12000)}
function stopSound(){soundOn=false;clearTimeout(audioTimer);if(audioBus&&ctxAudio){audioBus.gain.setTargetAtTime(0,ctxAudio.currentTime,.06);const old=audioBus;setTimeout(()=>old.disconnect(),400);audioBus=null}syncSoundLabel()}
function restartSound(){clearTimeout(audioTimer);queueSound()}
$('#sound').addEventListener('click',()=>soundOn?stopSound():startSound());document.addEventListener('visibilitychange',()=>{if(document.hidden){stopSound();if('speechSynthesis'in window)speechSynthesis.cancel()}else{lastFrame=performance.now();dirty=true}});
$('#save').addEventListener('click',()=>{if(collection.length>=24){toast('Your collection has 24 moments. Export a backup, then remove one to make room.');showCollection();return}$('#save-title').value=state.title;openDialog('save-dialog');setTimeout(()=>$('#save-title').select(),50)});
$('#save-form').addEventListener('submit',e=>{e.preventDefault();finishTyping();const title=$('#save-title').value.trim();if(!title){$('#save-title').setCustomValidity('Give this moment a name.');$('#save-title').reportValidity();return}$('#save-title').setCustomValidity('');const item={id:crypto.randomUUID(),date:new Date().toISOString(),state:{...state,title}};const next=[item,...collection];if(!write(STORE,next)){toast('This browser could not save your work. Export an editable project instead.');return}collection=next;state.title=title;sync();persist();$('#collection-count').textContent=collection.length;$('#save-dialog').close();toast('A little piece of you, kept in your collection.')});$('#save-title').addEventListener('input',()=>$('#save-title').setCustomValidity(''));
function showCollection(){renderCollection();openDialog('collection-dialog')}
function make(tag,className,text){const e=document.createElement(tag);if(className)e.className=className;if(text!==undefined)e.textContent=text;return e}
function renderCollection(){const grid=$('#collection-grid');grid.replaceChildren();$('#collection-count').textContent=collection.length;$('#storage-count').textContent=collection.length+' / 24 moments';if(!collection.length){const empty=make('div','collection-empty');empty.innerHTML='<svg aria-hidden="true"><use href="#i-save"/></svg><h3>Your first moment is waiting.</h3><p>Make something in the studio, then choose “Keep this moment”.</p>';grid.append(empty);return}for(const item of collection){const card=make('article','collection-card'),open=make('button','open-art'),img=make('img');img.src='data:image/svg+xml;charset=utf-8,'+encodeURIComponent(svgArt(item.state,{quality:.4}));img.alt=description(item.state);img.loading='lazy';open.append(img,make('h3','',item.state.title));open.setAttribute('aria-label','Open '+item.state.title);open.addEventListener('click',()=>{remember();state=clone(item.state);phase=0;dirty=true;sync();persist();if(soundOn)restartSound();$('#collection-dialog').close();toast('Moment reopened. Your previous composition is one Undo away.')});const meta=make('div','card-meta');meta.append(make('span','',MOODS[item.state.mood].name.toUpperCase()+' / '+item.state.form.toUpperCase()));const remove=make('button','icon-btn');remove.setAttribute('aria-label','Remove '+item.state.title);remove.innerHTML='<svg><use href="#i-trash"/></svg>';remove.addEventListener('click',()=>{const index=collection.findIndex(x=>x.id===item.id),next=collection.filter(x=>x.id!==item.id);if(!write(STORE,next)){toast('Could not update storage. This moment has not been removed.');return}deleted={item,index};collection=next;renderCollection();toast('Moment removed. You can undo this.',true)});meta.append(remove);card.append(open,meta);grid.append(card)}}
$('#collection-nav').addEventListener('click',showCollection);$('#toast-undo').addEventListener('click',()=>{if(!deleted)return;if(collection.length>=24){toast('Your collection is full. Remove a moment before restoring this one.');return}const next=[...collection];next.splice(deleted.index,0,deleted.item);if(write(STORE,next)){collection=next;deleted=null;renderCollection();toast('Moment restored.')}else toast('Could not restore this moment. Browser storage is unavailable.')});
$('#import').addEventListener('click',()=>$('#import-file').click());$('#import-file').addEventListener('change',async e=>{const file=e.target.files[0];if(!file)return;try{if(file.size>16384)throw new Error('size');const parsed=JSON.parse(await file.text());const clean=validate(parsed.state||parsed);if(!clean)throw new Error('format');remember();state=clean;phase=0;dirty=true;sync();persist();if(soundOn)restartSound();$('#collection-dialog').close();toast('Project opened. Choose “Keep this moment” to add it to your collection.')}catch{toast('That file is not a valid Sonder project. Choose an exported JSON file under 16 KB.')}finally{e.target.value=''}});
$('#export').addEventListener('click',()=>openDialog('export-dialog'));
function download(data,name,type){const blob=data instanceof Blob?data:new Blob([data],{type}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),30000)}
function fileName(ext){return'sonder-'+state.mood+'-'+state.seed+'.'+ext}
async function exportArt(type){const buttons=$$('[data-export]');buttons.forEach(b=>b.disabled=true);$('#export-status').textContent='Preparing your '+type.toUpperCase()+'…';try{if(type==='svg'){download(svgArt(state,{caption:true}),fileName('svg'),'image/svg+xml')}
 else if(type==='json'){download(JSON.stringify({app:'Sonder',version:1,state,description:description(state)},null,2),fileName('json'),'application/json')}
 else if(type==='png'){const s=svgArt(state,{caption:true}),url=URL.createObjectURL(new Blob([s],{type:'image/svg+xml'}));try{const image=new Image();image.src=url;await image.decode();const c=document.createElement('canvas');c.width=2400;c.height=2040;const x=c.getContext('2d');if(!x)throw new Error();x.drawImage(image,0,0,c.width,c.height);const blob=await new Promise(resolve=>c.toBlob(resolve,'image/png'));if(!blob)throw new Error();download(blob,fileName('png'),'image/png')}finally{URL.revokeObjectURL(url)}}
 else if(type==='wav'){const Offline=window.OfflineAudioContext||window.webkitOfflineAudioContext;if(!Offline)throw new Error();const offline=new Offline(2,44100*12,44100),bus=offline.createGain();bus.gain.setValueAtTime(.6,0);bus.gain.setValueAtTime(.6,10.5);bus.gain.linearRampToValueAtTime(0,12);bus.connect(offline.destination);for(const n of notePlan(state,12))scheduleNote(offline,bus,n,0);const buffer=await offline.startRendering();download(wavFromBuffer(buffer),fileName('wav'),'audio/wav')}
 $('#export-status').textContent='Your '+type.toUpperCase()+' is ready. Check your downloads.';toast('Your '+type.toUpperCase()+' is ready to keep.');}catch{$('#export-status').textContent='This export did not complete. Try again, or choose an editable project to keep your work.'}finally{buttons.forEach(b=>b.disabled=false)}}
$$('[data-export]').forEach(b=>b.addEventListener('click',()=>exportArt(b.dataset.export)));
$('#share').addEventListener('click',()=>{const shared={version:1,mood:state.mood,form:state.form,energy:state.energy,detail:state.detail,seed:state.seed};const url=new URL(location.href);url.hash='art='+btoa(JSON.stringify(shared));$('#share-url').value=url.href;$('#share-status').textContent='No account or public gallery. Just a link.';openDialog('share-dialog')});$('#copy-link').addEventListener('click',async()=>{try{await navigator.clipboard.writeText($('#share-url').value);$('#share-status').textContent='Copied. Share it with someone who could use a creative moment.';toast('Remix link copied. Your written moment stays private.')}catch{$('#share-url').focus();$('#share-url').select();$('#share-status').textContent='Copy is unavailable here. Select and copy the link above.'}});
document.addEventListener('keydown',e=>{if(e.key==='Escape'&&$('#canvas-wrap').classList.contains('expanded')){e.preventDefault();expand()}const typing=['INPUT','TEXTAREA','SELECT'].includes(document.activeElement?.tagName);if(typing||$('dialog[open]'))return;if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='z'){e.preventDefault();e.shiftKey?redo():undo()}if($('#canvas-wrap').classList.contains('expanded')&&e.key==='Tab'){const buttons=[$('#pause'),$('#fullscreen')];if(e.shiftKey&&document.activeElement===buttons[0]){e.preventDefault();buttons[1].focus()}else if(!e.shiftKey&&document.activeElement===buttons[1]){e.preventDefault();buttons[0].focus()}}});
function connectivity(){$('#connection-status').textContent=navigator.onLine?'Local-first by design':'Offline · keep creating'}window.addEventListener('online',connectivity);window.addEventListener('offline',connectivity);window.addEventListener('pagehide',()=>{finishTyping();clearTimeout(savedTimer);write(DRAFT,state);stopSound()});
window.addEventListener('storage',e=>{if(e.key===STORE){const stored=read(STORE,[]);if(Array.isArray(stored)){collection=stored.filter(x=>x&&typeof x.id==='string'&&validate(x.state)).slice(0,24);renderCollection();toast('Your collection was updated in another tab.')}}});
init();connectivity();
