// Sonder's deterministic, dependency-free art and sound recipe.
export const VERSION=1;
export const MOODS={
 still:{name:'Still',colors:['#91c8b1','#d9ddad','#b7a7d8','#7cacc5'],colorWords:'sea-glass green, pale gold, lavender, and soft blue',notes:[0,2,4,7,9],root:48,title:'The quiet between'},
 radiant:{name:'Radiant',colors:['#ecaf65','#edd899','#e58c72','#e1b997'],colorWords:'sunlit amber, butter yellow, coral, and warm sand',notes:[0,4,7,9,12],root:50,title:'A little more light'},
 curious:{name:'Curious',colors:['#aba0eb','#7cbbd7','#da9dce','#a3d9c1'],colorWords:'violet, sky blue, orchid, and mint',notes:[0,2,6,7,11],root:53,title:'What if we wandered'},
 tender:{name:'Tender',colors:['#dca7a4','#d8ba94','#b4a1c7','#e9c4b7'],colorWords:'dusty rose, warm ochre, lilac, and peach',notes:[0,3,5,7,10],root:45,title:'Soft places to land'}
};
export const FORMS=['flow','bloom','orbit'];
export function hash(text){let h=2166136261;for(let i=0;i<text.length;i++){h^=text.charCodeAt(i);h=Math.imul(h,16777619)}return h>>>0}
export function random(seed){let s=seed>>>0;return()=>{s+=0x6D2B79F5;let t=s;t=Math.imul(t^t>>>15,t|1);t^=t+Math.imul(t^t>>>7,t|61);return((t^t>>>14)>>>0)/4294967296}}
export function defaults(){return{version:1,mood:'still',form:'flow',energy:42,detail:58,seed:827391,moment:'',title:MOODS.still.title}}
export function validate(value){if(!value||typeof value!=='object'||value.version!==1||!Object.hasOwn(MOODS,value.mood)||!FORMS.includes(value.form)||!Number.isInteger(value.seed)||value.seed<0||value.seed>4294967295||!Number.isFinite(value.energy)||value.energy<0||value.energy>100||!Number.isFinite(value.detail)||value.detail<10||value.detail>100)return null;return{version:1,mood:value.mood,form:value.form,energy:Math.round(value.energy),detail:Math.round(value.detail),seed:value.seed,moment:typeof value.moment==='string'?value.moment.slice(0,160):'',title:typeof value.title==='string'&&value.title.trim()?value.title.trim().slice(0,60):MOODS[value.mood].title}}
export function description(s){const mood=MOODS[s.mood],forms={flow:'A ribbon of fine, looping contours folds around an open center, like silk caught in a slow current',bloom:'Petal-like rings unfold from an open center, forming an irregular, layered flower',orbit:'Tilted elliptical contours cross and gather around an open center, like a small celestial system'};return`${forms[s.form]}. Its lines move through ${mood.colorWords} against a deep charcoal-green background. Energy is ${s.energy} out of 100: ${s.energy<35?'a calm, softly shaped composition':s.energy<70?'a gently expressive, flowing composition':'a restless composition with pronounced ripples'}. Intricacy is ${s.detail} out of 100, shaping ${lineCount(s)} contours. Its sound uses a ${mood.name.toLowerCase()}-inspired five-note palette at ${tempo(s)} beats per minute. These are creative associations, not a reading of your emotions.`}
export function lineCount(s){return Math.round(90+s.detail*1.6)}
export function tempo(s){return Math.round(46+s.energy*.6)}
function rgb(hex){return[1,3,5].map(i=>parseInt(hex.slice(i,i+2),16))}
function blend(a,b,t){const x=rgb(a),y=rgb(b);return`rgb(${x.map((v,i)=>Math.round(v+(y[i]-v)*t)).join(',')})`}
export function geometry(s,time=0,quality=1){const count=Math.round(lineCount(s)*quality),points=Math.round(150*quality),rand=random(s.seed),phase=rand()*Math.PI*2,tilt=-.36+(rand()-.5)*.5,ct=Math.cos(tilt),st=Math.sin(tilt),colors=MOODS[s.mood].colors,out=[],energy=s.energy/100;
 for(let n=0;n<count;n++){let d='',u=n/(count-1),v=u*Math.PI*2,wobble=phase+time*.17;for(let j=0;j<=points;j++){let a=j/points*Math.PI*2,x,y;
 if(s.form==='bloom'){const r=172+u*120+(24+energy*33)*Math.sin(a*5+wobble+u*2.3)+15*Math.cos(a*3-u*3);x=Math.cos(a)*r;y=Math.sin(a)*r*.95;}
 else if(s.form==='orbit'){const r=182+u*140;x=Math.cos(a)*r+Math.sin(a*3+wobble)*(16+energy*30);y=Math.sin(a)*(100+u*125)+Math.cos(a*2+u*3+wobble)*(30+energy*58);const rot=Math.sin(u*2.2+wobble*.2)*.65;const xx=x;x=x*Math.cos(rot)-y*Math.sin(rot);y=xx*Math.sin(rot)+y*Math.cos(rot);}
 else{const r=185+u*132;x=Math.cos(a)*r+(26+energy*53)*Math.sin(a*3+wobble+u*3.5);y=Math.sin(a)*(118+u*117)+(48+energy*55)*Math.cos(a*2+u*3.2+wobble);}
 const ripple=Math.sin(a*(7+Math.floor(s.detail/25))+v+wobble)*energy*6;x+=ripple;y+=ripple*.5;let px=500+(x*ct-y*st),py=410+(x*st+y*ct);d+=(j?'L':'M')+px.toFixed(2)+','+py.toFixed(2);}
 d+='Z';const ci=u*(colors.length-1),idx=Math.min(colors.length-2,Math.floor(ci));out.push({d,color:blend(colors[idx],colors[idx+1],ci-idx),alpha:.30+.48*Math.pow(Math.sin(u*Math.PI),.6),width:.65+(1-u)*.25});}return out}
export function escapeXML(s){return String(s).replace(/[<>&"']/g,c=>({'<':'&lt;','>':'&gt;','&':'&amp;','"':'&quot;',"'":'&apos;'}[c]))}
export function svgArt(s,{caption=false,quality=1}={}){const paths=geometry(s,0,quality);let svg=`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1000 850" width="1000" height="850" role="img"><title>${escapeXML(s.title)}</title><desc>${escapeXML(description(s))}</desc><defs><radialGradient id="bg"><stop stop-color="#24352f"/><stop offset=".7" stop-color="#161f1c"/><stop offset="1" stop-color="#111715"/></radialGradient></defs><rect width="1000" height="850" fill="url(#bg)"/>`;for(const p of paths)svg+=`<path d="${p.d}" stroke="${p.color}" stroke-opacity="${p.alpha.toFixed(3)}" stroke-width="${p.width}" fill="none"/>`;if(caption)svg+=`<text x="55" y="60" fill="#c6d0bb" font-family="monospace" font-size="10" letter-spacing="3">SONDER / A STUDY IN FEELING</text><text x="55" y="775" fill="#e6eddc" font-family="Georgia,serif" font-style="italic" font-size="30">${escapeXML(s.title)}</text><text x="55" y="807" fill="#b3c1a5" font-family="monospace" font-size="10" letter-spacing="2">${MOODS[s.mood].name.toUpperCase()} / ${s.form.toUpperCase()} / SEED ${s.seed}</text>`;return svg+'</svg>'}
export function notePlan(s,duration=12){const rng=random(s.seed),interval=60/tempo(s),scale=MOODS[s.mood],notes=[];for(let t=0;t<duration-.6;t+=interval){let pitch=scale.root+scale.notes[Math.floor(rng()*5)]+(rng()>.7?24:12);notes.push({time:t,midi:pitch,length:Math.min(3.1,interval*2.8),gain:.10,pan:(rng()-.5)*1.4});if(s.detail>55&&t+interval*.5<duration-.6)notes.push({time:t+interval*.5,midi:scale.root+scale.notes[Math.floor(rng()*5)]+24,length:1.8,gain:.035,pan:(rng()-.5)*1.2})}return notes}
export function scheduleNote(ctx,destination,n,start=0){const osc=ctx.createOscillator(),overtone=ctx.createOscillator(),gain=ctx.createGain(),overtoneGain=ctx.createGain(),pan=ctx.createStereoPanner();const t=start+n.time;osc.type='sine';overtone.type='sine';const f=440*Math.pow(2,(n.midi-69)/12);osc.frequency.value=f;overtone.frequency.value=f*2;gain.gain.setValueAtTime(0,t);gain.gain.linearRampToValueAtTime(n.gain,t+.035);gain.gain.exponentialRampToValueAtTime(.0001,t+n.length);overtoneGain.gain.value=.13;pan.pan.value=n.pan;osc.connect(gain);overtone.connect(overtoneGain);overtoneGain.connect(gain);gain.connect(pan);pan.connect(destination);osc.start(t);overtone.start(t);osc.stop(t+n.length+.05);overtone.stop(t+n.length+.05);osc.onended=()=>{osc.disconnect();overtone.disconnect();overtoneGain.disconnect();gain.disconnect();pan.disconnect()};}
export function wavFromBuffer(buffer){const channels=buffer.numberOfChannels,length=buffer.length,bytes=length*channels*2,ab=new ArrayBuffer(44+bytes),v=new DataView(ab);const str=(at,s)=>[...s].forEach((c,i)=>v.setUint8(at+i,c.charCodeAt(0)));str(0,'RIFF');v.setUint32(4,36+bytes,true);str(8,'WAVE');str(12,'fmt ');v.setUint32(16,16,true);v.setUint16(20,1,true);v.setUint16(22,channels,true);v.setUint32(24,buffer.sampleRate,true);v.setUint32(28,buffer.sampleRate*channels*2,true);v.setUint16(32,channels*2,true);v.setUint16(34,16,true);str(36,'data');v.setUint32(40,bytes,true);const data=Array.from({length:channels},(_,i)=>buffer.getChannelData(i));for(let i=0;i<length;i++)for(let c=0;c<channels;c++){const x=Math.max(-1,Math.min(1,data[c][i]));v.setInt16(44+(i*channels+c)*2,x<0?x*32768:x*32767,true)}return ab}
