'use strict';
// Replace concept entries with your own project descriptions and photo paths.
// Set image: './images/your-print.webp' to show a photograph instead of a render.
const PROJECTS = [
 {id:'helix',name:'Helix Vessel',category:'sculptural',kind:'vase',color:'cobalt',background:'#e6e7df',subtitle:'Twisted geometry · Vessel study',material:'Matte PLA',dimensions:'Ø 110 × 210 mm',description:'A continuous twist gives a simple vessel its quiet movement. Deep flutes catch the light differently from every angle — an exploration of repetition, rhythm, and the beauty of a visible layer.',image:null},
 {id:'orbit',name:'Orbit Study',category:'sculptural',kind:'orbit',color:'clay',background:'#e9e1d6',subtitle:'An endless line · Sculptural object',material:'Terracotta PLA',dimensions:'160 × 160 × 85 mm',description:'A single looping form, folded back into itself. Orbit explores the tension between lightness and volume: a small sculptural gesture with no prescribed function other than to invite a second look.',image:null},
 {id:'pleat',name:'Pleat Light',category:'functional',kind:'lamp',color:'chalk',background:'#dedfd5',subtitle:'Soft light · Shade concept',material:'Translucent PLA',dimensions:'Ø 190 × 240 mm',description:'A pleated shade that turns a simple silhouette into a field of soft shadows. This is a visual lighting concept, not a tested electrical product. Any physical version requires a suitable low-heat LED and thermal testing.',image:null},
 {id:'arc',name:'Arc Bookend',category:'functional',kind:'arch',color:'sage',background:'#e2e5dc',subtitle:'Everyday architecture · Desk object',material:'Sage PLA',dimensions:'130 × 150 × 80 mm',description:'A little piece of architecture for a shelf. A generous arch and rounded edges balance a sturdy silhouette. A printed version would need weight and stability testing before supporting books.',image:null},
 {id:'ripple',name:'Ripple Bowl',category:'functional',kind:'bowl',color:'cobalt',background:'#e1e3e7',subtitle:'Concentric calm · Catchall concept',material:'Matte PLA',dimensions:'Ø 190 × 65 mm',description:'A shallow landscape for the small things that gather at the end of a day. Concentric layers and an undulating rim turn an everyday catchall into a tactile object. Intended for dry, non-food use.',image:null},
 {id:'totem',name:'Soft Totem',category:'sculptural',kind:'totem',color:'clay',background:'#e9e3da',subtitle:'Stacked silhouettes · Form experiment',material:'Clay-colored PLA',dimensions:'Ø 95 × 230 mm',description:'Three soft volumes, one continuous silhouette. Soft Totem plays with balance and the unexpected warmth of digitally generated forms — an experiment in making a rigid material feel gentle.',image:null}
];
const COLORS={cobalt:[48,57,205],clay:[183,91,57],chalk:[215,204,177],sage:[115,130,98]};
const $=s=>document.querySelector(s);
let reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
let motionOff=reduced;
try{const pref=localStorage.getItem('layerform-motion');if(pref!==null)motionOff=pref==='off'||reduced;}catch{}
let renders=[],heroRenderer,detailRenderer,selectedProject=0,filtered=PROJECTS;
const dialog=$('#project-dialog');
function setMotion(off){motionOff=off;document.body.classList.toggle('motion-off',off);$('.motion-toggle').setAttribute('aria-pressed',String(off));$('.motion-text').textContent=off?'Enable motion':'Pause motion';$('.motion-icon').textContent=off?'▷':'Ⅱ';$('.motion-toggle').title=off?'Enable decorative animations':'Turn off decorative animations';try{localStorage.setItem('layerform-motion',off?'off':'on')}catch{}if(heroRenderer){heroRenderer.scrollOffset=0;heroRenderer.draw()}}
$('.motion-toggle').addEventListener('click',()=>setMotion(!motionOff));
matchMedia('(prefers-reduced-motion: reduce)').addEventListener('change',e=>{reduced=e.matches;setMotion(e.matches)});
setMotion(motionOff);
// Original parametric geometry, rendered locally. No 3D library or remote image dependency.
const TAU=Math.PI*2;
function point(kind,u,v){const a=u*TAU;
 if(kind==='orbit'){const t=v*TAU,r=.29;const c=[1.04*Math.cos(a),1.04*Math.sin(a),.30*Math.sin(2*a)];return[c[0]+r*Math.cos(t)*Math.cos(a),c[1]+r*Math.cos(t)*Math.sin(a),c[2]+r*Math.sin(t)]}
 if(kind==='arch'){const t=Math.PI*u,r=.55+v*.62;return[r*Math.cos(t),r*Math.sin(t)-.5,0]}
 let y,r;
 if(kind==='vase'){y=(v-.5)*3.0;const body=.60+.32*Math.sin(v*Math.PI)-.22*Math.exp(-Math.pow((v-.82)*5,2));r=body*(1+.092*Math.cos(13*a+v*3.7));}
 else if(kind==='lamp'){y=(v-.5)*2.6;if(v<.14){r=.52; y=-1.3+v*1.5}else if(v<.32){r=.11;y=-1.09+(v-.14)*4.4}else{const w=(v-.32)/.68;y=-.30+w*1.6;r=(1.0-.48*w)*(1+.052*Math.cos(42*a));}}
 else if(kind==='bowl'){y=(v-.5)*.95;r=(.28+1.15*Math.sin(v*Math.PI*.50))*(1+.035*Math.cos(17*a+v));y+=.035*Math.cos(17*a)*v;}
 else{y=(v-.5)*3.0;r=(.34+.39*Math.pow(Math.sin(v*Math.PI*3),2))*(1+.015*Math.cos(24*a));}
 return[r*Math.cos(a),y,r*Math.sin(a)];
}
function sub(a,b){return a.map((v,i)=>v-b[i])}function cross(a,b){return[a[1]*b[2]-a[2]*b[1],a[2]*b[0]-a[0]*b[2],a[0]*b[1]-a[1]*b[0]]}function norm(a){const l=Math.hypot(...a)||1;return a.map(v=>v/l)}
const meshCache=new Map();
function mesh(kind){if(meshCache.has(kind))return meshCache.get(kind);let faces=[];
 function face(p,col=1,normal){const n=normal||norm(cross(sub(p[1],p[0]),sub(p[3],p[0])));faces.push({p,n,col})}
 if(kind==='arch'){const steps=96;for(let i=0;i<steps;i++){const a=i/steps,b=(i+1)/steps;for(const z of [-.39,.39]){let p=[point(kind,a,0),point(kind,b,0),point(kind,b,1),point(kind,a,1)].map(p=>[p[0],p[1],z]);face(p,1,[0,0,z>0?1:-1]);}for(const v of [0,1]){const p=point(kind,a,v),q=point(kind,b,v);face([[...p.slice(0,2),-.39],[...q.slice(0,2),-.39],[...q.slice(0,2),.39],[...p.slice(0,2),.39]],v?1:.7,[(v?1:-1)*Math.cos((a+b)*Math.PI/2),(v?1:-1)*Math.sin((a+b)*Math.PI/2),0]);}}for(const u of [0,1]){const a=point(kind,u,0),b=point(kind,u,1);face([[a[0],a[1],-.39],[b[0],b[1],-.39],[b[0],b[1],.39],[a[0],a[1],.39]],.8,[0,-1,0])}}
 else{const nu=kind==='lamp'?168:104,nv=kind==='orbit'?32:85;for(let j=0;j<nv;j++)for(let i=0;i<nu;i++){const p=[point(kind,i/nu,j/nv),point(kind,(i+1)/nu,j/nv),point(kind,(i+1)/nu,(j+1)/nv),point(kind,i/nu,(j+1)/nv)];face(p,j%2===0?1:.965)}
 if(kind!=='orbit'){const top=point(kind,0,1)[1];for(let i=0;i<nu;i++){const a=point(kind,i/nu,1),b=point(kind,(i+1)/nu,1),inner=kind==='bowl'?.89:.82;face([a,b,[b[0]*inner,b[1]-.03,b[2]*inner],[a[0]*inner,a[1]-.03,a[2]*inner]],1.15,[0,1,0]);if(kind==='vase'||kind==='bowl'){face([[a[0]*inner,a[1]-.03,a[2]*inner],[b[0]*inner,b[1]-.03,b[2]*inner],[b[0]*.6,top-.5,b[2]*.6],[a[0]*.6,top-.5,a[2]*.6]],.44);face([[a[0]*.6,top-.5,a[2]*.6],[b[0]*.6,top-.5,b[2]*.6],[0,top-.5,0],[0,top-.5,0]],.30,[0,1,0])}else{face([a,b,[0,top,0],[0,top,0]],.8,[0,1,0])}}}
 }
 meshCache.set(kind,faces);return faces;}
class Sculpture{
 constructor(canvas,kind,color,interactive=false){this.canvas=canvas;this.ctx=canvas.getContext('2d');this.kind=kind;this.color=color;this.angle=kind==='arch'?-.48:.25;this.scrollOffset=0;this.faces=mesh(kind);this.raf=0;this.visible=true;this.resizeObserver=new ResizeObserver(()=>this.queue());this.resizeObserver.observe(canvas);this.visibilityObserver=new IntersectionObserver(es=>{this.visible=es[0].isIntersecting;if(this.visible)this.queue()});this.visibilityObserver.observe(canvas);if(interactive)this.interact();renders.push(this);this.queue()}
 queue(){if(this.raf)return;this.raf=requestAnimationFrame(()=>{this.raf=0;this.draw()})}
 update(kind,color){this.kind=kind;this.color=color;this.faces=mesh(kind);this.angle=kind==='arch'?-.48:.25;this.queue()}
 interact(){let x=null,moved=false;this.canvas.addEventListener('pointerdown',e=>{if(e.button!==0)return;x=e.clientX;moved=false;this.canvas.setPointerCapture(e.pointerId)});this.canvas.addEventListener('pointermove',e=>{if(x===null)return;const dx=e.clientX-x;if(Math.abs(dx)>1)moved=true;this.angle+=dx*.012;x=e.clientX;this.queue()});const release=()=>{x=null;};this.canvas.addEventListener('pointerup',release);this.canvas.addEventListener('pointercancel',release);this.canvas.addEventListener('lostpointercapture',release);this.canvas.addEventListener('keydown',e=>{if(['ArrowLeft','ArrowRight','Home'].includes(e.key)){e.preventDefault();this.angle=e.key==='Home'?.25:this.angle+(e.key==='ArrowLeft'?-.15:.15);this.queue()}})}
 draw(){const canvas=this.canvas,c=this.ctx;if(!c)return;const w=canvas.clientWidth,h=canvas.clientHeight;if(!w||!h)return;const dpr=Math.min(devicePixelRatio||1,1.7);if(canvas.width!==Math.round(w*dpr)||canvas.height!==Math.round(h*dpr)){canvas.width=Math.round(w*dpr);canvas.height=Math.round(h*dpr)}c.setTransform(dpr,0,0,dpr,0,0);c.clearRect(0,0,w,h);
 const angle=this.angle+this.scrollOffset,ca=Math.cos(angle),sa=Math.sin(angle),tilt=this.kind==='bowl'?.67:.22,ct=Math.cos(tilt),st=Math.sin(tilt);const scale=Math.min(w*.31,h*.275)*(this.kind==='arch'?1.2:this.kind==='orbit'?1.02:1);const centerY=h*(this.kind==='arch'?.48:.47);
 const rot=p=>{const x=p[0]*ca+p[2]*sa,z=-p[0]*sa+p[2]*ca;return[x,p[1]*ct-z*st,p[1]*st+z*ct]};const project=p=>[w/2+p[0]*scale,centerY-p[1]*scale];
 const shadowY=centerY+scale*(this.kind==='bowl'?.55:this.kind==='arch'?.57:1.55);c.save();c.translate(w/2,shadowY);c.scale(1,.20);const gradient=c.createRadialGradient(0,0,0,0,0,scale*1.25);gradient.addColorStop(0,'rgba(41,42,32,.23)');gradient.addColorStop(.45,'rgba(41,42,32,.09)');gradient.addColorStop(1,'rgba(41,42,32,0)');c.fillStyle=gradient;c.beginPath();c.arc(0,0,scale*1.25,0,TAU);c.fill();c.restore();
 const color=COLORS[this.color]||COLORS.cobalt;const light=norm([-.65,.85,1]);const fs=this.faces.map(f=>{const p=f.p.map(rot);return{p,n:rot(f.n),col:f.col,z:p.reduce((a,p)=>a+p[2],0)/4}}).sort((a,b)=>a.z-b.z);
 for(const f of fs){let dot=f.n.reduce((a,n,i)=>a+n*light[i],0);if(this.kind==='orbit')dot=Math.abs(dot)*.85;const brightness=(.49+Math.max(0,dot)*.70)*f.col;const spec=Math.pow(Math.max(0,dot),16)*.10;const rgb=color.map(v=>Math.min(255,Math.round(v*brightness+255*spec)));c.fillStyle=`rgb(${rgb.join(',')})`;c.strokeStyle=c.fillStyle;c.lineWidth=.55;c.lineJoin='round';c.beginPath();f.p.forEach((p,i)=>{const a=project(p);i?c.lineTo(...a):c.moveTo(...a)});c.closePath();c.fill();c.stroke()}
 }
 destroy(){cancelAnimationFrame(this.raf);this.resizeObserver.disconnect();this.visibilityObserver.disconnect();renders=renders.filter(r=>r!==this)}
}
let galleryRenderers=[];
function buildGallery(filter='all'){galleryRenderers.forEach(r=>r.destroy());galleryRenderers=[];filtered=PROJECTS.filter(p=>filter==='all'||p.category===filter);const gallery=$('#gallery');gallery.replaceChildren();filtered.forEach(p=>{const index=PROJECTS.indexOf(p);const article=document.createElement('article');article.className='project-card reveal';const button=document.createElement('button');button.type='button';button.setAttribute('aria-label',`Explore ${p.name}, ${p.category} concept`);button.innerHTML=`<div class="project-visual" style="--card-bg:${p.background}"><span class="project-number">${String(index+1).padStart(2,'0')} /</span><span class="project-type">CONCEPT STUDY</span>${p.image?'<img loading="lazy" alt="">':'<canvas aria-hidden="true"></canvas>'}<span class="project-view" aria-hidden="true">↗</span></div><div class="project-info"><div><h3>${p.name}</h3><p>${p.subtitle}</p></div><span>${String(index+1).padStart(2,'0')}</span></div>`;button.addEventListener('click',()=>openProject(index));article.append(button);gallery.append(article);if(p.image){const img=button.querySelector('img');img.src=p.image;img.alt=p.name;img.addEventListener('error',()=>{img.replaceWith(Object.assign(document.createElement('p'),{textContent:'Photo unavailable. Open project for details.'}))})}else galleryRenderers.push(new Sculpture(button.querySelector('canvas'),p.kind,p.color));if(revealObserver)revealObserver.observe(article)});$('#result-count').textContent=`${filtered.length} objects`;}
$('.filters').addEventListener('click',e=>{const button=e.target.closest('button');if(!button)return;$('.filters').querySelectorAll('button').forEach(b=>b.setAttribute('aria-pressed',String(b===button)));buildGallery(button.dataset.filter)});
let previousFocus=null;
function showProject(index){selectedProject=(index+PROJECTS.length)%PROJECTS.length;const p=PROJECTS[selectedProject];$('#dialog-title').textContent=p.name;$('#dialog-category').textContent=`${p.category.toUpperCase()} / CONCEPT ${String(selectedProject+1).padStart(2,'0')}`;$('#dialog-description').textContent=p.description;$('#dialog-specs').replaceChildren();[['Proposed material',p.material],['Target dimensions',p.dimensions],['Status','Digital concept']].forEach(([a,b])=>{const row=document.createElement('div'),dt=document.createElement('dt'),dd=document.createElement('dd');dt.textContent=a;dd.textContent=b;row.append(dt,dd);$('#dialog-specs').append(row)});$('#project-position').textContent=`${selectedProject+1} / ${PROJECTS.length}`;$('.dialog-visual').style.background=p.background;$('#detail-canvas').hidden=!!p.image;$('#detail-image').hidden=!p.image;$('.detail-rotate').hidden=!!p.image;$('.dialog-art-note').textContent=p.image?'PROJECT PHOTOGRAPH':'DIGITAL CONCEPT / DRAG TO ROTATE';if(p.image){$('#detail-image').src=p.image;$('#detail-image').alt=p.name}else{if(!detailRenderer)detailRenderer=new Sculpture($('#detail-canvas'),p.kind,p.color,true);else detailRenderer.update(p.kind,p.color);}dialog.scrollTop=0;}
function openProject(index){previousFocus=document.activeElement;dialog.showModal();document.body.style.overflow='hidden';showProject(index);$('.dialog-close').focus();}
function closeProject(){dialog.close()}
$('.dialog-close').addEventListener('click',closeProject);dialog.addEventListener('close',()=>{document.body.style.overflow='';if(previousFocus&&previousFocus.isConnected)previousFocus.focus({preventScroll:true})});dialog.addEventListener('click',e=>{if(e.target===dialog){const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)closeProject()}});
$('#prev-project').addEventListener('click',()=>showProject(selectedProject-1));$('#next-project').addEventListener('click',()=>showProject(selectedProject+1));$('#hero-details').addEventListener('click',()=>openProject(0));$('#rotate-left').addEventListener('click',()=>{detailRenderer.angle-=.3;detailRenderer.queue()});$('#rotate-right').addEventListener('click',()=>{detailRenderer.angle+=.3;detailRenderer.queue()});$('#rotate-reset').addEventListener('click',()=>{detailRenderer.angle=.25;detailRenderer.queue()});
$('.swatches').addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;$('.swatches').querySelectorAll('button').forEach(s=>{s.classList.toggle('active',s===b);s.setAttribute('aria-pressed',String(s===b))});heroRenderer.color=b.dataset.color;heroRenderer.queue();$('#material-name').textContent={cobalt:'Cobalt',clay:'Terracotta',chalk:'Warm chalk'}[b.dataset.color];$('#hero-canvas').setAttribute('aria-label',`Interactive ${$('#material-name').textContent.toLowerCase()} sculptural vase concept. Drag or use left and right arrow keys to rotate. Home resets the view.`)});
const revealObserver='IntersectionObserver'in window?new IntersectionObserver(entries=>{entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');revealObserver.unobserve(e.target)}})},{threshold:.08}):null;
if(revealObserver){document.body.classList.add('motion-ready');document.querySelectorAll('.reveal').forEach(el=>revealObserver.observe(el))}
heroRenderer=new Sculpture($('#hero-canvas'),'vase','cobalt',true);new Sculpture($('#about-canvas'),'orbit','clay');buildGallery();
let scrolling=false,lastHero=0;
function onScroll(){if(scrolling)return;scrolling=true;requestAnimationFrame(()=>{const max=document.documentElement.scrollHeight-innerHeight;$('.reading-progress').style.transform=`scaleX(${max>0?scrollY/max:0})`;if(!motionOff&&heroRenderer.visible&&performance.now()-lastHero>55){heroRenderer.scrollOffset=Math.min(scrollY/1300,.65);heroRenderer.queue();lastHero=performance.now()}scrolling=false})}
addEventListener('scroll',onScroll,{passive:true});addEventListener('resize',onScroll,{passive:true});onScroll();$('#year').textContent=new Date().getFullYear();
