const { chromium } = require('playwright');
const http = require('node:http');
const fs = require('node:fs');
const assert = require('node:assert/strict');
const path = require('node:path');
const results = [];
const root = __dirname;
fs.mkdirSync(path.join(root, 'test-results'), { recursive: true });
const record = (name, detail) => { results.push({ name, detail, passed: true }); console.log('PASS:', name, detail || ''); };
const server = http.createServer((req, res) => { res.setHeader('Content-Type', 'text/html'); res.end(fs.readFileSync(path.join(root, 'index.html'))); });
(async () => {
 await new Promise(r => server.listen(8173, '127.0.0.1', r));
 const browser = await chromium.launch({ headless: true, args: ['--enable-webgl','--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader','--disable-dev-shm-usage'] });
 let context;
 try {
  context = await browser.newContext({ viewport: { width: 1440, height: 900 } });
  const page = await context.newPage();
  const errors = [];
  page.on('pageerror', e => errors.push(e.message));
  await page.goto('http://127.0.0.1:8173/?test=1', { waitUntil: 'networkidle' });
  await page.waitForFunction(() => window.__game && !document.getElementById('play').disabled, { timeout: 60000 });
  assert.equal(await page.locator('#fatal').isVisible(), false);
  await page.screenshot({ path: path.join(root,'test-results/01-title-desktop.png') });
  record('Desktop startup', '1440 × 900, WebGL initialized, title interface ready');
  await page.click('#helpButton');
  assert.equal(await page.locator('#help').isVisible(),true);
  await page.keyboard.press('Escape');
  assert.equal(await page.locator('#help').isVisible(),false);
  record('Field guide', 'Open and Escape close work');
  await page.click('#settingsButton');
  await page.locator('#bob').uncheck();
  await page.click('[data-close="settings"]');
  assert.equal(await page.evaluate(() => JSON.parse(localStorage.getItem('dead-frequency-settings-v1')).bob), false);
  record('Settings persistence', 'Camera bob preference saved locally');
  await page.click('#play');
  await page.waitForFunction(() => window.__game.state === 'playing');
  await page.waitForTimeout(300);
  assert.equal(await page.locator('#hud').isVisible(),true);
  record('New run', 'Live first-person HUD and game simulation');
  const initial = await page.evaluate(() => ({ x: __game.player.x, z: __game.player.z }));
  await page.keyboard.down('KeyW'); await page.waitForTimeout(650); await page.keyboard.up('KeyW');
  const moved = await page.evaluate(() => ({ x: __game.player.x, z: __game.player.z }));
  assert.ok(Math.hypot(moved.x-initial.x,moved.z-initial.z) > .3);
  record('Keyboard movement', 'W moves the player through the world');
  await page.keyboard.press('KeyM');
  const frozen = await page.evaluate(() => ({ time:__game.player.time, open:__game.mapOpen }));
  assert.equal(frozen.open,true);
  await page.waitForTimeout(200);
  assert.equal(await page.evaluate(() => __game.player.time),frozen.time);
  await page.screenshot({ path:path.join(root,'test-results/02-tactical-map.png') });
  await page.keyboard.press('KeyM');
  record('Tactical map', 'Map renders and pauses simulation');
  const combat = await page.evaluate(() => {
   const g=__game; g.player.x=0;g.player.z=-25;g.player.yaw=0;g.player.pitch=0;g.update(.01);
   for(const e of g.enemies){e.x=145;e.z=145;e.g.position.set(e.x,0,e.z)}
   const e=g.enemies[0];e.x=0;e.z=-32;e.hp=60;e.g.position.set(0,0,-32);
   const before=g.weapons[0].mag,kills=g.player.kills;g.fire();
   return {before,after:g.weapons[0].mag,kills:g.player.kills-kills,hp:e.hp};
  });
  assert.equal(combat.after,combat.before-1); assert.ok(combat.hp<60); assert.equal(combat.kills,1);
  record('Carbine and headshot', 'Consumes one round, damages target and records elimination');
  await page.evaluate(() => { const g=__game;g.weapons[0].mag=2;g.weapons[0].reserve=10;g.reload(); for(let i=0;i<40;i++)g.update(.05); });
  assert.deepEqual(await page.evaluate(() => [__game.weapons[0].mag,__game.weapons[0].reserve]),[12,0]);
  record('Reload accounting', 'Transfers available rounds without creating ammunition');
  await page.keyboard.press('Digit2');
  assert.equal(await page.evaluate(() => __game.player.weapon),1);
  record('Weapon switching', 'Shotgun selectable with 2');
  const medical=await page.evaluate(() => {const g=__game;g.player.hp=30;g.player.meds=2;g.heal();return [g.player.hp,g.player.meds]});
  assert.deepEqual(medical,[85,1]);
  record('Medkits', 'Restores 55 health and consumes one kit');
  const pickup=await page.evaluate(()=>{const g=__game,l=g.loot[0];g.player.x=l.x;g.player.z=l.z;g.findNearest();const before=g.weapons[0].reserve;g.interact();return {taken:l.taken,ammo:g.weapons[0].reserve-before}});
  assert.equal(pickup.taken,true);assert.equal(pickup.ammo,36);
  record('Scavenging', 'Supply cache is consumed and grants ammunition');
  const collision=await page.evaluate(()=>{const g=__game,b=g.colliders[0];return g.blocked((b.min.x+b.max.x)/2,(b.min.z+b.max.z)/2)});
  assert.equal(collision,true);
  record('World collision', 'Building interiors block traversal');
  await page.evaluate(()=>{const g=__game;g.player.x=-96;g.player.z=-94;g.findNearest();g.interact();g.player.x=-85;g.update(.05)});
  assert.equal(await page.evaluate(()=>__game.action),null);
  record('Objective interruption', 'Leaving relay radius cancels connection');
  await page.evaluate(()=>{const g=__game;for(const e of g.enemies){e.x=170;e.z=170;e.hp=0;e.dead=.01}for(const r of g.relays){g.player.x=r.x;g.player.z=r.z+2;g.findNearest();g.interact();for(let i=0;i<102;i++){g.player.hp=100;g.update(.05)}}});
  assert.equal(await page.evaluate(()=>__game.relays.filter(r=>r.done).length),3);
  record('Relay objectives', 'All three 5-second connections complete and unlock extraction');
  await page.evaluate(()=>{__game.player.x=0;__game.player.z=8;__game.save()});
  const saved=await page.evaluate(()=>JSON.parse(localStorage.getItem('dead-frequency-save-v1')));
  assert.deepEqual(saved.relays,[true,true,true]);assert.equal(saved.loot[0],true);
  record('Progress save', 'Player, objectives, inventory and looted caches persisted');
  await page.screenshot({ path:path.join(root,'test-results/03-gameplay-desktop.png') });
  await page.evaluate(()=>__game.pause());
  assert.equal(await page.evaluate(()=>__game.state),'paused');
  await page.reload({waitUntil:'networkidle'});
  await page.waitForFunction(()=>window.__game);
  assert.equal(await page.locator('#continue').isVisible(),true);
  await page.click('#continue');
  await page.waitForFunction(()=>__game.state==='playing');
  assert.deepEqual(await page.evaluate(()=>__game.relays.map(r=>r.done)),[true,true,true]);
  record('Continue after reload', 'Restores saved objectives and player state');
  await page.evaluate(()=>{const g=__game;for(const e of g.enemies){e.hp=0;e.dead=.01}g.player.x=0;g.player.z=-143;g.findNearest();g.interact();for(let i=0;i<162&&g.state==='playing';i++){g.player.hp=100;g.update(.05)}});
  assert.equal(await page.evaluate(()=>__game.state),'won');
  assert.equal(await page.evaluate(()=>localStorage.getItem('dead-frequency-save-v1')),null);
  record('Extraction victory', '8-second hold ends run and clears active save');
  await page.screenshot({path:path.join(root,'test-results/04-victory.png')});
  await page.click('#play');await page.waitForFunction(()=>__game.state==='playing');
  await page.evaluate(()=>{const g=__game;g.player.x=0;g.player.z=-25;g.player.hp=1;const e=g.enemies[0];e.x=0;e.z=-25.5;e.hp=100;e.attack=0;g.update(.05)});
  assert.equal(await page.evaluate(()=>__game.state),'dead');
  record('Damage and defeat', 'Enemy attack can end the run; restart available');
  assert.deepEqual(errors,[]);
  record('Desktop JavaScript errors','None');
  const mobile=await browser.newContext({viewport:{width:844,height:390},hasTouch:true,isMobile:true,deviceScaleFactor:1});
  const mp=await mobile.newPage();const mobileErrors=[];mp.on('pageerror',e=>mobileErrors.push(e.message));
  await mp.goto('http://127.0.0.1:8173/?test=1',{waitUntil:'networkidle'});await mp.waitForFunction(()=>window.__game);
  await mp.tap('#play');await mp.waitForFunction(()=>__game.state==='playing');
  assert.equal(await mp.locator('#touch').isVisible(),true);
  await mp.screenshot({path:path.join(root,'test-results/05-touch-landscape.png')});
  const touchMag=await mp.evaluate(()=>__game.weapons[0].mag);await mp.tap('#touchFire');
  assert.ok(await mp.evaluate(()=>__game.weapons[0].mag)<touchMag);
  await mp.tap('#touchSwap');assert.equal(await mp.evaluate(()=>__game.player.weapon),1);
  record('Touch layout and actions','844 × 390; fire and weapon swap work');
  await mp.setViewportSize({width:390,height:844});await mp.waitForTimeout(200);
  assert.equal(await mp.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
  await mp.screenshot({path:path.join(root,'test-results/06-touch-portrait.png')});
  assert.deepEqual(mobileErrors,[]);
  record('Portrait responsiveness','390 × 844; no horizontal page overflow or JavaScript errors');
  await mobile.close();
  const liveURL='https://sweemingxx.github.io/dead-frequency/';
  let live=false;
  for(let attempt=0;attempt<24;attempt++){
   try{const response=await fetch(liveURL,{signal:AbortSignal.timeout(15000)});const text=await response.text();if(response.ok&&text.includes('DEAD FREQUENCY')&&text.includes('id="world"')){live=true;break}}catch{}
   await new Promise(r=>setTimeout(r,15000));
  }
  assert.ok(live,'GitHub Pages URL should return the published game');
  const livePage=await context.newPage();const liveErrors=[];livePage.on('pageerror',e=>liveErrors.push(e.message));
  await livePage.goto(liveURL,{waitUntil:'networkidle'});await livePage.waitForFunction(()=>!document.getElementById('play').disabled,{timeout:60000});
  assert.equal(await livePage.locator('#fatal').isVisible(),false);
  await livePage.screenshot({path:path.join(root,'test-results/07-live-github-pages.png')});
  await livePage.click('#play');await livePage.waitForTimeout(500);assert.equal(await livePage.locator('#hud').isVisible(),true);assert.deepEqual(liveErrors,[]);
  record('Live GitHub Pages deployment',liveURL+' — HTTP 200, WebGL initialized, playable HUD, no JavaScript errors');
 }catch(error){results.push({name:'FAILED',passed:false,detail:error.stack});console.error(error);process.exitCode=1;
  try{for(const p of context?.pages()||[])await p.screenshot({path:path.join(root,'test-results/failure-'+Date.now()+'.png')})}catch{}
 }finally{fs.writeFileSync(path.join(root,'test-results/results.json'),JSON.stringify(results,null,2));await browser.close();server.close();}
})().catch(error=>{console.error(error);process.exit(1)});
