(()=>{'use strict';const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];const {Game,hash,random,W,H,STEP,LOOP}=Afterlight;const canvas=$('#canvas'),ctx=canvas.getContext('2d');let game=null,state='home',mode='arcade',last=0,acc=0,visual=0,pointer=null,keys=new Set(),particles=[],floats=[],trail=[],toastUntil=0,audio=null,sound=false,reduced=matchMedia('(prefers-reduced-motion: reduce)').matches,pausedForHelp=false,storageOK=true;const day=new Date().toISOString().slice(0,10);let saved={};try{saved=JSON.parse(localStorage.getItem('afterlight-v1')||'{}')||{};if(typeof saved!=='object')saved={}}catch{storageOK=false}const params=new URLSearchParams(location.search),raw=params.get('seed'),shared=raw!==null&&/^[0-9a-z]{1,7}$/i.test(raw)?parseInt(raw,36)>>>0:null;const colors={cyan:'#8af9df',coral:'#ff7f91',lilac:'#c3a7ff'};const stars=Array.from({length:65},(_,i)=>{const r=random(i*571+6);return{x:r()*W,y:r()*H,a:r()}});
function save(){try{localStorage.setItem('afterlight-v1',JSON.stringify(saved))}catch{storageOK=false;$('#connection').textContent='SCORES AVAILABLE THIS SESSION ONLY'}}
function bestKey(){return mode==='daily'?'daily-'+day:'best'}function updateBest(){$('#best').textContent=mode==='zen'?'UNRANKED':String(Number(saved[bestKey()])||0).padStart(5,'0')}
function selectMode(m){mode=m;$$('[data-mode]').forEach(b=>{const on=b.dataset.mode===m;b.classList.toggle('selected',on);b.setAttribute('aria-pressed',on)});$('#mode-description').textContent=m==='daily'?day+' UTC · One shared constellation.':m==='zen'?'No damage. No pressure. Just light.':shared!==null?'Challenge loaded. Same seed. Your timeline.':'A fresh constellation. A new chance.';$('#mode-label').textContent=m==='daily'?'DAILY / '+day.slice(5):m==='zen'?'ZEN / UNRANKED':shared!==null?'FRIEND CHALLENGE':'FREE RUN';updateBest()}
function initAudio(){if(!sound)return;try{audio=audio||new(window.AudioContext||window.webkitAudioContext)();if(audio.state==='suspended')audio.resume().catch(()=>{})}catch{sound=false}}
function tone(freq,dur=.16,type='sine',volume=.045){if(!sound||!audio)return;try{const o=audio.createOscillator(),g=audio.createGain();o.type=type;o.frequency.setValueAtTime(freq,audio.currentTime);o.frequency.exponentialRampToValueAtTime(freq*.7,audio.currentTime+dur);g.gain.setValueAtTime(volume,audio.currentTime);g.gain.exponentialRampToValueAtTime(.001,audio.currentTime+dur);o.connect(g);g.connect(audio.destination);o.start();o.stop(audio.currentTime+dur)}catch{}}
function announce(text,seconds=2){$('#toast').textContent=text;toastUntil=visual+seconds}function burst(x,y,color,n=20){if(reduced)n=5;for(let i=0;i<n;i++){const a=Math.random()*Math.PI*2,s=25+Math.random()*85;particles.push({x,y,vx:Math.cos(a)*s,vy:Math.sin(a)*s,life:.5+Math.random()*.5,color})}}function resetInput(){pointer=null;keys.clear()}
function start(){const seed=mode==='daily'?hash('AFTERLIGHT-'+day):shared!==null&&mode==='arcade'?shared:crypto.getRandomValues(new Uint32Array(1))[0];game=new Game(seed,mode);state='playing';acc=0;particles=[];floats=[];trail=[];resetInput();$('#welcome').classList.add('hidden');$('#result').classList.add('hidden');$('#pause').disabled=false;$('.console').classList.add('playing');$('#touch-guide').style.opacity='1';initAudio();tone(440);announce('COLLECT LIGHT. KEEP MOVING.',3);canvas.focus({preventScroll:true});hud()}
function hud(){if(!game)return;$('#score').textContent=String(game.score).padStart(5,'0');$('#clock').textContent=Math.max(0,60-game.time).toFixed(1);$('#hearts').textContent=mode==='zen'?'∞':Array.from({length:3},(_,i)=>i<game.shield?'◆':'◇').join(' ');$('#hearts').setAttribute('aria-label',mode==='zen'?'Zen mode: no damage':game.shield+' shields remaining');$('#echo-count').textContent=game.echoes.length+' ACTIVE';$('#echo-progress').style.width=(game.tick%LOOP)/LOOP*100+'%';$('#stage').textContent=game.time<8?'FIRST ECHO IN '+Math.ceil(8-game.time)+'s':'TIMELINE '+String(Math.floor(game.time/8)+1).padStart(2,'0');$('#pulse').disabled=game.charge<4||state!=='playing';$('#pulse').classList.toggle('ready',game.charge===4);$('#pulse-label').textContent=game.protection?'PROTECTED · '+(game.protection/60).toFixed(1)+'s':game.charge===4?'PULSE READY — REWRITE THE MOMENT':(4-game.charge)+' SHARDS TO CHARGE';$('#combo').textContent=game.combo>1?game.combo+'× CHAIN · KEEP IT ALIVE':game.charge===4?'Tap pulse for 2s of safety.':'Leave yourself room to escape.'}
function end(abandoned=false){state='result';resetInput();$('.console').classList.remove('playing');$('#pause').disabled=true;$('#pulse').disabled=true;const won=game.time>=60;$('#result-label').textContent=abandoned?'TRANSMISSION ENDED':won?'TIMELINE ESCAPED':'SIGNAL LOST';$('#result-title').innerHTML=won?'You outran<br><em>yourself.</em>':'Beautiful<br><em>while it lasted.</em>';$('#final-score').textContent=game.score.toLocaleString();$('#final-time').textContent=game.time.toFixed(1)+'s';$('#final-shards').textContent=game.collected;$('#final-echoes').textContent=game.echoes.length;const old=Number(saved[bestKey()])||0;const record=mode!=='zen'&&!abandoned&&game.score>old;if(record){saved[bestKey()]=game.score;save()}$('#record').textContent=mode==='zen'?'A quiet moment, beautifully spent.':abandoned?'Practice run · personal best unchanged':record?'✧ NEW PERSONAL BEST'+(storageOK?'':' · THIS SESSION'):'PERSONAL BEST '+Math.max(old,game.score).toLocaleString();$('#result').classList.remove('hidden');$('#retry').focus({preventScroll:true});tone(won?660:130,.5);updateBest()}
function pause(){if(state!=='playing')return;state='paused';resetInput();$('#pause-dialog').showModal();hud()}function resume(){if(state!=='paused')return;$('#pause-dialog').close();state='playing';acc=0;resetInput();canvas.focus({preventScroll:true});hud()}
function pulse(){if(state==='playing'&&game.pulse()){burst(game.player.x,game.player.y,colors.lilac,45);tone(220,.4);announce('TIMELINE REWRITTEN',1.5);hud()}}
function update(){if(state!=='playing')return;let x=(keys.has('arrowright')||keys.has('d')?1:0)-(keys.has('arrowleft')||keys.has('a')?1:0),y=(keys.has('arrowdown')||keys.has('s')?1:0)-(keys.has('arrowup')||keys.has('w')?1:0);if(pointer){x=(pointer.x-pointer.ox)/32;y=(pointer.y-pointer.oy)/32}game.step({x,y});trail.push({...game.player});if(trail.length>25)trail.shift();for(const e of game.events){if(e.type==='collect'){burst(e.x,e.y,colors.cyan);floats.push({x:e.x,y:e.y,text:'+'+e.points,life:1});tone(330*Math.pow(1.122,game.combo*2),.16);if(game.charge===4)announce('PULSE READY ✳',1)}if(e.type==='echo'){announce('YOUR PAST IS NOW FOLLOWING YOU',2);tone(165,.35,'triangle')}if(e.type==='hit'){burst(e.x,e.y,colors.coral,28);announce(game.shield+' SHIELDS LEFT · CHANGE YOUR ROUTE',2);tone(85,.3,'triangle')}}if(game.tick%LOOP===420)announce('NEW ECHO IN 1 SECOND',1);if(game.tick>180)$('#touch-guide').style.opacity='0';if(game.ended)end();hud()}
function circle(x,y,r,color,fill=true){ctx.beginPath();ctx.arc(x,y,r,0,Math.PI*2);ctx[fill?'fillStyle':'strokeStyle']=color;ctx[fill?'fill':'stroke']()}
function line(points,color,width=1){if(points.length<2)return;ctx.beginPath();ctx.moveTo(points[0].x,points[0].y);for(const p of points)ctx.lineTo(p.x,p.y);ctx.strokeStyle=color;ctx.lineWidth=width;ctx.stroke()}
function diamond(x,y,r,color){ctx.beginPath();ctx.moveTo(x,y-r);ctx.lineTo(x+r,y);ctx.lineTo(x,y+r);ctx.lineTo(x-r,y);ctx.closePath();ctx.fillStyle=color;ctx.fill()}
function draw(dt){ctx.clearRect(0,0,W,H);ctx.fillStyle='#07101a';ctx.fillRect(0,0,W,H);const gradient=ctx.createRadialGradient(180,220,5,180,240,280);gradient.addColorStop(0,'#14343d55');gradient.addColorStop(1,'#07101a00');ctx.fillStyle=gradient;ctx.fillRect(0,0,W,H);ctx.lineWidth=.5;ctx.strokeStyle='#23404c44';for(let x=20;x<W;x+=32){ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,H);ctx.stroke()}for(let y=16;y<H;y+=32){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(W,y);ctx.stroke()}for(const s of stars){ctx.globalAlpha=.15+s.a*.35;circle(s.x,s.y,.7,'#c0ffe9')}ctx.globalAlpha=1;
if(!game||state==='home'){for(let j=0;j<3;j++){const path=[];for(let i=0;i<90;i++){const t=i/90*6.28;path.push({x:180+Math.sin(t+j*.45)*(110+j*17),y:205+Math.cos(t*2+j*.8)*110})}line(path,j===1?'#ff7f9133':'#8af9df26',1);const a=(reduced?1:visual*.4)+j*2;const x=180+Math.sin(a+j*.45)*(110+j*17),y=205+Math.cos(a*2+j*.8)*110;ctx.shadowBlur=reduced?0:20;ctx.shadowColor=j===1?colors.coral:colors.cyan;circle(x,y,4,ctx.shadowColor);ctx.shadowBlur=0}return}
for(const s of game.shards){const r=6+(reduced?0:Math.sin(visual*3+s.x)*1.2);ctx.shadowBlur=reduced?0:15;ctx.shadowColor=colors.cyan;diamond(s.x,s.y,r,colors.cyan);ctx.shadowBlur=0;circle(s.x,s.y,13,'#8af9df24',false)}
for(const path of game.echoes){const idx=game.tick%LOOP;const pts=[];for(let j=34;j>=0;j--){pts.push(path[(idx-j+path.length)%path.length])}line(pts,game.protection?'#c3a7ff44':'#ff7f9144',2)}
for(const g of game.ghosts){const safe=game.protection||game.tick%LOOP<=60;ctx.globalAlpha=safe?.3:1;ctx.shadowBlur=reduced?0:16;ctx.shadowColor=colors.coral;circle(g.x,g.y,9,colors.coral,false);circle(g.x,g.y,3,colors.coral);ctx.shadowBlur=0;ctx.beginPath();ctx.moveTo(g.x-4,g.y-4);ctx.lineTo(g.x+4,g.y+4);ctx.moveTo(g.x+4,g.y-4);ctx.lineTo(g.x-4,g.y+4);ctx.strokeStyle=colors.coral;ctx.stroke();ctx.globalAlpha=1}
line(trail,'#8af9df55',3);const p=game.player;const blink=game.invulnerable>0&&Math.floor(game.tick/6)%2===0;ctx.shadowBlur=reduced?0:20;ctx.shadowColor=colors.cyan;circle(p.x,p.y,7,blink?'#ffffff88':'#effff9');ctx.shadowBlur=0;circle(p.x,p.y,12,'#8af9df77',false);if(game.protection){ctx.lineWidth=2;circle(p.x,p.y,24+(reduced?0:Math.sin(visual*7)*3),colors.lilac,false);circle(p.x,p.y,33,'#c3a7ff33',false)}
if(state==='playing'){for(const p of particles){p.life-=dt;p.x+=p.vx*dt;p.y+=p.vy*dt;ctx.globalAlpha=Math.max(0,p.life);circle(p.x,p.y,1.6,p.color)}particles=particles.filter(p=>p.life>0);ctx.globalAlpha=1;ctx.font='11px monospace';ctx.textAlign='center';for(const f of floats){f.life-=dt;f.y-=dt*25;ctx.globalAlpha=Math.max(0,f.life);ctx.fillStyle=colors.cyan;ctx.fillText(f.text,f.x,f.y)}floats=floats.filter(f=>f.life>0);ctx.globalAlpha=1}
if(pointer){ctx.lineWidth=1;circle(pointer.ox,pointer.oy,29,'#dfffff33',false);const dx=pointer.x-pointer.ox,dy=pointer.y-pointer.oy,l=Math.max(1,Math.hypot(dx,dy)/29);circle(pointer.ox+dx/l,pointer.oy+dy/l,8,'#8af9df55')}
}
function frame(t){const dt=Math.min(.05,(t-last)/1000||0);last=t;visual+=dt;if(state==='playing'){acc+=dt;while(acc>=STEP){update();acc-=STEP}}draw(dt);if(toastUntil&&visual>toastUntil){$('#toast').textContent='';toastUntil=0}requestAnimationFrame(frame)}
function resize(){const dpr=Math.min(devicePixelRatio||1,2),r=canvas.getBoundingClientRect();canvas.width=Math.round(r.width*dpr);canvas.height=Math.round(r.height*dpr);ctx.setTransform(canvas.width/W,0,0,canvas.height/H,0,0)}new ResizeObserver(resize).observe(canvas);
function position(e){const r=canvas.getBoundingClientRect();return{x:(e.clientX-r.left)/r.width*W,y:(e.clientY-r.top)/r.height*H}}
canvas.addEventListener('pointerdown',e=>{if(state!=='playing'||pointer)return;const p=position(e);pointer={...p,ox:p.x,oy:p.y,id:e.pointerId};canvas.setPointerCapture(e.pointerId);$('#touch-guide').style.opacity='0';canvas.focus({preventScroll:true})});canvas.addEventListener('pointermove',e=>{if(pointer&&pointer.id===e.pointerId)Object.assign(pointer,position(e))});for(const name of ['pointerup','pointercancel','lostpointercapture'])canvas.addEventListener(name,e=>{if(pointer&&pointer.id===e.pointerId)pointer=null});
document.addEventListener('keydown',e=>{const k=e.key.toLowerCase();if($('dialog[open]'))return;if(state==='playing'&&['arrowup','arrowdown','arrowleft','arrowright','w','a','s','d',' '].includes(k)){if(e.target.tagName==='BUTTON'&&k===' ')return;e.preventDefault();keys.add(k);if(k===' '&&!e.repeat)pulse()}if(k==='escape'&&state==='playing'){e.preventDefault();pause()}});document.addEventListener('keyup',e=>keys.delete(e.key.toLowerCase()));window.addEventListener('blur',()=>{if(state==='playing')pause()});document.addEventListener('visibilitychange',()=>{if(document.hidden&&state==='playing')pause()});
$('#start').onclick=start;$('#retry').onclick=start;$('#pulse').onclick=pulse;$('#pause').onclick=pause;$('#resume').onclick=resume;$('#pause-dialog').addEventListener('cancel',e=>{e.preventDefault();resume()});$('#quit').onclick=()=>{$('#pause-dialog').close();end(true)};$('#home').onclick=()=>{state='home';game=null;$('#result').classList.add('hidden');$('#welcome').classList.remove('hidden');$('#score').textContent='00000';$('#clock').textContent='60.0';$('#stage').textContent='THE FUTURE IS UNWRITTEN';$('#echo-progress').style.width='0';$('#echo-count').textContent='0 ACTIVE';$('#hearts').textContent='◆ ◆ ◆';$('#combo').textContent='Make your first move.';$('#pulse-label').textContent='COLLECT 4 SHARDS TO CHARGE';$('#pulse').classList.remove('ready');$('#toast').textContent='';$('#start').focus({preventScroll:true});updateBest()};$$('[data-mode]').forEach(b=>b.onclick=()=>selectMode(b.dataset.mode));
$('#help').onclick=()=>{pausedForHelp=state==='playing';if(pausedForHelp){state='paused';resetInput();hud()}$('#help-dialog').showModal()};$('#help-dialog').addEventListener('close',()=>{if(pausedForHelp){state='playing';acc=0;canvas.focus({preventScroll:true});hud()}pausedForHelp=false});$$('[data-close]').forEach(b=>b.onclick=()=>$('#'+b.dataset.close).close());$('#sound').onclick=()=>{sound=!sound;initAudio();$('#sound').setAttribute('aria-pressed',sound);$('#sound').setAttribute('aria-label',sound?'Disable sound':'Enable sound');$('#sound-state').textContent=sound?'ON':'OFF';if(sound)tone(523)};
function setReduced(){$('body').classList.toggle('reduced',reduced);$('#motion').setAttribute('aria-pressed',reduced);$('#motion').textContent=reduced?'Effects reduced':'Reduce effects'}$('#motion').onclick=()=>{reduced=!reduced;setReduced()};
$('#share').onclick=()=>{const url=new URL('./',location.href);url.searchParams.set('seed',game.seed.toString(36));$('#share-text').value='AFTERLIGHT · '+game.score+' light · '+game.time.toFixed(1)+'s'+(mode==='zen'?' · Zen (unranked)':'')+'\nCan you outrun your own echoes? Try my constellation:\n'+url.href;$('#copy-status').textContent='';$('#share-dialog').showModal()};$('#copy').onclick=async()=>{try{await navigator.clipboard.writeText($('#share-text').value);$('#copy-status').textContent='Copied. Send a little light to someone.'}catch{$('#share-text').focus();$('#share-text').select();$('#copy-status').textContent='Select and copy the message above to share.'}};
if(!storageOK)$('#connection').textContent='SCORES AVAILABLE THIS SESSION ONLY';setReduced();selectMode('arcade');resize();requestAnimationFrame(frame);if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{$('#connection').textContent='ONLINE PLAY · OFFLINE CACHE UNAVAILABLE'});
})();
