'use strict';
(() => {
 const api=window.PrismStudio;if(!api)return;
 const $=(q,r=document)=>r.querySelector(q),$$=(q,r=document)=>[...r.querySelectorAll(q)];
 const esc=x=>String(x).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const copy=x=>JSON.parse(JSON.stringify(x));
 const notes=[0,2,4,7,9,12,14,16,19,21,24];
 let noteContext=null,noteEpoch=0,previewFrame=null;
 function normalise(values){const lo=Math.min(...values),hi=Math.max(...values);return values.map(v=>hi===lo?.5:(v-lo)/(hi-lo));}
 function stopNote(){noteEpoch++;if(noteContext){noteContext.close().catch(()=>{});noteContext=null;}}
 async function audition(values,index){stopNote();api.stopAudio();const Audio=window.AudioContext||window.webkitAudioContext;if(!Audio){api.toast('Note playback is unavailable in this browser. You can still export a WAV.');return;}const epoch=noteEpoch;try{const ctx=new Audio();noteContext=ctx;await ctx.resume();if(epoch!==noteEpoch){await ctx.close();return;}const frequency=130.8128*2**(notes[Math.round(normalise(values)[index]*10)]/12),osc=ctx.createOscillator(),gain=ctx.createGain(),now=ctx.currentTime;osc.type='sine';osc.frequency.value=frequency;gain.gain.setValueAtTime(0,now);gain.gain.linearRampToValueAtTime(.08,now+.035);gain.gain.exponentialRampToValueAtTime(.0001,now+.95);osc.connect(gain);gain.connect(ctx.destination);osc.start(now);osc.stop(now+1);osc.onended=()=>{osc.disconnect();gain.disconnect();if(noteContext===ctx){noteContext=null;ctx.close().catch(()=>{});}};}catch(e){stopNote();api.toast('Your browser could not play this note. Try a WAV export instead.');}}
 function waveBlob(values){
  const rate=22050,interval=.52,tail=1,duration=(values.length-1)*interval+tail,length=Math.ceil(duration*rate),samples=new Float32Array(length),norm=normalise(values);
  norm.forEach((n,i)=>{const f=130.8128*2**(notes[Math.round(n*10)]/12),start=Math.round(i*interval*rate),count=Math.ceil(tail*rate);for(let j=0;j<count&&start+j<length;j++){const t=j/rate,envelope=t<.035?t/.035:Math.exp(-10*(t-.035)/.915);samples[start+j]+=.18*envelope*Math.sin(2*Math.PI*f*t);}});
  const buffer=new ArrayBuffer(44+length*2),view=new DataView(buffer);const text=(o,s)=>{for(let i=0;i<s.length;i++)view.setUint8(o+i,s.charCodeAt(i));};text(0,'RIFF');view.setUint32(4,36+length*2,true);text(8,'WAVE');text(12,'fmt ');view.setUint32(16,16,true);view.setUint16(20,1,true);view.setUint16(22,1,true);view.setUint32(24,rate,true);view.setUint32(28,rate*2,true);view.setUint16(32,2,true);view.setUint16(34,16,true);text(36,'data');view.setUint32(40,length*2,true);for(let i=0;i<length;i++)view.setInt16(44+i*2,Math.round(Math.max(-1,Math.min(1,samples[i]))*32767),true);return new Blob([buffer],{type:'audio/wav'});
 }
 function openComposer(){
  const original=api.getState();let draft=copy(original),changed=false,previewValid=true;
  api.openDialog('Find the shape of your story.',`<p class="dialog-copy">Edit a value and watch the artwork respond. Nothing changes in your studio until you apply. Each row is one observation—not a prediction.</p><div class="composer-layout"><div class="composer-preview-column"><div class="composer-preview" id="composer-preview" role="img" aria-label="Draft artwork preview"></div><div id="composer-summary" class="composer-summary" role="status" aria-live="polite"></div><p class="composer-explainer">Higher values widen the form and raise the pitch. Values are normalized within this dataset; changing an extreme can reshape the whole piece.</p><div class="composer-legend"><span>01 / Make a change</span><span>02 / See the response</span><span>03 / Make it yours</span></div></div><div class="composer-fields"><label class="field-label" for="composer-name">Dataset name</label><input id="composer-name" type="text" maxlength="80" value="${esc(draft.data.name)}"><div class="composer-meta-grid"><div><label class="field-label" for="composer-title">Artwork title</label><input id="composer-title" type="text" maxlength="80" value="${esc(draft.title)}"></div><div><label class="field-label" for="composer-unit">Units (optional)</label><input id="composer-unit" type="text" maxlength="16" placeholder="e.g. mm" value="${esc(draft.data.unit)}"></div></div><label class="field-label" for="composer-source">Source or context</label><textarea id="composer-source" maxlength="400" rows="2">${esc(draft.data.provenance)}</textarea><div class="composer-table-wrap" role="region" tabindex="0" aria-label="Editable data observations, scrollable table"><table class="composer-table"><caption class="sr-only">Each label and value can be edited. Audition plays the mapped note. At least three rows are required.</caption><thead><tr><th scope="col">Observation</th><th scope="col">Value</th><th scope="col"><span class="sr-only">Row actions</span></th></tr></thead><tbody id="composer-rows"></tbody></table></div><div class="composer-row-tools"><button class="secondary" id="composer-add">＋ Add observation</button><span id="composer-count"></span></div><div id="composer-error" class="error" role="alert" hidden></div><div class="composer-footer"><button class="primary" id="composer-apply">Apply to my artwork <span aria-hidden="true">↗</span></button><button class="secondary" id="composer-cancel">Keep original</button></div><p class="field-hint">3–120 observations. Finite decimal values within ±1,000,000,000. Apply creates one undo step. Note buttons play sound only on request.</p></div></div>`,'THE DATA COMPOSER / LEARN BY MAKING');
  $('#dialog').classList.add('composer-dialog');
  function rowsHTML(){return draft.data.values.map((v,i)=>`<tr data-row="${i}"><td><label class="sr-only" for="row-label-${i}">Observation ${i+1} label</label><input type="text" id="row-label-${i}" data-label="${i}" maxlength="60" value="${esc(draft.data.labels[i])}"></td><td><label class="sr-only" for="row-value-${i}">Observation ${i+1} value</label><input type="number" id="row-value-${i}" data-value="${i}" min="-1000000000" max="1000000000" step="any" value="${v}"></td><td class="composer-row-actions"><button type="button" class="icon-button" data-audition="${i}" aria-label="Hear note for observation ${i+1}" title="Hear this observation"><svg aria-hidden="true"><use href="#i-sound"/></svg></button><button type="button" class="icon-button" data-remove="${i}" aria-label="Remove observation ${i+1}" title="Remove observation" ${draft.data.values.length<=3?'disabled':''}><svg aria-hidden="true"><use href="#i-close"/></svg></button></td></tr>`).join('');}
  function error(msg){$('#composer-error').textContent=msg;$('#composer-error').hidden=!msg;$('#composer-apply').disabled=!!msg;$('#composer-add').disabled=!!msg||draft.data.values.length>=120;$$('[data-audition]').forEach(b=>b.disabled=!!msg);$$('[data-remove]').forEach(b=>b.disabled=!!msg||draft.data.values.length<=3);previewValid=!msg;}
  function readDraft(){
   const labels=[],values=[];let message='';
   $$('[data-label]').forEach((el,i)=>{const v=$('[data-value="'+i+'"]').value,label=el.value.trim();el.removeAttribute('aria-invalid');const field=$('[data-value="'+i+'"]');field.removeAttribute('aria-invalid');if(!label){message=message||'Observation '+(i+1)+': add a label to keep this row recognizable.';el.setAttribute('aria-invalid','true');}const num=Number(v);if(v.trim()===''||!Number.isFinite(num)||Math.abs(num)>1e9||field.validity.badInput){message=message||'Observation '+(i+1)+': enter a finite number between −1,000,000,000 and 1,000,000,000.';field.setAttribute('aria-invalid','true');}labels.push(label);values.push(num);});
   if(!$('#composer-name').value.trim())message=message||'Give your dataset a name before applying.';
   if(!$('#composer-title').value.trim())message=message||'Give your artwork a title before applying.';
   error(message);if(message)return false;
   draft.title=$('#composer-title').value.trim();draft.data={...draft.data,name:$('#composer-name').value.trim(),unit:$('#composer-unit').value.trim(),labels,values};
   return true;
  }
  function updatePreview(){if(!readDraft()){$('#composer-summary').textContent='Preview paused. Correct the highlighted entry to continue.';return;}cancelAnimationFrame(previewFrame);previewFrame=requestAnimationFrame(()=>{if(!$('#composer-preview'))return;$('#composer-preview').innerHTML=api.renderSVG(draft,'composer');$('#composer-preview').setAttribute('aria-label',api.describe(draft));const v=draft.data.values;$('#composer-summary').textContent=v.length+' observations · range '+Math.min(...v)+' to '+Math.max(...v)+' '+draft.data.unit;});}
  function bindRows(){
   $('#composer-rows').innerHTML=rowsHTML();$('#composer-count').textContent=draft.data.values.length+' / 120';$('#composer-add').disabled=draft.data.values.length>=120;
   $$('[data-label],[data-value]').forEach(el=>el.oninput=()=>{changed=true;updatePreview();});
   $$('[data-audition]').forEach(b=>b.onclick=()=>{if(!readDraft())return;audition(draft.data.values,+b.dataset.audition);$('#composer-summary').textContent='Playing '+draft.data.labels[+b.dataset.audition]+': '+draft.data.values[+b.dataset.audition]+' '+draft.data.unit;});
   $$('[data-remove]').forEach(b=>b.onclick=()=>{if(!readDraft()||draft.data.values.length<=3)return;const i=+b.dataset.remove;draft.data.values.splice(i,1);draft.data.labels.splice(i,1);changed=true;bindRows();updatePreview();$('#row-label-'+Math.min(i,draft.data.values.length-1)).focus();});
  }
  bindRows();updatePreview();
  for(const id of ['composer-name','composer-title','composer-unit','composer-source'])$('#'+id).oninput=()=>{changed=true;updatePreview();};
  $('#composer-add').onclick=()=>{if(!readDraft()||draft.data.values.length>=120)return;draft.data.labels.push('Observation '+(draft.data.values.length+1));draft.data.values.push(draft.data.values[draft.data.values.length-1]);changed=true;bindRows();updatePreview();$('#row-label-'+(draft.data.values.length-1)).focus();};
  $('#composer-apply').onclick=()=>{if(!readDraft())return;stopNote();const dataChanged=JSON.stringify(draft.data.values)!==JSON.stringify(original.data.values)||JSON.stringify(draft.data.labels)!==JSON.stringify(original.data.labels)||draft.data.name!==original.data.name||draft.data.unit!==original.data.unit||$('#composer-source').value.trim()!==original.data.provenance;
   if(dataChanged){draft.source='custom';draft.data.hint='Your composed data · stored on this device';draft.data.caption='Your observations, your interpretation';const source=$('#composer-source').value.trim()||'Source not specified.';draft.data.provenance=('Edited in the Prism Atlas data composer. '+source).slice(0,400);}
   try{api.commit(draft,changed?'Your data story is now on the canvas. Undo is available.':'Your recipe is unchanged.');api.closeDialog();}catch(e){error(e.message);}
  };
  $('#composer-cancel').onclick=()=>{stopNote();api.closeDialog();api.toast('Original artwork kept. Draft changes discarded.');};
 }
 function blobDataURL(blob){return new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(r.result);r.onerror=()=>reject(Error('Could not package this file. Try downloading WAV separately.'));r.readAsDataURL(blob);});}
 function safeJSON(value){return JSON.stringify(value).replace(/</g,'\\u003c').replace(/>/g,'\\u003e').replace(/&/g,'\\u0026');}
 async function exhibitionHTML(recipe,credit,statement,withAudio,receipt){
  const description=api.describe(recipe),svg=api.renderSVG(recipe,'exhibit',receipt),wav=withAudio?await blobDataURL(waveBlob(recipe.data.values)):null;
  return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="color-scheme" content="dark"><meta name="description" content="A self-contained Prism Atlas exhibition. No account, remote scripts, or internet connection required."><title>${esc(recipe.title)} — Prism Atlas exhibition</title><style>
*{box-sizing:border-box}body{margin:0;background:#101b1a;color:#e8eee0;font:16px/1.7 system-ui,sans-serif}main{max-width:1120px;padding:42px 32px 70px;margin:auto}.eyebrow{color:#bdcea9;font-size:12px;letter-spacing:2px}header{display:flex;justify-content:space-between;gap:24px;align-items:center;border-bottom:1px solid #405047;padding-bottom:24px}h1{font:clamp(34px,6vw,64px)/1.1 Georgia,serif;margin:18px 0;overflow-wrap:anywhere}h2{font:27px Georgia,serif}h3{font-size:17px}.credit{color:#c4d0be}.art{margin:30px 0 24px;border:1px solid #3b5047;border-radius:14px;overflow:hidden}.art svg{width:100%;height:auto;display:block}section{max-width:850px;margin-top:32px}p{overflow-wrap:anywhere}.statement{font:24px/1.6 Georgia,serif;white-space:pre-wrap}.caption{color:#c4d0be;font-size:14px}.actions{display:flex;gap:12px;flex-wrap:wrap}button{border:1px solid #697e60;border-radius:7px;color:#e9efdf;background:#273d31;font:inherit;padding:11px 17px;min-height:44px;cursor:pointer}button:hover{background:#3d5342}button:focus-visible,a:focus-visible,summary:focus-visible,[tabindex]:focus-visible{outline:3px solid #e4c080;outline-offset:4px}audio{width:100%;margin-top:12px}details{border-top:1px solid #405047;margin-top:32px;padding-top:20px}summary{cursor:pointer;min-height:44px}table{width:100%;border-collapse:collapse;font-size:14px}th,td{text-align:left;padding:10px;border-bottom:1px solid #405047;overflow-wrap:anywhere}thead{color:#c4d0be}.table-wrap{max-height:330px;overflow:auto}code{overflow-wrap:anywhere;font-size:12px}footer{font-size:12px;color:#bac9ae;border-top:1px solid #405047;padding-top:24px;margin-top:44px}a{color:#d2dfb4}.no-print{}.status{color:#d2dfb4;font-size:13px}body.immersive main{padding:15px;max-width:100%}body.immersive header,body.immersive .story,body.immersive details,body.immersive footer,body.immersive .caption{display:none}body.immersive .art{margin:0 auto;max-height:calc(100dvh - 100px);aspect-ratio:4/3;width:min(100%,calc((100dvh - 100px)*4/3))}body.immersive .art svg{height:100%}body.immersive .actions{margin-top:12px;justify-content:center}@media(max-width:600px){main{padding:25px 18px 40px}header{display:block}h1{font-size:38px}.statement{font-size:21px}.actions button{flex:1}.art{margin-top:24px}}@media print{body{background:#fff;color:#17271d}main{padding:0}.art{break-inside:avoid}.no-print,details,footer{display:none}h1{font-size:34px}.eyebrow,.credit,.caption{color:#384d31}.story{display:block!important}}
</style></head><body><main><header><div><div class="eyebrow">PRISM ATLAS / A STORY IN MANY SENSES</div><h1>${esc(recipe.title)}</h1><div class="credit">${esc(credit||'Independent creator')} · ${recipe.data.values.length} observations · ${esc(recipe.form)}</div></div><span class="eyebrow">EXHIBITION EDITION</span></header><div class="art" role="img" aria-label="${esc(description)}">${svg}</div><p class="caption">${esc(recipe.data.name)} · ${esc(recipe.data.provenance)}</p><div class="actions no-print"><button id="immersive" aria-pressed="false">Enter immersive view</button><button id="print">Print exhibition</button><button id="recipe">Save creative recipe</button></div><p id="status" class="status no-print" role="status"></p><div class="story">${statement?'<section><h2>A note from the creator</h2><p class="statement">'+esc(statement)+'</p></section>':''}<section><h2>Another way to see</h2><p>${esc(description)}</p></section>${wav?'<section><h2>The same story, in sound</h2><p class="caption">Each observation becomes one of 11 pentatonic pitches. Higher values play higher notes, in source order. Nothing plays automatically.</p><audio controls preload="none" aria-label="Data soundtrack for '+esc(recipe.title)+'" src="'+wav+'"></audio><p class="caption">Embedded mono WAV · 22,050 Hz · 16-bit PCM · one pass through the dataset.</p></section>':''}</div><details><summary>Explore the data and creative recipe</summary><div class="table-wrap" tabindex="0" role="region" aria-label="Original source data"><table><thead><tr><th scope="col">Observation</th><th scope="col">Value ${esc(recipe.data.unit)}</th></tr></thead><tbody>${recipe.data.values.map((v,i)=>'<tr><td>'+esc(recipe.data.labels[i])+'</td><td>'+v+'</td></tr>').join('')}</tbody></table></div><p class="caption">Form: ${esc(recipe.form)} · Palette: ${esc(recipe.palette)} · Flow: ${recipe.flow}% · Detail: ${recipe.density}% · Seed: ${recipe.seed}</p><p class="caption">Recipe checksum (SHA-256): <code>${esc(receipt.recipeSHA256||'Unavailable in the originating browser')}</code></p><p class="caption">${esc(receipt.note)} Artwork is an expressive interpretation, not a precise measurement chart.</p></details><footer>This exhibition was created with <a href="https://sweemingxx.github.io/prism-atlas/" target="_blank" rel="noopener noreferrer">Prism Atlas</a>, an independent InnovArt 2027 project. The artwork, description, data${wav?', soundtrack':''}, and editable recipe are contained in this file. No network request is needed to view it; the studio link requires internet access.</footer></main><script id="creative-recipe" type="application/json">${safeJSON(receipt)}</script><script>
(()=>{const q=s=>document.querySelector(s);q('#immersive').onclick=()=>{const on=document.body.classList.toggle('immersive');q('#immersive').setAttribute('aria-pressed',String(on));q('#immersive').textContent=on?'Leave immersive view':'Enter immersive view';window.scrollTo(0,0);};document.addEventListener('keydown',e=>{if(e.key==='Escape'&&document.body.classList.contains('immersive'))q('#immersive').click();});q('#print').onclick=()=>window.print();q('#recipe').onclick=()=>{const data=JSON.parse(q('#creative-recipe').textContent),blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='prism-atlas-exhibition-recipe.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),10000);q('#status').textContent='Recipe ready. Import this JSON in the studio to remix the artwork.';};document.addEventListener('visibilitychange',()=>{if(document.hidden)document.querySelector('audio')?.pause();});})();
</script></body></html>`;
 }
 function openExhibition(){
  const current=api.getState();api.openDialog('Give your story a place to live.',`<p class="dialog-copy">Make a self-contained exhibition page for a classroom, community showcase, or hackathon demo. One HTML file holds your artwork, data, description, editable recipe, and optional soundtrack.</p><div class="exhibition-preview"><div class="exhibition-thumb" aria-hidden="true">${api.renderSVG({...current,density:35},'exhibition-thumb')}</div><div><p class="eyebrow">EXHIBITION EDITION</p><h3>${esc(current.title)}</h3><p>${current.data.values.length} observations · ${esc(current.form)} · ${esc(current.palette)}</p></div></div><label class="field-label" for="exhibition-credit">Creator credit (optional)</label><input type="text" id="exhibition-credit" maxlength="80" value="${esc(current.creator)}" placeholder="Your name or creative alias"><label class="field-label" for="exhibition-statement">What would you like your audience to notice? (optional)</label><textarea id="exhibition-statement" maxlength="1200" rows="4" placeholder="The quiet days matter as much as the peaks…"></textarea><label class="exhibition-checkbox"><input id="exhibition-audio" type="checkbox" checked><span>Include the soundtrack <small>Embedded WAV. Audio starts only when your audience presses play.</small></span></label><div class="callout"><strong>Check before you share.</strong> The file includes every data label and value, your credit, and this statement. It is not encrypted. Do not include confidential information. Only share datasets you have permission to distribute.</div><div class="dialog-actions"><button class="primary" id="exhibition-download">Download exhibition ↗</button><button class="secondary" id="soundtrack-download">Download WAV only</button></div><p class="field-hint" id="exhibition-status" role="status">Works offline after download. WAV: mono, 22,050 Hz, 16-bit PCM. No recording or microphone access.</p>`,'CREATE SOMETHING WORTH SHARING');
  $('#exhibition-download').onclick=async()=>{const b=$('#exhibition-download'),status=$('#exhibition-status'),audioButton=$('#soundtrack-download');b.disabled=true;audioButton.disabled=true;status.textContent='Packaging artwork, data, and soundtrack…';try{const recipe=copy(current);recipe.creator=$('#exhibition-credit').value.trim();const statement=$('#exhibition-statement').value.trim(),withAudio=$('#exhibition-audio').checked;await new Promise(r=>setTimeout(r,30));const receipt=await api.makeReceipt(recipe),html=await exhibitionHTML(recipe,recipe.creator,statement,withAudio,receipt);api.download(new Blob([html],{type:'text/html;charset=utf-8'}),api.fileName()+'-exhibition.html');if(status.isConnected)status.textContent='Exhibition downloaded. Open the HTML file in a browser—even offline. Your studio recipe is unchanged.';api.toast('Your self-contained exhibition is ready.');}catch(e){if(status.isConnected)status.textContent='Could not build the exhibition: '+e.message+' You can still export a PNG or SVG from the studio.';}finally{if(b.isConnected)b.disabled=false;if(audioButton.isConnected)audioButton.disabled=false;}};
  $('#soundtrack-download').onclick=()=>{try{const wav=waveBlob(current.data.values);api.download(wav,api.fileName()+'-soundtrack.wav');$('#exhibition-status').textContent='WAV downloaded. One pass through '+current.data.values.length+' observations; no microphone or recording used.';}catch(e){$('#exhibition-status').textContent='Soundtrack could not be created. Try a smaller dataset.';}};
 }
 const tools=document.createElement('section');tools.className='creative-next wrap';tools.setAttribute('aria-labelledby','creative-next-title');tools.innerHTML=`<div class="creative-next-heading"><p class="eyebrow">TAKE THE NEXT STEP</p><h2 id="creative-next-title">From a spark to <em>something you share.</em></h2><p>Shape the source. Make the work yours. Bring someone else into the story.</p></div><div class="creative-next-cards"><button class="next-card" id="composer-open"><span class="next-card-number">01 / COMPOSE</span><svg aria-hidden="true"><use href="#i-data"/></svg><strong>Be the source.</strong><span>Edit observations, see your artwork respond, and hear each value become a note.</span><span class="next-card-action">Open data composer <span aria-hidden="true">↗</span></span></button><button class="next-card" id="exhibition-open"><span class="next-card-number">02 / EXHIBIT</span><svg aria-hidden="true"><use href="#i-share"/></svg><strong>Let it meet the world.</strong><span>Download a complete offline exhibition with art, sound, your story, and its source.</span><span class="next-card-action">Build an exhibition <span aria-hidden="true">↗</span></span></button></div>`;
 $('.inspiration').before(tools);$('#composer-open').onclick=openComposer;$('#exhibition-open').onclick=openExhibition;
 const edit=document.createElement('button');edit.id='composer-inline';edit.className='import-link composer-inline';edit.textContent='Edit these observations ↗';$('#import-open').after(edit);edit.onclick=openComposer;
 new MutationObserver(()=>{if(!$('#dialog').open||!$('#composer-preview')){$('#dialog').classList.remove('composer-dialog');stopNote();cancelAnimationFrame(previewFrame);}}).observe($('#dialog'),{attributes:true,attributeFilter:['open']});
 document.addEventListener('visibilitychange',()=>{if(document.hidden)stopNote();});
 document.addEventListener('click',e=>{if(e.target.closest('#dialog-close,#composer-cancel'))stopNote();});
 document.addEventListener('keydown',e=>{if(e.key==='Escape')stopNote();});
})();
