'use strict';
(() => {
const $ = (q, root=document) => root.querySelector(q);
const $$ = (q, root=document) => [...root.querySelectorAll(q)];
const clone = x => JSON.parse(JSON.stringify(x));
const esc = x => String(x).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const STORE='prism-atlas:session:v1', GALLERY='prism-atlas:collection:v1';
const months=['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec'];
const palettes={estuary:{name:'Estuary',bg:'#101e21',glow:'#284b44',colors:['#427f7c','#7cbaaa','#d4e1af']},ember:{name:'Ember',bg:'#281a21',glow:'#663b30',colors:['#b9525f','#e7a071','#f6dfae']},iris:{name:'Iris',bg:'#1b1d35',glow:'#413764',colors:['#657ba7','#ada4dd','#e8c7dc']},solar:{name:'Solar',bg:'#23291c',glow:'#4c5730',colors:['#8b9e4f','#d9d685','#fcf0ca']}};
const datasets={
 ocean:{name:'Ocean rhythms',unit:'m',hint:'Illustrative monthly tide heights · not live data',caption:'An imagined ocean, made visible',provenance:'Illustrative monthly tide-height dataset, authored for Prism Atlas. Not measured or live data.',labels:months,values:[1.2,1.5,2.1,2.8,3.4,2.9,2.2,1.8,2.4,3.1,2.5,1.6]},
 warmth:{name:'A year of warmth',unit:'°C',hint:'Illustrative monthly temperatures · not live data',caption:'Twelve months, one warm impression',provenance:'Illustrative seasonal temperature dataset, authored for Prism Atlas. Not measured or live data.',labels:months,values:[3,5,9,14,19,23,26,25,20,14,8,4]},
 mood:{name:'Everyday feelings',unit:'/ 10',hint:'Illustrative daily reflections · not health advice',caption:'The small rhythms of being human',provenance:'Illustrative mood journal, authored for Prism Atlas. Not personal or clinical data.',labels:['Mon','Tue','Wed','Thu','Fri','Sat','Sun'],values:[4,6,5,8,6,9,7]}
};
const defaultState={version:1,title:'Tidal memory',creator:'',source:'ocean',data:clone(datasets.ocean),form:'ribbons',palette:'estuary',flow:58,density:68,seed:1459};
const presets=[
 {title:'Tidal memory',subtitle:'Ocean rhythms · Fluid, quietly alive',tag:'NATURE / REIMAGINED',source:'ocean',form:'ribbons',palette:'estuary',seed:1459,flow:58,density:68},
 {title:'A warmer tomorrow',subtitle:'A year of warmth · Let the light in',tag:'SEASONS / IN COLOUR',source:'warmth',form:'bloom',palette:'ember',seed:728,flow:76,density:77},
 {title:'The shape of a feeling',subtitle:'Everyday feelings · A softer perspective',tag:'REFLECTION / IN FORM',source:'mood',form:'contours',palette:'iris',seed:415,flow:64,density:73},
 {title:'An ordinary wonder',subtitle:'Ocean rhythms · Find another rhythm',tag:'CURIOSITY / UNFOLDED',source:'ocean',form:'bloom',palette:'solar',seed:9781,flow:43,density:84}
];
let storageOK=true, initMessages=[], gallery=[], state=clone(defaultState), history=[], historyAt=0;
let motion=!matchMedia('(prefers-reduced-motion: reduce)').matches;
let toastTimer, renderFrame, audio=null, tourStep=0, dialogReturnFocus=null;
const fmt=n=>new Intl.NumberFormat('en',{maximumFractionDigits:3}).format(n);
function validateProject(input){
 if(!input||input.version!==1)throw Error('This is not a supported Prism Atlas recipe (version 1).');
 const s=clone(input);const d=s.data;
 if(!d||!Array.isArray(d.values)||!Array.isArray(d.labels)||d.values.length<3||d.values.length>120||d.values.length!==d.labels.length)throw Error('A recipe needs 3–120 labelled data points.');
 if(d.values.some(v=>typeof v!=='number'||!Number.isFinite(v)||Math.abs(v)>1e9))throw Error('Values must be finite numbers between −1,000,000,000 and 1,000,000,000.');
 if(d.labels.some(v=>typeof v!=='string'||v.length>60||!v.trim()))throw Error('Each data label must contain 1–60 characters.');
 if(!['ribbons','bloom','contours'].includes(s.form)||!palettes[s.palette])throw Error('This recipe uses an unknown form or palette.');
 for(const k of ['flow','density'])if(!Number.isFinite(s[k])||s[k]<(k==='flow'?10:20)||s[k]>100)throw Error('The recipe has an invalid '+k+' setting.');
 if(!Number.isInteger(s.seed)||s.seed<0||s.seed>4294967295)throw Error('The recipe has an invalid variation seed.');
 return {version:1,title:String(s.title||'Untitled study').slice(0,80),creator:String(s.creator||'').slice(0,80),source:['ocean','warmth','mood','custom'].includes(s.source)?s.source:'custom',form:s.form,palette:s.palette,flow:s.flow,density:s.density,seed:s.seed,data:{name:String(d.name||'Your own data').slice(0,80),unit:String(d.unit||'').slice(0,16),hint:String(d.hint||'Imported data · stored on this device').slice(0,160),caption:String(d.caption||'Your story, in a new language').slice(0,160),provenance:String(d.provenance||'User-provided dataset; source not independently verified.').slice(0,400),labels:d.labels.map(x=>x.trim()),values:d.values}};
}
function loadStorage(){
 try{const saved=localStorage.getItem(STORE);if(saved)state=validateProject(JSON.parse(saved));}catch(e){if(e.name==='SecurityError')storageOK=false;else initMessages.push('Your previous session could not be restored. A fresh canvas is ready.');}
 try{const saved=JSON.parse(localStorage.getItem(GALLERY)||'[]');if(!Array.isArray(saved))throw Error();gallery=saved.slice(0,20).map(x=>({id:String(x.id),date:String(x.date),state:validateProject(x.state)}));}catch(e){gallery=[];initMessages.push('The local collection could not be read. You can still create and export.');}
 try{if(location.hash.startsWith('#recipe=')){const raw=location.hash.slice(8);if(raw.length>35000)throw Error();state=validateProject(JSON.parse(decodeRecipe(raw)));initMessages.push('Shared recipe opened. Make it your own.');}}catch(e){initMessages.push('This shared link could not be opened. Ask the creator to copy it again.');}
 history=[clone(state)];
}
function persist(){try{localStorage.setItem(STORE,JSON.stringify(state));storageOK=true;$('#save-status').textContent='Session saved on this device';}catch(e){storageOK=false;$('#save-status').textContent='Session only · export to keep';}}
function saveGallery(){try{localStorage.setItem(GALLERY,JSON.stringify(gallery));$('#collection-count').textContent=gallery.length;return true;}catch(e){toast('Browser storage is unavailable or full. Export a recipe to keep your work.');return false;}}
function toast(message,action){clearTimeout(toastTimer);const el=$('#toast');el.replaceChildren(document.createTextNode(message));if(action){const b=document.createElement('button');b.textContent=action.label;b.onclick=()=>{action.run();el.hidden=true;};el.append(b);}el.hidden=false;toastTimer=setTimeout(()=>el.hidden=true,action?9000:4500);}
function rng(seed){let a=seed>>>0;return()=>{a+=0x6D2B79F5;let t=a;t=Math.imul(t^t>>>15,t|1);t^=t+Math.imul(t^t>>>7,t|61);return((t^t>>>14)>>>0)/4294967296;};}
function normalise(values){const lo=Math.min(...values),hi=Math.max(...values);return values.map(x=>hi===lo?.5:(x-lo)/(hi-lo));}
function interpolate(values,t){const x=Math.max(0,Math.min(.999999,t))*(values.length-1),i=Math.floor(x),a=x-i;return values[i]*(1-a)+values[Math.min(i+1,values.length-1)]*a;}
function renderSVG(s,prefix='piece',receipt=null){
 const p=palettes[s.palette],random=rng(s.seed),norm=normalise(s.data.values),f=s.flow/100,n=Math.round(36+s.density*.95),phase=random()*Math.PI*2;
 let out=`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1200 900" preserveAspectRatio="xMidYMid meet"><title>${esc(s.title)}</title><desc>${esc(describe(s))}</desc>${receipt?'<metadata>'+esc(JSON.stringify(receipt))+'</metadata>':''}<defs><radialGradient id="${prefix}-bg"><stop stop-color="${p.glow}" stop-opacity=".52"/><stop offset="1" stop-color="${p.bg}"/></radialGradient><linearGradient id="${prefix}-line" x1="0" y1="1" x2="1" y2="0"><stop stop-color="${p.colors[0]}"/><stop offset=".45" stop-color="${p.colors[1]}"/><stop offset=".77" stop-color="${p.colors[2]}"/><stop offset="1" stop-color="${p.colors[0]}"/></linearGradient></defs><rect width="1200" height="900" fill="${p.bg}"/><rect width="1200" height="900" fill="url(#${prefix}-bg)"/>`;
 for(let i=0;i<185;i++){const x=random()*1200,y=random()*900;out+=`<circle cx="${x.toFixed(1)}" cy="${y.toFixed(1)}" r="${(random()*.8+.2).toFixed(1)}" fill="${p.colors[2]}" opacity="${(random()*.22+.04).toFixed(2)}"/>`;}
 out+=`<g fill="none" stroke="${p.colors[1]}" stroke-width=".6" opacity=".13"><path d="M75 450h1050M600 85v730" stroke-dasharray="2 12"/><circle cx="600" cy="450" r="325" stroke-dasharray="1 11"/></g>`;
 for(let j=0;j<n;j++){
  let path='';const u=j/(n-1),steps=s.form==='ribbons'?106:160;
  for(let k=0;k<=steps;k++){
   const t=k/steps;let x,y;
   if(s.form==='ribbons'){
    const value=interpolate(norm,t),a=u*Math.PI*2,twist=t*(2.3+f*3)+phase;
    const envelope=Math.sin(t*Math.PI)*(.8+value*.5),radius=(72+value*112)*(.5+f*.75);
    x=102+t*996+Math.sin(a+twist)*envelope*68;
    y=450+Math.sin(t*Math.PI*2+phase*.3)*(65+f*100)+Math.cos(a+twist)*radius+Math.sin(a)*envelope*66;
   }else if(s.form==='bloom'){
    const a=t*Math.PI*2,value=interpolate([...norm,norm[0]],t),r=(105+u*222)*(1+.14*Math.sin(a*5+phase+u*2)*f)+value*65*f;
    const swirl=u*(1.2+f*1.5)+.12*Math.sin(a*3);
    x=600+Math.cos(a+swirl)*r*1.12+Math.sin(u*6+phase)*24;
    y=450+Math.sin(a+swirl)*r*.87+Math.cos(a*3+u*8)*u*22*f;
   }else{
    const a=t*Math.PI*2,value=interpolate([...norm,norm[0]],t),r=(35+u*285)*(1+Math.sin(a*3+phase)*.16*f+Math.cos(a*5+u*2)*.1*f)+(value-.5)*85*u*f;
    x=600+Math.cos(a)*r*1.35+Math.sin(u*4+phase)*30;
    y=450+Math.sin(a)*r*.96+Math.cos(u*5)*25;
   }
   path+=(k?'L':'M')+x.toFixed(1)+','+y.toFixed(1);
  }
  if(s.form!=='ribbons')path+='Z';
  const alpha=s.form==='ribbons'?(.23+.48*Math.pow(Math.sin(u*Math.PI),2)):(.23+.42*u);
  out+=`<path d="${path}" fill="none" stroke="url(#${prefix}-line)" stroke-width="${j%7===0?1.6:.85}" opacity="${alpha.toFixed(2)}"/>`;
 }
 out+='<g fill="'+p.colors[2]+'" opacity=".55">';for(let i=0;i<norm.length;i++){const x=510+(i/(norm.length-1))*180;out+=`<rect x="${x.toFixed(1)}" y="${(805-norm[i]*16).toFixed(1)}" width="1.1" height="${(3+norm[i]*16).toFixed(1)}"/>`;}out+='</g></svg>';return out;
}
function describe(s){const v=s.data.values,lo=Math.min(...v),hi=Math.max(...v),li=v.indexOf(lo),hii=v.indexOf(hi),trend=v[v.length-1]-v[0];const shape={ribbons:'A woven ribbon twists across a dark field. Higher values widen its folds; lower values draw them inward.',bloom:'Fine lines curl into a flower-like orbit. Higher values extend the petals; lower values gather toward the center.',contours:'Nested contours form an imaginary island. Higher values push its boundaries outward; lower values pull them inward.'}[s.form];return `${s.title}. ${shape} The ${palettes[s.palette].name} palette moves from ${s.palette==='estuary'?'deep turquoise through mint to warm ivory':s.palette==='ember'?'coral through amber to warm blush':s.palette==='iris'?'blue through lavender to pale rose':'olive through saffron to cream'}. This piece contains ${v.length} points from ${s.data.name}. The lowest value is ${lo} ${s.data.unit} at ${s.data.labels[li]}; the highest is ${hi} ${s.data.unit} at ${s.data.labels[hii]}. The final value is ${trend===0?'equal to':trend>0?'higher than':'lower than'} the first. In the musical interpretation, higher values become higher notes on a pentatonic scale. ${s.data.provenance}`;}
function renderArt(s=state){$('#artwork').innerHTML=renderSVG(s);$('#artwork').setAttribute('aria-label',describe(s));$('#art-stage').style.background=palettes[s.palette].bg;}
function render(){cancelAnimationFrame(renderFrame);renderArt();$('#art-title').textContent=state.title;$('#point-count').textContent=state.data.values.length+' data points';$('#source-caption').textContent=state.data.caption;$('#source-hint').textContent=state.data.hint;$('#source option[value=custom]').disabled=state.source!=='custom';$('#source').value=state.source;$('#palette-name').textContent=palettes[state.palette].name;$('#art-palette').textContent=palettes[state.palette].name.toUpperCase()+' / STUDY NO. '+String(state.seed%1000).padStart(3,'0');$('#art-type').textContent='GENERATIVE STUDY / '+({ribbons:'001',bloom:'002',contours:'003'}[state.form]);for(const k of ['flow','density']){$('#'+k).value=state[k];$('#'+k+'-value').textContent=state[k]+'%';}$$('[data-form]').forEach(b=>b.setAttribute('aria-pressed',b.dataset.form===state.form));$$('[data-palette]').forEach(b=>b.setAttribute('aria-pressed',b.dataset.palette===state.palette));$('#undo').disabled=historyAt===0;$('#redo').disabled=historyAt===history.length-1;$('#collection-count').textContent=gallery.length;renderMotion();}
function commit(next,message){stopAudio();state=validateProject(next);if(JSON.stringify(state)!==JSON.stringify(history[historyAt])){history=history.slice(0,historyAt+1);history.push(clone(state));if(history.length>40)history.shift();historyAt=history.length-1;}render();persist();if(message)toast(message);}
function change(patch,message){commit({...clone(state),...patch},message);}
function undo(delta){if(historyAt+delta<0||historyAt+delta>=history.length)return;stopAudio();historyAt+=delta;state=clone(history[historyAt]);render();persist();toast(delta<0?'Last change undone.':'Change restored.');}
function renderMotion(){const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;if(reduced)motion=false;$('#art-stage').classList.toggle('moving',motion);$('#motion').setAttribute('aria-pressed',String(motion));const label=motion?'Pause artwork motion':'Enable gentle artwork motion';$('#motion').setAttribute('aria-label',label);$('#motion').title=label;$('#motion use').setAttribute('href',motion?'#i-pause':'#i-play');}
function presetState(p){return {...clone(defaultState),...p,version:1,data:clone(datasets[p.source])};}
function showPresets(){$('#inspiration-grid').innerHTML=presets.map((p,i)=>`<button class="inspiration-card" data-preset="${i}" aria-label="Open ${esc(p.title)} creative recipe"><div class="preview-art">${renderSVG({...presetState(p),density:42},'preview'+i)}<span class="preview-label">${esc(p.tag)}</span></div><div class="inspiration-meta"><h3>${esc(p.title)}</h3><span aria-hidden="true">↗</span></div><p>${esc(p.subtitle)}</p></button>`).join('');$$('[data-preset]').forEach(b=>b.onclick=()=>{commit(presetState(presets[+b.dataset.preset]),'A new starting point. Make it yours.');$('#studio').scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth'});});}
function stopAudio(){if(audio){clearInterval(audio.timer);try{audio.context.close();}catch(e){}audio=null;}$('#listen').setAttribute('aria-pressed','false');$('#listen-label').textContent='Listen to this piece';$('#sound-display').hidden=true;$$('[data-listen]').forEach(b=>b.textContent='Listen to the data');}
async function toggleAudio(){if(audio){stopAudio();toast('Sound paused.');return;}const Audio=window.AudioContext||window.webkitAudioContext;if(!Audio){toast('Sound is unavailable in this browser. The written description has the same data story.');return;}try{const context=new Audio();await context.resume();const gain=context.createGain();gain.gain.value=.18;gain.connect(context.destination);const norm=normalise(state.data.values),scale=[0,2,4,7,9,12,14,16,19,21,24];let step=0;audio={context,gain,timer:null};const note=()=>{if(!audio)return;const i=step%norm.length,semi=scale[Math.round(norm[i]*(scale.length-1))],freq=130.8128*2**(semi/12),now=context.currentTime;const osc=context.createOscillator(),env=context.createGain();osc.type='sine';osc.frequency.value=freq;env.gain.setValueAtTime(0,now);env.gain.linearRampToValueAtTime(.34,now+.035);env.gain.exponentialRampToValueAtTime(.0001,now+.95);osc.connect(env);env.connect(gain);osc.start(now);osc.stop(now+1);osc.onended=()=>{osc.disconnect();env.disconnect();};$('#sound-note').textContent=state.data.labels[i]+' · '+state.data.values[i]+' '+state.data.unit;step++;};note();audio.timer=setInterval(note,520);$('#listen').setAttribute('aria-pressed','true');$('#listen-label').textContent='Pause the sound';$('#sound-display').hidden=false;$$('[data-listen]').forEach(b=>b.textContent='Pause the sound');toast('Sound on. Each note follows one data point.');}catch(e){stopAudio();toast('Sound could not start. Check your browser sound permissions and try again.');}}
function openDialog(title,html,eyebrow='ANOTHER WAY TO CREATE'){stopAudio();if(window.speechSynthesis)speechSynthesis.cancel();dialogReturnFocus=document.activeElement;$('#dialog-title').textContent=title;$('#dialog-eyebrow').textContent=eyebrow;$('#dialog-body').innerHTML=html;if(!$('#dialog').open)$('#dialog').showModal();$('#dialog').scrollTop=0;}
function closeDialog(){stopAudio();if(window.speechSynthesis)speechSynthesis.cancel();$('#dialog').close();if(dialogReturnFocus?.isConnected)dialogReturnFocus.focus();}
function showData(){const d=state.data,v=d.values,lo=Math.min(...v),hi=Math.max(...v),mean=v.reduce((a,b)=>a+b,0)/v.length,norm=normalise(v);openDialog('The story beneath the lines',`<p>${esc(d.provenance)}</p><div class="stats-grid"><div class="stat"><small>DATA POINTS</small><strong>${v.length}</strong></div><div class="stat"><small>RANGE ${esc(d.unit)}</small><strong>${fmt(lo)}–${fmt(hi)}</strong></div><div class="stat"><small>MEAN ${esc(d.unit)}</small><strong>${fmt(mean)}</strong></div></div><div class="data-chart" aria-hidden="true">${norm.map(n=>`<div class="data-bar" style="height:${12+n*88}%"></div>`).join('')}</div><p class="field-hint">Bar heights show min–max normalized values. Exact values are in the table.</p><div class="data-table-wrap"><table><caption class="sr-only">${esc(d.name)} — original values</caption><thead><tr><th scope="col">Observation</th><th scope="col">Value ${esc(d.unit)}</th></tr></thead><tbody>${v.map((x,i)=>`<tr><td>${esc(d.labels[i])}</td><td>${esc(x)}</td></tr>`).join('')}</tbody></table></div><h3>A translation, not a black box</h3><ul class="mapping-list"><li><strong>Value → shape</strong>We normalize values within this dataset from 0 to 1. Higher values widen ribbons or extend bloom and contour radii. Equal values map to 0.5. Shape is an expressive interpretation, not a precise chart.</li><li><strong>Value → sound</strong>Each point selects one of 11 C-major pentatonic pitches, from C3 to C5, played every 520 milliseconds in source order. Higher value = higher pitch.</li><li><strong>Your choices → character</strong>Flow changes curvature; detail changes line count. Palette changes atmosphere. A saved seed makes the same recipe reproducible.</li></ul><div class="dialog-actions"><button class="primary" data-listen>Listen to the data</button><button class="secondary" id="download-csv">Download source CSV</button></div>`,'OPEN THE CREATIVE RECIPE');$('[data-listen]').onclick=toggleAudio;$('#download-csv').onclick=downloadCSV;}
function showDescription(){openDialog('There is more than one way to see.',`<p>${esc(describe(state))}</p><div class="callout">This description is generated from the actual recipe and dataset—not from an AI guess about the image. Both the written and musical versions carry the data story.</div><div class="dialog-actions"><button class="primary" id="read-aloud">Read aloud</button><button class="secondary" data-listen>Listen to the data</button></div><p class="field-hint">Read-aloud uses your browser’s speech service. Voice availability and whether processing is local depend on your browser. No microphone is used.</p>`,'EXPERIENCE IT IN WORDS');$('#read-aloud').onclick=()=>{if(!('speechSynthesis'in window)){toast('Read-aloud is not available here. The description remains available to your screen reader.');return;}if(speechSynthesis.speaking){speechSynthesis.cancel();$('#read-aloud').textContent='Read aloud';return;}stopAudio();const u=new SpeechSynthesisUtterance(describe(state));u.lang='en';u.rate=.88;u.onend=()=>{if($('#read-aloud'))$('#read-aloud').textContent='Read aloud';};u.onerror=()=>{if($('#read-aloud'))$('#read-aloud').textContent='Read aloud';toast('Your browser could not read this aloud. You can still read or copy the description.');};speechSynthesis.speak(u);$('#read-aloud').textContent='Stop reading';};$('[data-listen]').onclick=()=>{if(window.speechSynthesis)speechSynthesis.cancel();if($('#read-aloud'))$('#read-aloud').textContent='Read aloud';toggleAudio();};}
function parseCSV(text){if(new TextEncoder().encode(text).length>65536)throw Error('Please use a CSV file smaller than 64 KB.');text=text.replace(/^\uFEFF/,'').trim();if(!text)throw Error('Add your CSV data first. Try the example below.');const rows=[];let row=[],cell='',quoted=false,ended=false;
 for(let i=0;i<text.length;i++){const c=text[i];if(quoted){if(c==='"'){if(text[i+1]==='"'){cell+='"';i++;}else{quoted=false;ended=true;}}else cell+=c;}else if(c==='"'){if(cell.trim()||ended)throw Error('A quote is misplaced. Put quotes around the entire label.');quoted=true;cell='';}else if(c===','){row.push(cell.trim());cell='';ended=false;}else if(c==='\n'||c==='\r'){if(c==='\r'&&text[i+1]==='\n')i++;row.push(cell.trim());if(row.some(Boolean))rows.push(row);row=[];cell='';ended=false;}else{if(ended&&c.trim())throw Error('Unexpected text after a quoted label.');cell+=c;}}
 if(quoted)throw Error('A quoted cell is not closed. Add its closing double quote.');row.push(cell.trim());if(row.some(Boolean))rows.push(row);
 if(rows.some(r=>r.length!==2))throw Error('Use exactly two columns: label,value. Put a label containing a comma in double quotes.');
 if(rows.length&&rows[0][1]!==''&&!Number.isFinite(Number(rows[0][1])))rows.shift();
 if(rows.length<3||rows.length>120)throw Error('Please include 3–120 data rows, plus an optional header.');
 const labels=[],values=[];rows.forEach((r,i)=>{if(!r[0]||r[0].length>60)throw Error('Data row '+(i+1)+': use a label with 1–60 characters.');if(!/^[+-]?(?:\d+\.?\d*|\.\d+)(?:e[+-]?\d+)?$/i.test(r[1])||!Number.isFinite(Number(r[1]))||Math.abs(Number(r[1]))>1e9)throw Error('Data row '+(i+1)+': enter a finite decimal number between −1,000,000,000 and 1,000,000,000, without units.');labels.push(r[0]);values.push(Number(r[1]));});return {labels,values};}
function showImport(){openDialog('Every dataset has a story.',`<p>Bring a small rhythm from your world: rainfall, footsteps, a garden diary, or a week of feelings. Your file stays in your browser.</p><label class="field-label" for="data-name">Give your dataset a name</label><input type="text" id="data-name" maxlength="80" value="My everyday rhythms"><label class="field-label" for="csv-file">Choose a CSV file (optional)</label><input type="file" id="csv-file" accept=".csv,text/csv"><label class="field-label" for="csv-text">Or paste two columns: label, value</label><textarea id="csv-text" spellcheck="false" placeholder="label,value&#10;Monday,4&#10;Tuesday,7&#10;Wednesday,5" aria-describedby="csv-help csv-error"></textarea><p class="field-hint" id="csv-help">3–120 rows · maximum 64 KB · optional header · decimal numbers only. Labels with commas must be quoted. Example data is illustrative, not measured.</p><div class="error" id="csv-error" role="alert" hidden></div><div class="dialog-actions"><button class="primary" id="import-create">Turn my data into art</button><button class="secondary" id="import-example">Try example data</button></div><h3>Returning to a previous creation?</h3><label class="field-label" for="recipe-file">Restore an exported Prism Atlas recipe (.json, up to 150 KB)</label><input type="file" id="recipe-file" accept=".json,application/json">`,'YOUR DATA. YOUR EXPRESSION.');
 const fail=message=>{$('#csv-error').textContent=message;$('#csv-error').hidden=false;$('#csv-text').setAttribute('aria-invalid','true');};
 $('#import-example').onclick=()=>{$('#csv-text').value='label,value\nMonday,4\nTuesday,7\nWednesday,5\nThursday,8\nFriday,6\nSaturday,9\nSunday,7';$('#csv-error').hidden=true;$('#csv-text').removeAttribute('aria-invalid');};
 $('#csv-file').onchange=async e=>{const file=e.target.files[0];if(!file)return;if(file.size>65536){fail('That file is too large. Choose a CSV smaller than 64 KB.');e.target.value='';return;}try{$('#csv-text').value=await file.text();$('#csv-error').hidden=true;$('#csv-text').removeAttribute('aria-invalid');toast('File loaded. Review your data, then create.');}catch(err){fail('The file could not be read. Try pasting the contents instead.');}};
 $('#import-create').onclick=()=>{try{const d=parseCSV($('#csv-text').value),name=$('#data-name').value.trim()||'My everyday rhythms';commit({...clone(state),source:'custom',title:name,data:{...d,name,unit:'',hint:'Your imported data · stored on this device',caption:'Your story, in a new language',provenance:'User-provided dataset: '+name+'. Values have not been independently verified.'}},'Your data has a new language.');closeDialog();}catch(e){fail(e.message);$('#csv-text').focus();}};
 $('#recipe-file').onchange=async e=>{const file=e.target.files[0];if(!file)return;try{if(file.size>153600)throw Error('Use a recipe smaller than 150 KB.');const recipe=JSON.parse(await file.text());commit(validateProject(recipe.recipe||recipe),'Your creative recipe has been restored.');closeDialog();}catch(err){fail(err instanceof SyntaxError?'This file is not valid JSON. Choose a Prism Atlas recipe export.':err.message);e.target.value='';}};
}
function fileName(){return (state.title.toLowerCase().normalize('NFKD').replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')||'prism-atlas')+'-prism-atlas';}
function download(blob,name){const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),10000);}
function downloadCSV(){const quote=s=>'"'+String(s).replace(/"/g,'""')+'"';const csv='label,value\r\n'+state.data.values.map((x,i)=>quote(state.data.labels[i])+','+x).join('\r\n');download(new Blob([csv],{type:'text/csv;charset=utf-8'}),fileName()+'-data.csv');toast('Source CSV downloaded.');}
async function receipt(){const canonical=JSON.stringify(state),hash=crypto.subtle?Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(canonical)))).map(x=>x.toString(16).padStart(2,'0')).join(''):null;return {application:'Prism Atlas',engineVersion:'1.0.0',exportedAt:new Date().toISOString(),recipe:clone(state),description:describe(state),recipeSHA256:hash,note:'This checksum identifies this exact creative recipe. It does not prove copyright, originality, ownership, or data authenticity.'};}
function showExport(){openDialog('Made by you. Ready for the world.',`<p>Keep a print-ready image, a scalable artwork, or the recipe that lets you come back and create again.</p><label class="field-label" for="export-title">Artwork title</label><input type="text" id="export-title" maxlength="80" value="${esc(state.title)}"><label class="field-label" for="export-creator">Creator credit (optional, included in exported recipe)</label><input type="text" id="export-creator" maxlength="80" value="${esc(state.creator)}" placeholder="Your name or creative alias"><div class="export-grid" style="margin-top:20px"><button class="export-option" data-export="png"><strong>Print-ready PNG ↗</strong><small>2400 × 1800 px · high-resolution image</small></button><button class="export-option" data-export="svg"><strong>Scalable SVG ↗</strong><small>Vector artwork · description + recipe embedded</small></button><button class="export-option" data-export="json"><strong>Creative recipe ↗</strong><small>JSON · editable settings + original data + checksum</small></button><button class="export-option" data-export="csv"><strong>Original data ↗</strong><small>CSV · keep every original observation</small></button></div><p id="export-status" class="field-hint" role="status">The recipe and SVG include your data and creator credit. Review before sharing.</p><div class="callout">A transparent creative trail. Every recipe includes its source, settings, variation seed, and a SHA-256 checksum. This is reproducibility—not a claim of ownership or copyright verification.</div>`,'TAKE YOUR CREATIVITY WITH YOU');$$('[data-export]').forEach(b=>b.onclick=()=>exportArtwork(b.dataset.export));}
async function exportArtwork(kind){const buttons=$$('[data-export]');try{buttons.forEach(b=>b.disabled=true);$('#export-status').textContent='Preparing your '+kind.toUpperCase()+'…';change({title:$('#export-title').value.trim()||'Untitled study',creator:$('#export-creator').value.trim()});if(kind==='csv')downloadCSV();else{const r=await receipt();if(kind==='json')download(new Blob([JSON.stringify(r,null,2)],{type:'application/json'}),fileName()+'.json');else{const svg=renderSVG(state,'export',r),blob=new Blob([svg],{type:'image/svg+xml;charset=utf-8'});if(kind==='svg')download(blob,fileName()+'.svg');else{const img=new Image(),url=URL.createObjectURL(blob);try{await new Promise((resolve,reject)=>{img.onload=resolve;img.onerror=()=>reject(Error('The image could not be rendered. Try SVG instead.'));img.src=url;});const canvas=document.createElement('canvas');canvas.width=2400;canvas.height=1800;const ctx=canvas.getContext('2d');if(!ctx)throw Error('Image export is unavailable in this browser. Try SVG instead.');ctx.drawImage(img,0,0,2400,1800);const png=await new Promise(resolve=>canvas.toBlob(resolve,'image/png'));if(!png)throw Error('PNG export failed. Try SVG instead.');download(png,fileName()+'.png');}finally{URL.revokeObjectURL(url);}}}}$('#export-status').textContent=kind.toUpperCase()+' ready. Check your browser’s downloads.';toast('Your '+kind.toUpperCase()+' is ready.');}catch(e){$('#export-status').textContent='Export failed: '+e.message;}finally{buttons.forEach(b=>b.disabled=false);}}
function encodeRecipe(s){const bytes=new TextEncoder().encode(JSON.stringify(s));let raw='';bytes.forEach(b=>raw+=String.fromCharCode(b));return btoa(raw).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'');}
function decodeRecipe(s){const raw=atob(s.replace(/-/g,'+').replace(/_/g,'/'));return new TextDecoder().decode(Uint8Array.from(raw,c=>c.charCodeAt(0)));}
function showShare(){const link=location.origin+location.pathname+'#recipe='+encodeRecipe(state);openDialog('Pass a little inspiration on.',`<p>Share an editable recipe, not just a picture. Anyone with the link can open this exact creation and make their own variation—no account required.</p><div class="callout"><strong>Before you share:</strong> this link contains your dataset, labels, title, and creator credit. Do not share personal or confidential data. Nothing is uploaded to a Prism Atlas server.</div><label for="share-url" class="field-label">Your creative recipe link</label><textarea id="share-url" class="link-field" readonly rows="4">${esc(link)}</textarea><div class="dialog-actions"><button class="primary" id="copy-link">Copy recipe link</button></div><p class="field-hint" id="copy-status" role="status">Sharing sends the recipe to the people and platforms you choose.</p>`,'A RECIPE WORTH SHARING');$('#copy-link').onclick=async()=>{try{await navigator.clipboard.writeText(link);$('#copy-status').textContent='Link copied. Your recipient can remix this exact piece.';toast('Recipe link copied.');}catch(e){$('#share-url').focus();$('#share-url').select();$('#copy-status').textContent='Clipboard access is unavailable. The link is selected; copy it manually.';}};}
function savePiece(){if(gallery.length>=20){toast('Your collection holds 20 pieces. Remove one, or export a recipe to keep this creation.');return;}const duplicate=gallery.find(x=>JSON.stringify(x.state)===JSON.stringify(state));if(duplicate){toast('This exact piece is already in your collection.');return;}const item={id:crypto.randomUUID?crypto.randomUUID():String(Date.now()),date:new Date().toISOString(),state:clone(state)};gallery.unshift(item);if(saveGallery())toast('Saved to your collection on this device.');else gallery.shift();}
function showCollection(){openDialog('Your little atlas of possibilities.',`<p>Saved on this browser, on this device. Export a creative recipe for a backup or to move to another device. Your collection can hold 20 pieces.</p>${gallery.length?'<div class="local-grid">'+gallery.map((x,i)=>`<article class="saved-card"><div class="preview-art">${renderSVG({...x.state,density:30},'saved'+i)}</div><h3>${esc(x.state.title)}</h3><small>${esc(x.state.data.name)} · ${x.state.data.values.length} points</small><div class="saved-actions"><button class="secondary" data-load="${esc(x.id)}">Open recipe</button><button class="delete" data-delete="${esc(x.id)}">Remove</button></div></article>`).join('')+'</div>':'<div class="empty-state"><svg class="icon" aria-hidden="true"><use href="#i-folder"/></svg><h3>A place for your possibilities.</h3><p>Create something you love, then select Save beneath your artwork.</p><button class="secondary" id="collection-start">Back to the studio</button></div>'}`,'YOUR COLLECTION / '+gallery.length+' OF 20');if($('#collection-start'))$('#collection-start').onclick=closeDialog;$$('[data-load]').forEach(b=>b.onclick=()=>{const item=gallery.find(x=>x.id===b.dataset.load);if(item){commit(item.state,'Saved recipe opened.');closeDialog();}});$$('[data-delete]').forEach(b=>b.onclick=()=>{const i=gallery.findIndex(x=>x.id===b.dataset.delete);if(i<0)return;const [item]=gallery.splice(i,1);if(!saveGallery()){gallery.splice(i,0,item);return;}showCollection();toast('Piece removed from this device.',{label:'Undo',run:()=>{gallery.splice(i,0,item);saveGallery();if($('#dialog').open)showCollection();}});});}
function showAbout(){openDialog('Art that opens another door.',`<p>A chart can tell you what happened. Art can give you a reason to care. Prism Atlas is a small, working experiment in making data more personal, expressive, and approachable.</p><div class="about-grid"><div><h3>See the rhythm.</h3><p>Deterministic generative geometry turns each dataset into an editable visual study, with transparent value-to-shape mappings.</p></div><div><h3>Hear the pattern.</h3><p>Sonification makes high and low values audible, using a gentle pentatonic scale and the original observation order.</p></div><div><h3>Read the story.</h3><p>A data-grounded description explains the artwork, its source, its extremes, and its start-to-end change.</p></div><div><h3>Keep the process.</h3><p>Portable recipes carry the data, creator credit, settings, seed, and checksum. Anyone can reproduce or remix your study.</p></div></div><h3>Built for the InnovArt 2027 themes</h3><p class="dialog-copy">Data-informed artistic expression; adaptive and cross-sensory art; creative learning; interactive audience engagement; and transparent creative provenance.</p><div class="callout">An independent hackathon project, not an official event service. Example datasets are illustrative. No generative AI, live environmental feed, clinical claims, or copyright verification is used.</div><div class="dialog-actions"><button class="primary" id="about-tour">Try the guided introduction</button><a class="secondary" href="https://github.com/SweeMingXx/SweeMingXx.github.io/tree/main/prism-atlas" target="_blank" rel="noopener noreferrer">View the source ↗</a></div>`,'A LITTLE DATA. A DIFFERENT PERSPECTIVE.');$('#about-tour').onclick=()=>{tourStep=0;showTour();};}
function showAccess(){openDialog('Not one right way. Your way.',`<p>Choose the form of experience that works for you. You do not need to hear sound, distinguish a palette, or use a pointer to create a piece.</p><ul class="mapping-list"><li><strong>Keyboard-first controls</strong>Tab moves between controls. Enter or Space activates buttons. Arrow keys adjust the sliders. Escape closes dialogs.</li><li><strong>Words alongside visuals</strong>The artwork has a data-grounded description. The data table includes every original value. Selected controls expose their state to assistive technology.</li><li><strong>Motion is a choice</strong>Pause motion using the button on the artwork. System reduced-motion preferences take priority. There are no flashing effects.</li><li><strong>Sound is always optional</strong>Audio starts only when you ask. Select Listen again to stop. Opening or closing a dialog stops playback, as does leaving the browser tab.</li><li><strong>Your browser, your work</strong>No account, analytics, or application backend. Sessions and collections are local. Download a recipe to protect against clearing browser storage.</li></ul><p class="dialog-copy">The musical, written, and visual translations emphasize different aspects; they are not interchangeable scientific measurements. Keyboard and responsive behavior are tested, but this prototype has not undergone a formal accessibility certification or co-design study with disabled artists.</p>`,'DESIGNED TO INCLUDE YOU');}
function showHelp(){openDialog('A little guidance goes a long way.',`<ul class="mapping-list"><li><strong>1. Start with a story</strong>Choose illustrative data or import a CSV with two columns (label,value), 3–120 rows, and a maximum size of 64 KB.</li><li><strong>2. Follow your curiosity</strong>Change form, palette, flow, or detail. Discover a new variation changes the seed, not the source data. Undo and redo work across your last 40 recipe states in this session.</li><li><strong>3. Experience it differently</strong>Listen to the data or open the written description. Explore data explains exactly how the mapping works.</li><li><strong>4. Keep what you create</strong>Save up to 20 pieces locally. Export PNG (2400 × 1800), vector SVG, JSON recipe, or source CSV. Import a JSON recipe to resume elsewhere.</li></ul><h3>Keyboard shortcuts</h3><p class="dialog-copy"><span class="kbd">R</span> New variation · <span class="kbd">Space</span> Sound on/off · <span class="kbd">Ctrl/⌘ Z</span> Undo · <span class="kbd">Ctrl/⌘ Shift Z</span> Redo · <span class="kbd">Esc</span> Close dialog or immersive view. Single-key shortcuts are inactive while typing, using controls, or in a dialog.</p><div class="callout">If local storage is blocked or full, your canvas still works. Export JSON to keep the recipe. If PNG export fails, try the vector SVG instead. Sound may need browser permission or an unmuted device.</div><div class="dialog-actions"><button class="secondary" id="reset-open">Start a fresh canvas</button></div>`,'MAKE ROOM FOR CURIOSITY');$('#reset-open').onclick=()=>{openDialog('Start fresh?',`<p>This resets the current canvas to Tidal memory. Your collection stays untouched. You can undo the reset during this session.</p><div class="dialog-actions"><button class="primary" id="reset-confirm">Start fresh</button><button class="secondary" id="reset-cancel">Keep creating</button></div>`);$('#reset-confirm').onclick=()=>{commit(clone(defaultState),'A fresh canvas. Your collection is safe.');closeDialog();};$('#reset-cancel').onclick=closeDialog;};}
const tour=[{title:'A story hiding in plain sight.',text:'Start with twelve illustrative tide heights. Every value helps shape this woven ribbon. This is a creative interpretation, not a tide forecast.'},{title:'One story. A different language.',text:'The same data can become a bloom. Higher values extend its petals. Form and palette change the expression without changing the original numbers.'},{title:'You can hear a pattern, too.',text:'Listen: lower values play lower notes, higher values play higher notes. Or experience the same story in words. No single sense is a prerequisite.'},{title:'Make something only you would make.',text:'Bring your own two-column CSV, shape it, and save a piece. Export a PNG for a wall, an SVG for a project, or a recipe for someone to remix.'}];
function showTour(){const t=tour[tourStep];openDialog(t.title,`<div class="tour-count">0${tourStep+1} / 04 · A ONE-MINUTE INTRODUCTION</div><div class="tour-art">${renderSVG({...state,density:35},'tour')}</div><p>${esc(t.text)}</p>${tourStep===2?'<button class="secondary" data-listen>Listen to the data</button>':''}<div class="dialog-actions">${tourStep?'<button class="secondary" id="tour-back">Back</button>':''}<button class="primary" id="tour-next">${tourStep===3?'Make it yours':'Next perspective →'}</button></div>`,'MEET YOUR CREATIVE MEDIUM');if($('[data-listen]'))$('[data-listen]').onclick=toggleAudio;if($('#tour-back'))$('#tour-back').onclick=()=>{tourStep--;showTour();};$('#tour-next').onclick=()=>{if(tourStep===3){closeDialog();$('#studio').scrollIntoView();$('#source').focus();return;}tourStep++;if(tourStep===1)change({form:'bloom'});showTour();};}
function toggleFullscreen(){const stage=$('#art-stage');if(stage.classList.contains('focus-view')){stage.classList.remove('focus-view');document.body.classList.remove('focus-active');$('#fullscreen').setAttribute('aria-label','View artwork full screen');return;}if(document.fullscreenElement){document.exitFullscreen();return;}if(stage.requestFullscreen){stage.requestFullscreen().catch(()=>fallback());}else fallback();function fallback(){stage.classList.add('focus-view');document.body.classList.add('focus-active');$('#fullscreen').setAttribute('aria-label','Exit full-screen artwork');$('#fullscreen').focus();}}
loadStorage();render();showPresets();persist();
$('#source').onchange=e=>{if(datasets[e.target.value]){const source=e.target.value;change({source,data:clone(datasets[source]),title:source==='ocean'?'Tidal memory':source==='warmth'?'A year of warmth':'The shape of a feeling'},'A different story, ready to explore.');}};
$$('[data-form]').forEach(b=>b.onclick=()=>change({form:b.dataset.form}));$$('[data-palette]').forEach(b=>b.onclick=()=>change({palette:b.dataset.palette}));
for(const k of ['flow','density']){$('#'+k).oninput=e=>{const v=+e.target.value;$('#'+k+'-value').textContent=v+'%';cancelAnimationFrame(renderFrame);renderFrame=requestAnimationFrame(()=>renderArt({...state,[k]:v}));};$('#'+k).onchange=e=>change({[k]:+e.target.value});}
$('#remix').onclick=()=>{const a=new Uint32Array(1);crypto.getRandomValues(a);change({seed:a[0]},'A new variation. The same data, another possibility.');};$('#undo').onclick=()=>undo(-1);$('#redo').onclick=()=>undo(1);$('#save').onclick=savePiece;$('#listen').onclick=toggleAudio;$('#motion').onclick=()=>{if(matchMedia('(prefers-reduced-motion: reduce)').matches){toast('Your system’s reduced-motion preference is on. Motion stays paused.');return;}motion=!motion;renderMotion();toast(motion?'Gentle motion on.':'Motion paused.');};
$('#fullscreen').onclick=toggleFullscreen;$('#describe').onclick=showDescription;$('#data-open').onclick=showData;$('#mapping-open').onclick=showData;$('#import-open').onclick=showImport;$('#export-open').onclick=showExport;$('#share-open').onclick=showShare;$('#collection-open').onclick=showCollection;$('#about-open').onclick=showAbout;$('#access-open').onclick=showAccess;$('#help-open').onclick=showHelp;$('#tour-open').onclick=()=>{tourStep=0;commit(clone(defaultState));showTour();};
$('#dialog-close').onclick=closeDialog;$('#dialog').addEventListener('cancel',e=>{e.preventDefault();closeDialog();});$('#dialog').addEventListener('click',e=>{if(e.target===$('#dialog')){const r=$('#dialog').getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)closeDialog();}});
document.addEventListener('keydown',e=>{if(e.key==='Escape'&&$('#art-stage').classList.contains('focus-view'))toggleFullscreen();if($('#dialog').open||e.target.closest('input,textarea,select,button,a,[contenteditable=true]'))return;if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='z'){e.preventDefault();undo(e.shiftKey?1:-1);}else if(!e.ctrlKey&&!e.metaKey&&!e.altKey&&e.key.toLowerCase()==='r')$('#remix').click();else if(e.code==='Space'){e.preventDefault();toggleAudio();}});
document.addEventListener('visibilitychange',()=>{if(document.hidden){stopAudio();if(window.speechSynthesis)speechSynthesis.cancel();}});document.addEventListener('fullscreenchange',()=>{const label=document.fullscreenElement?'Exit full-screen artwork':'View artwork full screen';$('#fullscreen').setAttribute('aria-label',label);$('#fullscreen').title=label;});matchMedia('(prefers-reduced-motion: reduce)').addEventListener('change',renderMotion);
window.addEventListener('hashchange',()=>{if(location.hash.startsWith('#recipe=')){try{if(location.hash.length>35008)throw Error();commit(validateProject(JSON.parse(decodeRecipe(location.hash.slice(8)))),'Shared recipe opened.');}catch(e){toast('This shared recipe is invalid. Your current artwork is unchanged.');}}});
if(initMessages.length)setTimeout(()=>toast(initMessages.join(' ')),700);if(!storageOK)setTimeout(()=>toast('Local storage is unavailable. Export a recipe to keep your creation.'),900);
})();
