'use strict';
(() => {
const $ = id => document.getElementById(id);
const $$ = selector => [...document.querySelectorAll(selector)];
const esc = s => String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const icon = name => `<svg aria-hidden="true"><use href="#i-${name}"/></svg>`;
const PRESETS = [
 {id:'amber',title:'Amber tides',subtitle:'A little warmth. A little wonder.',mood:'WARM & WANDERING',form:'flow',colors:['#D9744C','#E6AD7F','#EACDA0','#709B92','#335D61'],instrument:'warm',tempo:72,motion:35,seed:38},
 {id:'midnight',title:'Midnight bloom',subtitle:'For the thoughts that flower after dark.',mood:'DREAMY & EXPANSIVE',form:'bloom',colors:['#B9A5E0','#8966BB','#E3BFD7','#5674A4','#333E68'],instrument:'glass',tempo:60,motion:24,seed:81},
 {id:'orbit',title:'Quiet orbit',subtitle:'Somewhere between stillness and space.',mood:'COOL & WEIGHTLESS',form:'orbit',colors:['#82C4CE','#A2D5BA','#E8DDAE','#528A96','#314E66'],instrument:'soft',tempo:54,motion:20,seed:19},
 {id:'moss',title:'Moss & memory',subtitle:'A small return to the natural world.',mood:'EARTHY & REFLECTIVE',form:'flow',colors:['#ADBF84','#6D956B','#D6C69D','#819F92','#425F47'],instrument:'warm',tempo:66,motion:30,seed:62}
];
const STORAGE = 'spectra.collection.v1', DRAFT = 'spectra.draft.v1';
let state = {...PRESETS[0],colors:[...PRESETS[0].colors],volume:45,still:matchMedia('(prefers-reduced-motion: reduce)').matches};
let collection=[], playing=false, selectedNote=0, phase=0, lastFrame=0, dirty=true, collectionVisible=false, needsSave=false;
let audio=null,master=null,loopTimer=null,nextNote=0,activeVoices=[],speechActive=false,toastTimer,hintTimer,draftTimer;
const sanitize = data => {
 if(!data || typeof data!=='object' || !Array.isArray(data.colors) || data.colors.length!==5 || data.colors.some(c=>typeof c!=='string'||!/^#[0-9a-f]{6}$/i.test(c))) throw new Error('This is not a valid SPECTRA composition.');
 const num=(v,min,max,fallback)=>Number.isFinite(Number(v))?Math.min(max,Math.max(min,Number(v))):fallback;
 return {id:'custom',title:String(data.title||'Untitled feeling').slice(0,70),subtitle:String(data.subtitle||'An original composition, made by you.').slice(0,140),colors:[...data.colors],form:['flow','bloom','orbit'].includes(data.form)?data.form:'flow',instrument:['warm','glass','soft'].includes(data.instrument)?data.instrument:'warm',tempo:Math.round(num(data.tempo,48,120,72)),motion:Math.round(num(data.motion,0,100,35)),volume:Math.round(num(data.volume,0,100,45)),seed:num(data.seed,0,10000,38),still:typeof data.still==='boolean'?data.still:false};
};
function toast(message){$('toast').textContent=message;$('toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').classList.remove('show'),4200);}
function announce(message){$('a11y-status').textContent=message;}
function persistDraft(){clearTimeout(draftTimer);draftTimer=setTimeout(()=>{try{localStorage.setItem(DRAFT,JSON.stringify(state));}catch{}},250);}
function changed(){dirty=true;needsSave=true;$('save-status').textContent='Your changes are ready to save.';persistDraft();updateDescription();}
try {const stored=JSON.parse(localStorage.getItem(STORAGE)||'[]');if(Array.isArray(stored))collection=stored.slice(0,40).filter(x=>{try{sanitize(x);return typeof x.savedId==='string';}catch{return false;}});}catch{}
try {const draft=localStorage.getItem(DRAFT);if(draft)state=sanitize(JSON.parse(draft));}catch{}
let sharedLoaded=false, badShare=false;
if(location.hash.startsWith('#s=')){
 try{const raw=location.hash.slice(3);if(raw.length>6000)throw new Error();state=sanitize(JSON.parse(decodeURIComponent(escape(atob(raw.replace(/-/g,'+').replace(/_/g,'/'))))));sharedLoaded=true;}catch{badShare=true;}
}
if(matchMedia('(prefers-reduced-motion: reduce)').matches)state.still=true;
function rgb(hex){return [1,3,5].map(i=>parseInt(hex.slice(i,i+2),16));}
function hue(hex){const [r,g,b]=rgb(hex).map(c=>c/255),max=Math.max(r,g,b),min=Math.min(r,g,b),d=max-min;let h=0;if(d){if(max===r)h=((g-b)/d)%6;else if(max===g)h=(b-r)/d+2;else h=(r-g)/d+4;}return (h*60+360)%360;}
function noteFor(color){const h=hue(color),[r,g,b]=rgb(color),light=(.2126*r+.7152*g+.0722*b)/255,scale=[0,2,4,7,9],slot=Math.min(4,Math.floor(h/72)),octave=light>.55?4:3,midi=(octave+1)*12+scale[slot],name=['C','D','E','G','A'][slot]+octave;return {name,midi,freq:440*Math.pow(2,(midi-69)/12),color,word:colorWord(color)};}
function colorWord(color){const [r,g,b]=rgb(color),max=Math.max(r,g,b),min=Math.min(r,g,b);if(max-min<25)return max>180?'soft pearl':max<75?'deep charcoal':'quiet stone';const h=hue(color);return h<20?'warm coral':h<48?'warm amber':h<78?'soft gold':h<160?'moss green':h<205?'ocean teal':h<260?'midnight blue':h<310?'soft violet':'rose pink';}
function motionName(s=state){return s.motion===0?'Still':s.motion<34?'Slow':s.motion<67?'Gentle':'Expressive';}
function description(s=state){const forms={flow:'Layered, flowing ribbons curl around an open center',bloom:'Fine, petal-like contours unfold around a central opening',orbit:'Elliptical rings overlap in a tilted, orbital sculpture'};return `${s.title}. ${forms[s.form]}, against a dark background. The palette moves through ${s.colors.map(colorWord).join(', ')}. ${s.still||!s.motion?'The artwork is still.':motionName(s)+' movement softly shifts its contours.'} Its ${s.instrument==='warm'?'warm keys':s.instrument==='glass'?'glass chimes':'soft waves'} play ${s.colors.map(c=>noteFor(c).name).join(', ')} at ${s.tempo} beats per minute.`;}
function updateDescription(){$('art-description').textContent=description();$('art-canvas').setAttribute('aria-label',`${state.title}: ${state.form} artwork. Arrow keys select a color; Enter plays it. Keys 1 to 5 play colors.`);$('note-mapping').innerHTML=state.colors.map((c,i)=>`<button class="note-key" data-note="${i}" aria-label="Play color ${i+1}, ${esc(colorWord(c))}, note ${noteFor(c).name}"><i style="background:${c}"></i>${noteFor(c).name}<span>${i+1}</span></button>`).join('');$$('#note-mapping button').forEach(b=>b.onclick=()=>explore(Number(b.dataset.note)));}
function renderPalette(){$('palette').innerHTML=state.colors.map((c,i)=>`<div class="color-item" data-color="${i}"><div class="swatch-wrap"><input type="color" value="${c}" id="color-${i}" aria-label="Color ${i+1}: ${esc(colorWord(c))}"></div><span>${c}</span></div>`).join('');$$('#palette input').forEach((input,i)=>input.addEventListener('input',()=>{state.colors[i]=input.value;input.parentElement.nextElementSibling.textContent=input.value;input.setAttribute('aria-label',`Color ${i+1}: ${colorWord(input.value)}`);changed();}));}
function updateRange(input){const p=(Number(input.value)-Number(input.min))/(Number(input.max)-Number(input.min))*100;input.style.setProperty('--range',p+'%');}
function sync(){if(master&&audio)master.gain.setTargetAtTime(state.volume/100*.24,audio.currentTime,.05);renderPalette();$('art-title').textContent=state.title;$('art-subtitle').textContent=state.subtitle;$('motion-range').value=state.motion;$('motion-value').textContent=motionName();$('motion-range').setAttribute('aria-valuetext',motionName());$('tempo-range').value=state.tempo;$('tempo-value').textContent=state.tempo+' BPM';$('volume-range').value=state.volume;$('volume-value').textContent=state.volume+'%';$('instrument-select').value=state.instrument;$('low-motion').checked=state.still;$$('[data-form]').forEach(b=>{b.classList.toggle('selected',b.dataset.form===state.form);b.setAttribute('aria-pressed',String(b.dataset.form===state.form));});$$('input[type=range]').forEach(updateRange);syncMotion();updateDescription();updateCount();dirty=true;}
function syncMotion(){const still=state.still||!state.motion;document.body.classList.toggle('motion-off',still);$('canvas-mode').textContent=still?'STILL ARTWORK':'LIVING ARTWORK';$('motion-button').innerHTML=icon(still?'play':'pause');$('motion-button').setAttribute('aria-label',still?'Resume visual motion':'Pause visual motion');$('motion-button').title=still?'Resume visual motion':'Pause visual motion';$('low-motion').checked=state.still;}
function updateCount(){$('collection-count').textContent=collection.length;$('collection-summary').textContent=`${collection.length} saved creation${collection.length===1?'':'s'}`;}
// Original parametric contour renderer. No stock artwork or remote image service.
let grain;
function noiseTexture(){if(grain)return grain;grain=document.createElement('canvas');grain.width=grain.height=128;const g=grain.getContext('2d'),data=g.createImageData(128,128);let n=923;for(let i=0;i<data.data.length;i+=4){n=(n*1664525+1013904223)>>>0;const v=n%256;data.data[i]=data.data[i+1]=data.data[i+2]=v;data.data[i+3]=18;}g.putImageData(data,0,0);return grain;}
function drawArtwork(canvas,s,time=0,quality=1){const ctx=canvas.getContext('2d');if(!ctx)return;const w=canvas.width,h=canvas.height;ctx.clearRect(0,0,w,h);ctx.fillStyle='#101b1e';ctx.fillRect(0,0,w,h);const background=ctx.createRadialGradient(w*.5,h*.42,0,w*.5,h*.48,w*.75);background.addColorStop(0,`${s.colors[4]}75`);background.addColorStop(.6,`${s.colors[4]}1e`);background.addColorStop(1,'#091316');ctx.fillStyle=background;ctx.fillRect(0,0,w,h);
const compact=w/h<1,base=Math.min(w*.44,h*.39),cx=w*.51,cy=h*.47,t=time*.00022,sig=s.seed*.019;
let seed=2027;for(let i=0;i<110*quality;i++){seed=(seed*16807)%2147483647;const x=(seed%10000)/10000*w;seed=(seed*16807)%2147483647;const y=(seed%10000)/10000*h;ctx.fillStyle=`rgba(213,227,207,${.08+(i%5)*.025})`;ctx.beginPath();ctx.arc(x,y,(i%3===0?.65:.35)*Math.max(1,w/900),0,Math.PI*2);ctx.fill();}
ctx.save();ctx.translate(cx,cy);ctx.rotate(s.form==='orbit'?-.32:-.2);ctx.globalCompositeOperation='screen';const layers=Math.round(94*quality),steps=Math.round(170*Math.max(.7,quality));
for(let j=0;j<layers;j++){const u=j/(layers-1),r=base*(.37+u*.66);ctx.beginPath();for(let k=0;k<=steps;k++){const a=k/steps*Math.PI*2;let x,y;if(s.form==='flow'){const deform=1+.16*Math.sin(3*a+t+sig+u*.7)+.065*Math.cos(5*a-t*.6+u*1.8);x=Math.cos(a)*r*deform*1.1+Math.sin(2*a+u*3+t)*base*.12;y=Math.sin(a)*r*deform*.91+Math.cos(3*a+u*2+t*.7)*base*.055;}else if(s.form==='bloom'){const petals=1+.2*Math.sin(6*a+u*2+t*.65)+.08*Math.sin(3*a-t);x=Math.cos(a+u*.27)*r*petals;y=Math.sin(a+u*.27)*r*petals*.97;}else{const wave=1+.055*Math.sin(4*a+t+u*3);x=Math.cos(a+u*.22)*r*wave*1.18;y=Math.sin(a+u*.22)*r*.63+(u-.5)*base*.49+Math.sin(a*2+t)*base*.045;}if(k===0)ctx.moveTo(x,y);else ctx.lineTo(x,y);}ctx.closePath();const gradient=ctx.createLinearGradient(-base,-base*.8,base,base);const n=(Math.floor(u*3)+Math.floor(sig))%5;gradient.addColorStop(0,s.colors[3]);gradient.addColorStop(.26,s.colors[0]);gradient.addColorStop(.5,s.colors[1]);gradient.addColorStop(.68,s.colors[2]);gradient.addColorStop(.89,s.colors[n]);gradient.addColorStop(1,s.colors[4]);ctx.strokeStyle=gradient;ctx.globalAlpha=.30+.48*Math.pow(Math.sin(u*Math.PI),.6)+.15*Math.sin(u*35+t);ctx.lineWidth=(.65+.55*Math.sin(u*Math.PI))*Math.max(1,w/1000)/quality;ctx.stroke();if(j%16===0){ctx.globalAlpha=.07;ctx.lineWidth=5*Math.max(1,w/1000);ctx.stroke();}}
ctx.restore();const vignette=ctx.createLinearGradient(0,h*.62,0,h);vignette.addColorStop(0,'#0b171800');vignette.addColorStop(1,'#0b1718a8');ctx.fillStyle=vignette;ctx.fillRect(0,0,w,h);ctx.globalAlpha=.23;ctx.fillStyle=ctx.createPattern(noiseTexture(),'repeat');ctx.fillRect(0,0,w,h);ctx.globalAlpha=1;
}
const canvas=$('art-canvas');
function resize(){const rect=$('canvas-stage').getBoundingClientRect(),dpr=Math.min(devicePixelRatio||1,1.5);if(rect.width<1||rect.height<1)return;canvas.width=Math.round(rect.width*dpr);canvas.height=Math.round(rect.height*dpr);dirty=true;}
new ResizeObserver(resize).observe($('canvas-stage'));
function animate(timestamp){if(!collectionVisible&&!document.hidden&&(dirty||(!state.still&&state.motion>0&&timestamp-lastFrame>48))){if(!state.still&&state.motion>0)phase+=Math.min(timestamp-lastFrame,100)*state.motion/40;lastFrame=timestamp;drawArtwork(canvas,state,phase,innerWidth<621?.75:1);dirty=false;}requestAnimationFrame(animate);}
function renderPresets(){$('preset-grid').innerHTML=PRESETS.map((s,i)=>`<button class="preset-card" data-preset="${i}" aria-label="Load ${esc(s.title)} preset"><div class="preset-art"><canvas id="preset-${i}" width="560" height="340" aria-hidden="true"></canvas><span class="preset-use">${icon('arrow')}</span></div><div class="preset-meta"><h3>${esc(s.title)}</h3><span class="preset-colors" aria-hidden="true">${s.colors.map(c=>`<i style="background:${c}"></i>`).join('')}</span></div><p class="preset-caption">${s.mood}</p></button>`).join('');PRESETS.forEach((s,i)=>drawArtwork($('preset-'+i),s,0,.8));$$('[data-preset]').forEach(b=>b.onclick=()=>loadPreset(Number(b.dataset.preset)));}
function loadPreset(index){const s=PRESETS[index];if(!s)return;const still=state.still,volume=state.volume;state={...s,colors:[...s.colors],still,volume};phase=0;sync();changed();restartLoop();toast(`${s.title} is yours to explore.`);$('studio').scrollIntoView({behavior:state.still?'instant':'smooth',block:'start'});}
// Pentatonic, hue-based sonification. All synthesis happens in Web Audio locally.
async function ensureAudio(){const Audio=window.AudioContext||window.webkitAudioContext;if(!Audio){toast('This browser does not support audio synthesis. You can still create and export visual art.');return false;}try{if(!audio){audio=new Audio();master=audio.createGain();master.gain.value=state.volume/100*.24;const compressor=audio.createDynamicsCompressor();compressor.threshold.value=-16;compressor.ratio.value=4;master.connect(compressor);compressor.connect(audio.destination);}if(audio.state==='suspended')await audio.resume();return audio.state==='running';}catch{toast('Audio could not start. Check your browser sound permissions and try again.');return false;}}
function synth(context,destination,note,time,duration,instrument){const envelope=context.createGain();envelope.gain.setValueAtTime(0,time);envelope.gain.linearRampToValueAtTime(.5,time+(instrument==='soft'?.2:.018));envelope.gain.exponentialRampToValueAtTime(.001,time+duration);const filter=context.createBiquadFilter();filter.type='lowpass';filter.frequency.value=instrument==='soft'?1000:instrument==='warm'?2600:8000;envelope.connect(filter);filter.connect(destination);const a=context.createOscillator(),b=context.createOscillator(),harmonic=context.createGain();a.type=instrument==='soft'?'triangle':'sine';a.frequency.value=note.freq;b.type='sine';b.frequency.value=note.freq*(instrument==='glass'?2.005:2);harmonic.gain.value=instrument==='glass'?.22:.12;a.connect(envelope);b.connect(harmonic);harmonic.connect(envelope);a.start(time);b.start(time);a.stop(time+duration+.04);b.stop(time+duration+.04);a.onended=()=>{a.disconnect();b.disconnect();harmonic.disconnect();envelope.disconnect();filter.disconnect();};return {a,b,envelope};}
function visualNote(index){selectedNote=index;$$('.color-item').forEach((el,i)=>el.classList.toggle('sounding',i===index));const note=noteFor(state.colors[index]);$('explore-note').textContent=`${note.name} · ${note.word}`;$('canvas-center-hint').classList.add('show');clearTimeout(hintTimer);hintTimer=setTimeout(()=>{$('canvas-center-hint').classList.remove('show');$$('.color-item').forEach(el=>el.classList.remove('sounding'));},650);}
function playNote(index){if(!audio)return;activeVoices=activeVoices.filter(v=>v.until>audio.currentTime);const voice=synth(audio,master,noteFor(state.colors[index]),audio.currentTime+.012,state.instrument==='glass'?2.2:1.7,state.instrument);activeVoices.push({...voice,until:audio.currentTime+2.3});visualNote(index);}
async function explore(index){if(index<0||index>4)return;if(await ensureAudio()){playNote(index);announce(`Color ${index+1}, ${colorWord(state.colors[index])}, ${noteFor(state.colors[index]).name}.`);}}
function tick(){const index=[0,1,2,3,4,3,2,1][nextNote%8];playNote(index);nextNote++;$('play-status').textContent=`${noteFor(state.colors[index]).name} · ${state.tempo} BPM`;}
function restartLoop(){if(!playing)return;clearInterval(loopTimer);loopTimer=setInterval(tick,60000/state.tempo);}
async function togglePlay(){if(playing){stopAudio();return;}if(!await ensureAudio())return;playing=true;nextNote=0;tick();restartLoop();$('play-label').textContent='Pause soundscape';$('play-button').querySelector('use').setAttribute('href','#i-pause');$('sound-meter').classList.add('active');$('play-button').setAttribute('aria-pressed','true');announce('Soundscape playing. Press Space to pause.');}
function stopAudio(){playing=false;clearInterval(loopTimer);if(audio){activeVoices.forEach(v=>{try{v.envelope.gain.cancelScheduledValues(audio.currentTime);v.envelope.gain.setTargetAtTime(.0001,audio.currentTime,.025);v.a.stop(audio.currentTime+.15);v.b.stop(audio.currentTime+.15);}catch{}});}activeVoices=[];$('play-label').textContent='Play soundscape';$('play-button').querySelector('use').setAttribute('href','#i-play');$('sound-meter').classList.remove('active');$('play-status').textContent='Paused. Take your time.';$('play-button').setAttribute('aria-pressed','false');announce('Soundscape paused.');}
$('play-button').onclick=togglePlay;
$('motion-range').oninput=e=>{state.motion=Number(e.target.value);$('motion-value').textContent=motionName();e.target.setAttribute('aria-valuetext',motionName());updateRange(e.target);syncMotion();changed();};
$('tempo-range').oninput=e=>{state.tempo=Number(e.target.value);$('tempo-value').textContent=state.tempo+' BPM';updateRange(e.target);restartLoop();changed();};
$('volume-range').oninput=e=>{state.volume=Number(e.target.value);$('volume-value').textContent=state.volume+'%';updateRange(e.target);if(master)master.gain.setTargetAtTime(state.volume/100*.24,audio.currentTime,.05);changed();};
$('instrument-select').onchange=e=>{state.instrument=e.target.value;changed();};
$$('[data-form]').forEach(b=>b.onclick=()=>{state.form=b.dataset.form;sync();changed();announce(`${state.form} shape selected.`);});
$('shuffle-button').onclick=()=>{const pool=PRESETS[Math.floor(Math.random()*PRESETS.length)];state.colors=[...pool.colors];const offset=1+Math.floor(Math.random()*4);state.colors=state.colors.slice(offset).concat(state.colors.slice(0,offset));state.seed=Math.floor(Math.random()*1000);renderPalette();changed();toast('A fresh palette. A different feeling.');};
$('motion-button').onclick=()=>{state.still=!(state.still||!state.motion);if(!state.still&&!state.motion)state.motion=35;sync();changed();announce(state.still?'Visual motion paused.':'Visual motion resumed.');};
$('low-motion').onchange=e=>{state.still=e.target.checked;syncMotion();changed();};
$('high-contrast').onchange=e=>document.body.classList.toggle('high-contrast',e.target.checked);
$('fullscreen-button').onclick=async()=>{try{if(document.fullscreenElement){await document.exitFullscreen();}else if($('canvas-stage').requestFullscreen){await $('canvas-stage').requestFullscreen();}else{toast('Fullscreen is not available in this browser. Rotate your device for a larger canvas.');}}catch{toast('Fullscreen was blocked by your browser. The studio still works in this view.');}};
document.addEventListener('fullscreenchange',()=>{$('fullscreen-button').setAttribute('aria-label',document.fullscreenElement?'Exit fullscreen':'Enter fullscreen');resize();});
canvas.addEventListener('pointerdown',e=>{const r=canvas.getBoundingClientRect();explore(Math.max(0,Math.min(4,Math.floor((e.clientX-r.left)/r.width*5))));});
canvas.addEventListener('keydown',e=>{if(e.key==='ArrowRight'||e.key==='ArrowLeft'){e.preventDefault();selectedNote=(selectedNote+(e.key==='ArrowRight'?1:4))%5;visualNote(selectedNote);announce(`Selected color ${selectedNote+1}: ${colorWord(state.colors[selectedNote])}, ${noteFor(state.colors[selectedNote]).name}. Press Enter to hear it.`);}else if(e.key==='Enter'){e.preventDefault();explore(selectedNote);}});
document.addEventListener('keydown',e=>{if(e.ctrlKey||e.metaKey||e.altKey||e.repeat||$('modal').open||collectionVisible)return;const tag=e.target.tagName;if(['INPUT','SELECT','TEXTAREA'].includes(tag)||e.target.isContentEditable)return;if(e.code==='Space'&&tag!=='BUTTON'&&tag!=='A'){e.preventDefault();togglePlay();}else if(/^[1-5]$/.test(e.key)){e.preventDefault();explore(Number(e.key)-1);}});
document.addEventListener('visibilitychange',()=>{if(document.hidden){if(playing)stopAudio();if('speechSynthesis'in window)speechSynthesis.cancel();}});
function tab(which){const create=which==='create';$('create-panel').hidden=!create;$('experience-panel').hidden=create;['create','experience'].forEach(name=>{const el=$(name+'-tab'),on=name===which;el.classList.toggle('active',on);el.setAttribute('aria-selected',String(on));el.tabIndex=on?0:-1;});}
$('create-tab').onclick=()=>tab('create');$('experience-tab').onclick=()=>tab('experience');
$$('[role=tab]').forEach(el=>el.addEventListener('keydown',e=>{if(['ArrowLeft','ArrowRight','Home','End'].includes(e.key)){e.preventDefault();const to=e.key==='Home'?'create':e.key==='End'?'experience':el.id==='create-tab'?'experience':'create';tab(to);$(to+'-tab').focus();}}));
// Private image-to-palette extraction: quantized colors followed by diverse cluster selection.
$('import-button').onclick=()=>$('image-input').click();
$('image-input').onchange=e=>{const file=e.target.files[0];if(file)importImage(file);e.target.value='';};
async function importImage(file){if(!['image/png','image/jpeg','image/webp'].includes(file.type)){toast('Choose a PNG, JPG or WebP image. Your current artwork is unchanged.');return;}if(file.size>10*1024*1024){toast('That image is over 10 MB. Try a smaller image.');return;}const button=$('import-button');button.disabled=true;button.textContent='Finding your colors…';announce('Analyzing your image on this device.');const url=URL.createObjectURL(file);try{const img=new Image();img.src=url;await img.decode();if(img.naturalWidth*img.naturalHeight>40000000)throw new Error('size');const sample=document.createElement('canvas');sample.width=sample.height=80;const c=sample.getContext('2d',{willReadFrequently:true});c.fillStyle='#f5f3ee';c.fillRect(0,0,80,80);c.drawImage(img,0,0,80,80);const pixels=c.getImageData(0,0,80,80).data,buckets=new Map();for(let i=0;i<pixels.length;i+=4){if(pixels[i+3]<128)continue;const key=[pixels[i],pixels[i+1],pixels[i+2]].map(v=>Math.min(240,Math.floor(v/24)*24+12)).join(',');buckets.set(key,(buckets.get(key)||0)+1);}const sorted=[...buckets].sort((a,b)=>b[1]-a[1]).map(([key,count])=>({rgb:key.split(',').map(Number),count}));if(!sorted.length)throw new Error('empty');const colors=[];for(const threshold of [68,30,0]){for(const item of sorted){if(colors.every(c=>Math.hypot(...c.map((v,i)=>v-item.rgb[i]))>threshold))colors.push(item.rgb);if(colors.length===5)break;}if(colors.length===5)break;}while(colors.length<5){const base=colors[0],offset=(colors.length-2)*20;colors.push(base.map(v=>Math.min(240,Math.max(16,v+offset))));}state.colors=colors.map(v=>'#'+v.map(n=>n.toString(16).padStart(2,'0')).join(''));state.title='Colors from your world';state.subtitle='A new feeling, found in your own image.';sync();changed();toast('Your palette is ready. The image never left your device.');}catch(e){toast(e.message==='size'?'Use an image smaller than 40 megapixels. Your artwork is unchanged.':'We could not read that image. Try another PNG, JPG or WebP.');}finally{URL.revokeObjectURL(url);button.disabled=false;button.innerHTML=icon('upload')+' Find colors in your own image <span>↗</span>';}}
let dragDepth=0;$('canvas-stage').addEventListener('dragenter',e=>{e.preventDefault();dragDepth++;$('drop-overlay').classList.add('show');});$('canvas-stage').addEventListener('dragover',e=>e.preventDefault());$('canvas-stage').addEventListener('dragleave',()=>{dragDepth--;if(dragDepth<=0)$('drop-overlay').classList.remove('show');});$('canvas-stage').addEventListener('drop',e=>{e.preventDefault();dragDepth=0;$('drop-overlay').classList.remove('show');if(e.dataTransfer.files[0])importImage(e.dataTransfer.files[0]);});
// Native modal dialogs provide focus containment, Escape-to-close and focus restoration.
function openModal(html,eyebrow='SPECTRA STUDIO'){if('speechSynthesis'in window)speechSynthesis.cancel();$('modal-content').innerHTML=html;$('modal-eyebrow').textContent=eyebrow;if(!$('modal').open)$('modal').showModal();}
function closeModal(){$('modal').close();}
$('modal-close').onclick=closeModal;$('modal').addEventListener('keydown',e=>{if(e.key==='Escape'){e.preventDefault();closeModal();}});$('modal').addEventListener('click',e=>{if(e.target===$('modal')){const r=$('modal').getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)closeModal();}});
function how(){openModal(`<h2 id="modal-title">Follow your senses.</h2><p>No art training. No music theory. Just a little curiosity.</p><div class="modal-steps"><div class="modal-step"><span>01</span><div><h3>Find your colors</h3><p>Start with a world below, edit the five swatches, or extract a palette from your own image. Images are processed on this device.</p></div></div><div class="modal-step"><span>02</span><div><h3>Give them a voice</h3><p>Press Play soundscape. Each color becomes a note. Change the shape, instrument and tempo, or tap the canvas to play it yourself.</p></div></div><div class="modal-step"><span>03</span><div><h3>Keep your little world</h3><p>Save locally, share a composition link, or download artwork, a 16-second soundscape, a visual score or a reusable project.</p></div></div></div><div class="keyboard-help"><span><kbd>space</kbd> play / pause</span><span><kbd>1</kbd>–<kbd>5</kbd> play colors</span><span><kbd>esc</kbd> close dialogs</span></div><button class="primary-button" id="start-creating">Let's make something ${icon('arrow')}</button>`,'A SMALL GUIDE');$('start-creating').onclick=()=>{closeModal();showView('studio');$('play-button').focus();};}
function about(){openModal(`<h2 id="modal-title">Art, beyond the visible.</h2><p>SPECTRA is a small experiment with a big question: what happens when visual art becomes something you can hear, explore and describe?</p><h3>One composition. More than one way in.</h3><p>Five colors drive both an original generative artwork and a pentatonic soundscape. Hue chooses the note; brightness chooses the octave. A descriptive text connects its colors, structure, motion and musical score.</p><p>This is a designed artistic translation—not a claim that colors have an inherent sound, and not a medical or therapeutic tool.</p><h3>Built for InnovArt 2027</h3><p>The project explores art across sensory modalities, accessible creative tools, interactive art, and creative learning. It works without an account, an AI service, or a paid API.</p><h3>An honest next step</h3><p>Keyboard controls, still motion, a higher-contrast mode and text alternatives are included. Co-design and usability testing with blind, low-vision and Deaf participants are still needed; universal accessibility is not claimed.</p><button class="primary-button" id="about-access">Accessibility & privacy ${icon('arrow')}</button>`,'THE IDEA');$('about-access').onclick=accessibility;}
function accessibility(){openModal(`<h2 id="modal-title">Your studio. Your terms.</h2><h3>More ways to explore</h3><p>Use Tab to reach every control. Keys 1–5 play individual colors; Space toggles the soundscape when you are not editing a control. On the artwork, left and right arrows select a color; Enter plays it. The settings tabs also support arrow keys.</p><p>“Your experience” includes a still canvas, higher contrast, a text description and a labeled color score. Your device's reduced-motion preference is respected. Sound never starts automatically.</p><h3>Your images stay yours</h3><p>Imported images are decoded locally, reduced to five colors, then discarded. No image files are sent to a server. Google Fonts may be requested for typography; system fonts are the fallback. GitHub Pages serves the site and may log requests.</p><h3>Saving and sharing</h3><p>Up to 40 named compositions are saved in this browser's local storage, not in a cloud account. Clearing browser data removes them. Export project JSON files for a portable backup. Shared links contain colors and settings in the URL fragment, not the source image. Anyone you give the link to can reproduce that composition.</p><h3>Sound & narration</h3><p>Start at a comfortable volume. The Web Audio API is required for sound and WAV exports. Read-aloud depends on browser speech support and available voices; a browser may use its own speech service. The text description is always available.</p><button class="primary-button" id="open-experience">Customize my experience ${icon('sliders')}</button>`,'ACCESSIBILITY & PRIVACY');$('open-experience').onclick=()=>{closeModal();showView('studio');tab('experience');$('experience-tab').focus();$('studio').scrollIntoView({block:'start'});};}
$('how-button').onclick=how;$('nav-about').onclick=about;$('manifesto-button').onclick=about;$('footer-access').onclick=accessibility;
$('read-button').onclick=()=>{if(!('speechSynthesis'in window)){toast('Read-aloud is not supported here. The full description is available as text.');return;}if(speechActive){speechSynthesis.cancel();speechActive=false;$('read-button').innerHTML=icon('volume')+' Read aloud';return;}if(playing)stopAudio();const speech=new SpeechSynthesisUtterance(description());speech.rate=.88;speech.lang='en-US';speech.onend=speech.onerror=()=>{speechActive=false;$('read-button').innerHTML=icon('volume')+' Read aloud';};speechSynthesis.cancel();speechSynthesis.speak(speech);speechActive=true;$('read-button').innerHTML=icon('pause')+' Stop reading';};
$('reset-button').onclick=()=>{openModal(`<h2 id="modal-title">A fresh start?</h2><p>Restore Amber tides and its starting settings. Saved pieces in your collection will not be affected. Unsaved changes to this canvas will be replaced.</p><div class="modal-actions"><button class="primary-button" id="confirm-reset">Reset the canvas</button><button class="secondary-button" id="cancel-reset">Keep creating</button></div>`);$('confirm-reset').onclick=()=>{stopAudio();closeModal();loadPreset(0);};$('cancel-reset').onclick=closeModal;};
function showView(view){collectionVisible=view==='collection';$('studio-view').hidden=collectionVisible;$('collection-view').hidden=!collectionVisible;$('nav-studio').classList.toggle('active',!collectionVisible);$('nav-collection').classList.toggle('active',collectionVisible);$('nav-studio').removeAttribute('aria-current');$('nav-collection').removeAttribute('aria-current');$(collectionVisible?'nav-collection':'nav-studio').setAttribute('aria-current','page');if(collectionVisible){if(playing)stopAudio();renderCollection();}else{resize();dirty=true;}window.scrollTo({top:0,behavior:'instant'});}
$('nav-studio').onclick=()=>showView('studio');$('nav-collection').onclick=()=>showView('collection');$$('.brand').forEach(a=>a.onclick=e=>{e.preventDefault();showView('studio');});$('collection-create').onclick=$('empty-create').onclick=()=>showView('studio');
function storeCollection(updated){try{localStorage.setItem(STORAGE,JSON.stringify(updated));collection=updated;updateCount();return true;}catch{toast('Browser storage is full or unavailable. Download a project file to keep your work.');return false;}}
$('save-button').onclick=()=>{if(collection.length>=40){toast('Your collection has 40 pieces. Export a backup, then remove a piece to make space.');return;}openModal(`<h2 id="modal-title">Give this feeling a name.</h2><p>Your artwork, palette and sound settings will be saved together in this browser.</p><form id="save-form"><label class="modal-field" for="save-title">Artwork name</label><input class="text-input" id="save-title" maxlength="70" required value="${esc(state.title)}" autocomplete="off"><div class="modal-actions"><button type="submit" class="primary-button">Save my creation ${icon('bookmark')}</button><button type="button" id="cancel-save" class="secondary-button">Keep editing</button></div></form><p class="dialog-note">Local storage is not a backup. Export a project file to keep a portable copy.</p>`,'A PLACE IN YOUR COLLECTION');$('save-title').focus();$('save-title').select();$('cancel-save').onclick=closeModal;$('save-form').onsubmit=e=>{e.preventDefault();const title=$('save-title').value.trim();if(!title){$('save-title').setCustomValidity('Give your artwork a name.');$('save-title').reportValidity();return;}const saved={...state,colors:[...state.colors],title,savedId:crypto.randomUUID?crypto.randomUUID():Date.now().toString(36),savedAt:new Date().toISOString()};if(storeCollection([saved,...collection])){state.title=title;needsSave=false;$('art-title').textContent=title;$('save-status').textContent='Saved in your collection.';persistDraft();updateDescription();closeModal();toast(`“${title}” is safely in this browser's collection.`);}};$('save-title').oninput=e=>e.target.setCustomValidity('');};
function renderCollection(){updateCount();$('empty-collection').hidden=collection.length>0;$('collection-grid').hidden=!collection.length;$('collection-grid').innerHTML=collection.map((s,i)=>`<article class="saved-card"><button class="preset-card" data-open="${i}" aria-label="Open ${esc(s.title)}"><div class="preset-art"><canvas id="saved-${i}" width="600" height="420" aria-hidden="true"></canvas><span class="preset-use">${icon('arrow')}</span></div></button><div class="saved-meta"><h3>${esc(s.title)}</h3><p>${esc(s.form)} · ${esc(s.instrument)} · ${Number(s.tempo)} BPM</p><div class="saved-actions"><button data-open="${i}">Open in studio ↗</button><button data-backup="${i}">Export project</button><button class="delete-saved" data-delete="${i}" aria-label="Delete ${esc(s.title)}">Remove</button></div></div></article>`).join('');collection.forEach((s,i)=>drawArtwork($('saved-'+i),sanitize(s),0,.8));$$('[data-open]').forEach(b=>b.onclick=()=>{state=sanitize(collection[Number(b.dataset.open)]);sync();persistDraft();showView('studio');$('save-status').textContent='Opened from your collection.';toast('Your saved world, ready to explore.');});$$('[data-backup]').forEach(b=>b.onclick=()=>exportProject(sanitize(collection[Number(b.dataset.backup)])));$$('[data-delete]').forEach(b=>b.onclick=()=>{const index=Number(b.dataset.delete),s=collection[index];openModal(`<h2 id="modal-title">Remove this creation?</h2><p>“${esc(s.title)}” will be removed from this browser. Export its project first if you want a backup.</p><div class="modal-actions"><button class="primary-button danger-button" id="confirm-delete">Remove creation</button><button class="secondary-button" id="cancel-delete">Keep it</button></div>`);$('cancel-delete').onclick=closeModal;$('confirm-delete').onclick=()=>{if(storeCollection(collection.filter((_,i)=>i!==index))){closeModal();renderCollection();toast('Creation removed.');}};});}
function filename(s=state){return (s.title.toLowerCase().replace(/[^a-z0-9]+/g,'-').slice(0,55)||'spectra')+'-spectra';}
function download(blob,name){const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),30000);}
function exportProject(s=state){download(new Blob([JSON.stringify({format:'spectra-project',version:1,...s,description:description(s)},null,2)],{type:'application/json'}),filename(s)+'.json');toast('Project exported. Import it later from My collection.');}
$('project-import-button').onclick=()=>$('project-input').click();$('project-input').onchange=async e=>{const file=e.target.files[0];e.target.value='';if(!file)return;if(file.size>100000){toast('Project files must be smaller than 100 KB.');return;}try{const data=JSON.parse(await file.text());if(data.format!=='spectra-project'||data.version!==1)throw new Error();state=sanitize(data);sync();persistDraft();showView('studio');toast('Project imported. Save it to add it to your collection.');}catch{toast('That file is not a supported SPECTRA project. Choose an exported .json file.');}};
$('share-button').onclick=()=>{const encoded=btoa(unescape(encodeURIComponent(JSON.stringify(sanitize(state))))).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'');const url=location.origin+location.pathname+'#s='+encoded;openModal(`<h2 id="modal-title">Pass the feeling on.</h2><p>This link recreates your palette, shape and sound. It contains no imported image. The recipient can remix their own version.</p><label class="modal-field" for="share-url">Your composition link</label><input class="text-input share-link" id="share-url" readonly value="${esc(url)}"><button class="primary-button" id="copy-link">Copy link ${icon('link')}</button><p class="dialog-note">If copying is blocked, select the link above and copy it manually.</p>`,'MADE TO BE SHARED');$('copy-link').onclick=async()=>{try{await navigator.clipboard.writeText(url);$('copy-link').innerHTML='Copied '+icon('check');toast('Link copied. Your composition is ready to travel.');}catch{$('share-url').focus();$('share-url').select();toast('Link selected. Use your device’s Copy command.');}};};
$('export-button').onclick=()=>{openModal(`<h2 id="modal-title">Take a little art with you.</h2><p>Your creation, in a format that feels right.</p><div class="export-options"><button class="export-option" id="download-png">${icon('eye')}<span><strong>Artwork print</strong><small>2000 × 1600 pixels, with your title</small></span><span class="file-tag">PNG</span></button><button class="export-option" id="download-wav">${icon('headphones')}<span><strong>Soundscape</strong><small>16 seconds of your composition · stereo</small></span><span class="file-tag">WAV</span></button><button class="export-option" id="download-score">${icon('sliders')}<span><strong>Accessible visual score</strong><small>Labeled colors, notes and a text description</small></span><span class="file-tag">SVG</span></button><button class="export-option" id="download-project">${icon('bookmark')}<span><strong>Reusable project</strong><small>All your settings, ready to open again</small></span><span class="file-tag">JSON</span></button></div><p class="dialog-note">Export only images and artwork you have the right to use. Source images are never included in exports.</p>`,'YOURS TO KEEP');$('download-png').onclick=exportPng;$('download-wav').onclick=exportWav;$('download-score').onclick=exportScore;$('download-project').onclick=()=>exportProject();};
async function exportPng(){const button=$('download-png');button.disabled=true;button.querySelector('strong').textContent='Rendering your print…';await new Promise(r=>setTimeout(r,30));try{const out=document.createElement('canvas');out.width=2000;out.height=1600;drawArtwork(out,state,phase,1.8);const c=out.getContext('2d');c.fillStyle='#f6efdf';c.font='60px Georgia';c.fillText(state.title,100,1450,1760);c.font='18px sans-serif';c.fillStyle='#adbdab';c.fillText('S P E C T R A   /   '+state.form.toUpperCase()+'   /   '+state.tempo+' BPM',104,1504);const blob=await new Promise(r=>out.toBlob(r,'image/png'));if(!blob)throw new Error();download(blob,filename()+'.png');toast('Your artwork is ready.');}catch{toast('The artwork could not be exported. Try again or save a project file.');}finally{button.disabled=false;button.querySelector('strong').textContent='Artwork print';}}
async function exportWav(){const Offline=window.OfflineAudioContext||window.webkitOfflineAudioContext;if(!Offline){toast('Audio export is not supported by this browser. Try Chrome, Edge, Firefox or Safari.');return;}const button=$('download-wav');button.disabled=true;button.querySelector('strong').textContent='Rendering 16 seconds of sound…';announce('Rendering your soundscape.');try{const seconds=16,sampleRate=44100,context=new Offline(2,seconds*sampleRate,sampleRate),gain=context.createGain();gain.gain.setValueAtTime(state.volume/100*.24,0);gain.gain.setValueAtTime(state.volume/100*.24,14);gain.gain.linearRampToValueAtTime(0,16);gain.connect(context.destination);const interval=60/state.tempo;let i=0;for(let t=0;t<14;t+=interval){const n=[0,1,2,3,4,3,2,1][i++%8];synth(context,gain,noteFor(state.colors[n]),t,state.instrument==='glass'?2.2:1.7,state.instrument);}const buffer=await context.startRendering(),length=buffer.length,channels=2,array=new ArrayBuffer(44+length*channels*2),view=new DataView(array),write=(offset,text)=>{for(let j=0;j<text.length;j++)view.setUint8(offset+j,text.charCodeAt(j));};write(0,'RIFF');view.setUint32(4,36+length*4,true);write(8,'WAVE');write(12,'fmt ');view.setUint32(16,16,true);view.setUint16(20,1,true);view.setUint16(22,2,true);view.setUint32(24,sampleRate,true);view.setUint32(28,sampleRate*4,true);view.setUint16(32,4,true);view.setUint16(34,16,true);write(36,'data');view.setUint32(40,length*4,true);const left=buffer.getChannelData(0),right=buffer.getChannelData(1);for(let j=0;j<length;j++){view.setInt16(44+j*4,Math.round(Math.max(-1,Math.min(1,left[j]))*32767),true);view.setInt16(46+j*4,Math.round(Math.max(-1,Math.min(1,right[j]))*32767),true);}download(new Blob([view],{type:'audio/wav'}),filename()+'.wav');toast(state.volume===0?'Exported a silent soundscape: your volume is set to 0%.':'Your 16-second soundscape is ready.');}catch{toast('Audio rendering failed. Try again, or export a reusable project.');}finally{button.disabled=false;button.querySelector('strong').textContent='Soundscape';}}
function exportScore(){const blocks=state.colors.map((color,i)=>{const n=noteFor(color);return `<g transform="translate(${55+i*172},180)"><rect width="150" height="190" rx="9" fill="${color}" stroke="#31382a"/><rect y="124" width="150" height="66" rx="8" fill="#fffdf6"/><text x="14" y="151" font-size="19" fill="#283024">${i+1}. ${n.name}</text><text x="14" y="175" font-size="13" fill="#283024">${color.toUpperCase()}</text><text y="220" font-size="14">${esc(n.word)}</text></g>`;}).join('');const words=description().split(' '),lines=[];let line='';for(const word of words){if((line+' '+word).length>98){lines.push(line);line=word;}else line+=(line?' ':'')+word;}if(line)lines.push(line);const height=500+lines.length*24;const svg=`<svg xmlns="http://www.w3.org/2000/svg" width="970" height="${height}" viewBox="0 0 970 ${height}" role="img" aria-labelledby="title desc"><title id="title">${esc(state.title)} — SPECTRA color score</title><desc id="desc">${esc(description())}</desc><rect width="970" height="${height}" fill="#f5f3ee"/><g font-family="system-ui,sans-serif" fill="#283024"><text x="55" y="65" font-size="15" letter-spacing="4">SPECTRA / COLOR SCORE</text><text x="55" y="123" font-size="34">${esc(state.title)}</text><text x="55" y="151" font-size="14">${state.tempo} BPM · ${esc(state.instrument)} · Play from left to right, then back.</text>${blocks}${lines.map((l,i)=>`<text x="55" y="${460+i*24}" font-size="15">${esc(l)}</text>`).join('')}</g></svg>`;download(new Blob([svg],{type:'image/svg+xml'}),filename()+'-score.svg');toast('Your labeled visual score is ready.');}
// Expose read-only diagnostic values for automated end-to-end verification.
window.Spectra=Object.freeze({getState:()=>JSON.parse(JSON.stringify(state)),noteFor,description,isPlaying:()=>playing,version:'1.0.0'});
sync();renderPresets();resize();requestAnimationFrame(animate);$('play-button').setAttribute('aria-pressed','false');if(sharedLoaded)setTimeout(()=>toast('A shared world, opened just for you. Make it your own.'),600);if(badShare)setTimeout(()=>toast('This shared link could not be read. Start fresh or import a project file.'),600);
})();
