/* Dependency-free Chrome DevTools integration tests; Node 22+. */
const {spawn}=require('node:child_process'),fs=require('node:fs'),assert=require('node:assert/strict'),crypto=require('node:crypto');
const {setTimeout:wait}=require('node:timers/promises');
const result={application:'SPECTRA',revision:process.env.GITHUB_SHA||'local',checkedAt:new Date().toISOString(),tests:[],live:{verified:false}};
(async()=>{
let ws,log='',launchError='';
const chrome=spawn('google-chrome',['--headless','--no-sandbox','--disable-gpu','--disable-dev-shm-usage','--no-proxy-server','--autoplay-policy=no-user-gesture-required','--disable-background-timer-throttling','--disable-renderer-backgrounding','--remote-debugging-port=9222','--window-size=1440,1050','--user-data-dir=/tmp/spectra-qa-'+process.pid,'about:blank'],{stdio:['ignore','pipe','pipe']});
chrome.stderr.on('data',d=>{log+=d.toString();});chrome.stdout.on('data',d=>{log+=d.toString();});chrome.on('error',e=>{launchError=e.message;});
try{
 let target,lastError='';for(let i=0;i<250;i++){try{target=await(await fetch('http://127.0.0.1:9222/json/new?about:blank',{method:'PUT',signal:AbortSignal.timeout(2000)})).json();if(target.webSocketDebuggerUrl)break;}catch(e){lastError=e.message;}await wait(120);}
 if(!target?.webSocketDebuggerUrl)throw Error('Chrome startup failed: '+launchError+' '+lastError+' '+log.slice(-5000));
 ws=new WebSocket(target.webSocketDebuggerUrl);await new Promise((r,j)=>{ws.onopen=r;ws.onerror=j;});let id=0;const pending=new Map(),errors=[];
 ws.onmessage=e=>{const m=JSON.parse(e.data);if(m.method==='Runtime.exceptionThrown')errors.push(m.params.exceptionDetails.exception?.description||m.params.exceptionDetails.text);if(pending.has(m.id)){const p=pending.get(m.id);pending.delete(m.id);m.error?p.j(Error(JSON.stringify(m.error))):p.r(m.result);}};
 function cdp(method,params={}){return new Promise((r,j)=>{const n=++id;pending.set(n,{r,j});ws.send(JSON.stringify({id:n,method,params}));setTimeout(()=>{if(pending.has(n)){pending.delete(n);j(Error('CDP timeout: '+method));}},20000).unref();});}
 async function js(source){const r=await cdp('Runtime.evaluate',{expression:'eval('+JSON.stringify(source)+')',returnByValue:true,awaitPromise:true,userGesture:true});if(r.exceptionDetails)throw Error(r.exceptionDetails.exception?.description||r.exceptionDetails.text);return r.result.value;}
 async function until(source,ms=12000){const t=Date.now();while(Date.now()-t<ms){try{if(await js(source))return;}catch{}await wait(100);}throw Error('Timeout: '+source);}
 const click=id=>js(`document.getElementById(${JSON.stringify(id)}).click()`);
 async function check(name,fn){try{await fn();result.tests.push({name,passed:true});console.log('PASS '+name);}catch(e){result.tests.push({name,passed:false,error:e.message});throw e;}}
 async function navigate(url){await cdp('Page.navigate',{url});await wait(300);if(url!=='about:blank')await until('!!window.Spectra');}
 await cdp('Page.enable');await cdp('Runtime.enable');await cdp('Browser.setDownloadBehavior',{behavior:'allow',downloadPath:'/tmp/spectra-downloads'});await cdp('Emulation.setDeviceMetricsOverride',{width:1440,height:1050,deviceScaleFactor:1,mobile:false});
 await navigate('http://127.0.0.1:8765/spectra/');
 await check('Studio initialization and original canvas rendering',async()=>{assert.equal(await js('Spectra.getState().title'),'Amber tides');assert.equal(await js('document.querySelectorAll("#palette input").length'),5);assert.equal(await js('document.querySelectorAll("[data-preset]").length'),4);const count=await js(`(()=>{const c=document.getElementById('art-canvas'),d=c.getContext('2d').getImageData(0,0,c.width,c.height).data,s=new Set();for(let i=0;i<d.length;i+=64)s.add(d[i]+','+d[i+1]+','+d[i+2]);return s.size;})()`);assert.ok(count>500,'Rich artwork rendered: '+count+' colors');});
 await check('Desktop, tablet, mobile and small-phone layouts',async()=>{for(const [name,width,height] of [['desktop',1440,1050],['tablet',768,1024],['mobile',390,844],['small-phone',320,568]]){await cdp('Emulation.setDeviceMetricsOverride',{width,height,deviceScaleFactor:1,mobile:width<700});await wait(250);assert.equal(await js('document.documentElement.scrollWidth<=innerWidth+1'),true,name+' must not overflow');assert.equal(await js('document.getElementById("art-canvas").width>0'),true);const shot=await cdp('Page.captureScreenshot',{format:'png',captureBeyondViewport:true});fs.writeFileSync('/tmp/spectra-'+name+'.png',Buffer.from(shot.data,'base64'));}await cdp('Emulation.setDeviceMetricsOverride',{width:1440,height:1050,deviceScaleFactor:1,mobile:false});});
 await check('Deterministic pentatonic color mapping',async()=>{const notes=await js('Spectra.getState().colors.map(c=>Spectra.noteFor(c))');for(const n of notes){assert.match(n.name,/^[CDEGA][34]$/);assert.ok(n.freq>100&&n.freq<500);}assert.deepEqual(await js('Spectra.noteFor("#ff0000")'),await js('Spectra.noteFor("#ff0000")'));});
 await check('Soundscape playback and pause',async()=>{await click('play-button');await until('Spectra.isPlaying()');await wait(950);assert.equal(await js('document.getElementById("play-label").textContent'),'Pause soundscape');await click('play-button');assert.equal(await js('Spectra.isPlaying()'),false);});
 await check('Keyboard color exploration',async()=>{await js('document.getElementById("art-canvas").focus()');await cdp('Input.dispatchKeyEvent',{type:'keyDown',key:'ArrowRight',code:'ArrowRight'});assert.match(await js('document.getElementById("a11y-status").textContent'),/Selected color/);await cdp('Input.dispatchKeyEvent',{type:'keyDown',key:'3',code:'Digit3',text:'3'});await wait(50);assert.match(await js('document.getElementById("a11y-status").textContent'),/Color 3/);});
 await check('Presets, shape, tempo, instrument and motion controls',async()=>{await js('document.querySelectorAll("[data-preset]")[1].click()');assert.equal(await js('Spectra.getState().title'),'Midnight bloom');await js(`document.querySelector('[data-form="orbit"]').click();const r=document.getElementById('tempo-range');r.value=96;r.dispatchEvent(new Event('input'));const s=document.getElementById('instrument-select');s.value='soft';s.dispatchEvent(new Event('change'));`);await click('motion-button');assert.equal(await js('Spectra.getState().tempo'),96);assert.equal(await js('Spectra.getState().form'),'orbit');assert.equal(await js('Spectra.getState().instrument'),'soft');assert.equal(await js('Spectra.getState().still'),true);});
 await check('Keyboard settings tabs, descriptions and high contrast',async()=>{await js('document.getElementById("create-tab").focus()');await cdp('Input.dispatchKeyEvent',{type:'keyDown',key:'ArrowRight',code:'ArrowRight'});assert.equal(await js('document.getElementById("experience-tab").getAttribute("aria-selected")'),'true');assert.equal(await js('document.querySelectorAll(".note-key").length'),5);assert.match(await js('document.getElementById("art-description").textContent'),/beats per minute/);await click('high-contrast');assert.equal(await js('document.body.classList.contains("high-contrast")'),true);await click('high-contrast');await click('create-tab');});
 await check('Private image palette extraction and invalid-file recovery',async()=>{await js(`(async()=>{const c=document.createElement('canvas');c.width=200;c.height=100;const x=c.getContext('2d');['#ee4433','#eebc66','#559988','#224466','#aa5599'].forEach((v,i)=>{x.fillStyle=v;x.fillRect(i*40,0,40,100);});const blob=await new Promise(r=>c.toBlob(r,'image/png'));const dt=new DataTransfer();dt.items.add(new File([blob],'owned-image.png',{type:'image/png'}));const el=document.getElementById('image-input');el.files=dt.files;el.dispatchEvent(new Event('change'));})()`);await until('Spectra.getState().title==="Colors from your world"');const before=await js('Spectra.getState().colors');assert.equal(before.length,5);await js(`const dt=new DataTransfer();dt.items.add(new File(['bad'],'bad.txt',{type:'text/plain'}));const el=document.getElementById('image-input');el.files=dt.files;el.dispatchEvent(new Event('change'));`);assert.deepEqual(await js('Spectra.getState().colors'),before);assert.match(await js('document.getElementById("toast").textContent'),/PNG, JPG or WebP/);});
 await check('Named collection persistence and reload',async()=>{await click('save-button');await js('document.getElementById("save-title").value="QA — A feeling worth keeping";document.getElementById("save-form").requestSubmit()');assert.equal(await js('document.getElementById("collection-count").textContent'),'1');await wait(400);await cdp('Page.reload');await wait(400);await until('!!window.Spectra');assert.equal(await js('document.getElementById("collection-count").textContent'),'1');await click('nav-collection');assert.equal(await js('document.querySelectorAll(".saved-card").length'),1);await js('document.querySelector("[data-open]").click()');assert.equal(await js('Spectra.getState().title'),'QA — A feeling worth keeping');});
 await check('Share links reproduce composition settings',async()=>{const before=await js('Spectra.getState()');await click('share-button');const url=await js('document.getElementById("share-url").value');assert.ok(url.includes('#s='));await click('modal-close');await navigate('about:blank');await navigate(url);const after=await js('Spectra.getState()');for(const k of ['title','colors','form','instrument','tempo','seed'])assert.deepEqual(after[k],before[k]);});
 await js(`window.__exports=[];const original=URL.createObjectURL.bind(URL);URL.createObjectURL=b=>{window.__exports.push(b);return original(b);};`);
 await click('export-button');
 await check('Reusable JSON project export',async()=>{await click('download-project');const d=await js('window.__exports.at(-1).text().then(JSON.parse)');assert.equal(d.format,'spectra-project');assert.equal(d.version,1);assert.equal(d.colors.length,5);});
 await check('Labeled SVG visual score export',async()=>{await click('download-score');const svg=await js('window.__exports.at(-1).text()');assert.match(svg,/<title id="title">/);assert.match(svg,/<desc id="desc">/);assert.match(svg,/SPECTRA \/ COLOR SCORE/);});
 await check('2000 × 1600 PNG artwork export',async()=>{const n=await js('window.__exports.length');await click('download-png');await until(`window.__exports.length>${n}`);const d=await js(`(async()=>{const b=await window.__exports.at(-1).arrayBuffer(),d=new DataView(b);return [d.getUint32(16),d.getUint32(20),b.byteLength];})()`);assert.deepEqual(d.slice(0,2),[2000,1600]);assert.ok(d[2]>10000);});
 await check('16-second stereo WAV with audible sample data',async()=>{const n=await js('window.__exports.length');await click('download-wav');await until(`window.__exports.length>${n}`,20000);const wav=await js(`(async()=>{const b=await window.__exports.at(-1).arrayBuffer(),d=new DataView(b);let max=0;for(let i=44;i<b.byteLength;i+=400)max=Math.max(max,Math.abs(d.getInt16(i,true)));return {length:b.byteLength,channels:d.getUint16(22,true),rate:d.getUint32(24,true),max};})()`);assert.equal(wav.channels,2);assert.equal(wav.rate,44100);assert.equal(wav.length,44+16*44100*4);assert.ok(wav.max>0);});
 await click('modal-close');
 await check('Project import and malformed-project recovery',async()=>{await click('nav-collection');await js(`const p={format:'spectra-project',version:1,...Spectra.getState(),title:'Imported proof',tempo:84};const dt=new DataTransfer();dt.items.add(new File([JSON.stringify(p)],'proof.json',{type:'application/json'}));const el=document.getElementById('project-input');el.files=dt.files;el.dispatchEvent(new Event('change'));`);await until('Spectra.getState().title==="Imported proof"');assert.equal(await js('Spectra.getState().tempo'),84);await click('nav-collection');await js(`const dt=new DataTransfer();dt.items.add(new File(['{}'],'bad.json',{type:'application/json'}));const el=document.getElementById('project-input');el.files=dt.files;el.dispatchEvent(new Event('change'));`);await wait(150);assert.match(await js('document.getElementById("toast").textContent'),/not a supported/);await click('nav-studio');});
 await check('Reset and deletion confirmation and cancellation',async()=>{await click('reset-button');await click('cancel-reset');assert.equal(await js('Spectra.getState().title'),'Imported proof');await click('nav-collection');await js('document.querySelector("[data-delete]").click()');await click('cancel-delete');assert.equal(await js('document.querySelectorAll(".saved-card").length'),1);await js('document.querySelector("[data-delete]").click()');await click('confirm-delete');assert.equal(await js('document.getElementById("empty-collection").hidden'),false);await click('nav-studio');});
 await check('Native modal focus and Escape dismissal',async()=>{await click('nav-about');assert.equal(await js('document.getElementById("modal").contains(document.activeElement)'),true);await cdp('Input.dispatchKeyEvent',{type:'keyDown',key:'Escape',code:'Escape'});await cdp('Input.dispatchKeyEvent',{type:'keyUp',key:'Escape',code:'Escape'});assert.equal(await js('document.getElementById("modal").open'),false);});
 await check('System reduced-motion preference',async()=>{await cdp('Emulation.setEmulatedMedia',{features:[{name:'prefers-reduced-motion',value:'reduce'}]});await navigate('http://127.0.0.1:8765/spectra/');assert.equal(await js('Spectra.getState().still'),true);assert.equal(await js('document.getElementById("canvas-mode").textContent'),'STILL ARTWORK');});
 await check('No uncaught JavaScript errors',async()=>assert.deepEqual(errors,[]));
 await check('Live Pages assets match the tested source exactly',async()=>{const base='https://sweemingxx.github.io/spectra/',files=['index.html','style.css','app.js'];let verified=false,last='';for(let attempt=0;attempt<36;attempt++){try{let matches=true;for(const file of files){const response=await fetch(base+file+'?verify='+result.revision,{signal:AbortSignal.timeout(15000),headers:{'Cache-Control':'no-cache'}});if(!response.ok)throw Error(file+' HTTP '+response.status);const remote=await response.text(),local=fs.readFileSync('spectra/'+file,'utf8');if(crypto.createHash('sha256').update(remote).digest('hex')!==crypto.createHash('sha256').update(local).digest('hex')){last=file+' revision pending';matches=false;break;}}if(matches){verified=true;break;}}catch(e){last=e.message;}await wait(10000);}assert.ok(verified,last);result.live={verified:true,url:base,verifiedAt:new Date().toISOString(),assets:files};});
 result.passed=true;console.log('::notice::SPECTRA_VERIFIED '+result.tests.length+' checks passed. '+result.live.url);
}catch(e){result.passed=false;result.error=e.message;console.error('::error::'+e.message.replaceAll('\n',' '));process.exitCode=1;}
finally{if(!result.tests.length)result.browserLog=log.slice(-6000);fs.writeFileSync('/tmp/spectra-verification.json',JSON.stringify(result,null,2));if(ws)ws.close();chrome.kill('SIGTERM');}
})();
