/* SPECTRA: dependency-free Chrome DevTools end-to-end tests. Node 22+. */
const {spawn}=require('node:child_process');
const fs=require('node:fs');
const {setTimeout:wait}=require('node:timers/promises');
const assert=require('node:assert/strict');
const crypto=require('node:crypto');
const results={application:'SPECTRA',revision:process.env.GITHUB_SHA||'local',checkedAt:new Date().toISOString(),tests:[],live:{verified:false}};
(async()=>{
const browser=spawn('google-chrome',['--headless=new','--no-sandbox','--disable-dev-shm-usage','--autoplay-policy=no-user-gesture-required','--disable-background-timer-throttling','--disable-renderer-backgrounding','--remote-debugging-port=9237','--window-size=1440,1050','--user-data-dir=/tmp/spectra-qa-'+process.pid,'about:blank'],{stdio:'ignore'});
let ws;const runtimeErrors=[];
try {
 let target;for(let i=0;i<100;i++){try{target=await(await fetch('http://127.0.0.1:9237/json/new?about:blank',{method:'PUT'})).json();break;}catch{await wait(100);}}
 if(!target)throw Error('The Chrome test browser did not start.');
 ws=new WebSocket(target.webSocketDebuggerUrl);await new Promise((resolve,reject)=>{ws.onopen=resolve;ws.onerror=reject;});
 let id=0;const pending=new Map();ws.onmessage=e=>{const m=JSON.parse(e.data);if(m.method==='Runtime.exceptionThrown')runtimeErrors.push(m.params.exceptionDetails.exception?.description||m.params.exceptionDetails.text);if(pending.has(m.id)){const p=pending.get(m.id);pending.delete(m.id);m.error?p.reject(Error(JSON.stringify(m.error))):p.resolve(m.result);}};
 function cdp(method,params={}){return new Promise((resolve,reject)=>{const n=++id;pending.set(n,{resolve,reject});ws.send(JSON.stringify({id:n,method,params}));setTimeout(()=>{if(pending.has(n)){pending.delete(n);reject(Error('CDP timeout: '+method));}},20000).unref();});}
 async function js(expression){const r=await cdp('Runtime.evaluate',{expression,returnByValue:true,awaitPromise:true,userGesture:true});if(r.exceptionDetails)throw Error(r.exceptionDetails.exception?.description||r.exceptionDetails.text);return r.result.value;}
 async function until(expression,timeout=12000){const start=Date.now();while(Date.now()-start<timeout){try{if(await js(expression))return;}catch{}await wait(100);}throw Error('Timed out waiting for: '+expression);}
 async function test(name,fn){try{await fn();results.tests.push({name,passed:true});console.log('PASS '+name);}catch(e){results.tests.push({name,passed:false,error:e.message});console.error('FAIL '+name+': '+e.message);throw e;}}
 await cdp('Page.enable');await cdp('Runtime.enable');await cdp('Browser.setDownloadBehavior',{behavior:'allow',downloadPath:'/tmp/spectra-downloads'});await cdp('Emulation.setDeviceMetricsOverride',{width:1440,height:1050,deviceScaleFactor:1,mobile:false});
 await cdp('Page.navigate',{url:'http://127.0.0.1:8765/spectra/'});await until('!!window.Spectra');
 await test('Studio initializes with original artwork and complete controls',async()=>{assert.equal(await js('Spectra.getState().title'),'Amber tides');assert.equal(await js('document.querySelectorAll("#palette input").length'),5);assert.equal(await js('document.querySelectorAll("[data-preset]").length'),4);assert.equal(await js('document.querySelector("#art-canvas").width>0'),true);assert.equal(await js('document.querySelector("#art-description").textContent.includes("beats per minute")'),true);});
 await test('Artwork contains rendered color rather than a blank canvas',async()=>{await wait(350);const unique=await js(`(()=>{const c=document.getElementById('art-canvas'),d=c.getContext('2d').getImageData(0,0,c.width,c.height).data,s=new Set();for(let i=0;i<d.length;i+=64)s.add(d[i]+','+d[i+1]+','+d[i+2]);return s.size;})()`);assert.ok(unique>500,'Expected rich original rendered artwork, found '+unique+' sampled colors');});
 await test('Color mapping is deterministic and has valid pentatonic pitches',async()=>{const notes=await js('Spectra.getState().colors.map(c=>Spectra.noteFor(c))');assert.equal(notes.length,5);for(const n of notes){assert.match(n.name,/^[CDEGA][34]$/);assert.ok(n.freq>100&&n.freq<500);}assert.deepEqual(await js('Spectra.noteFor("#ff0000")'),await js('Spectra.noteFor("#ff0000")'));});
 await test('Audio starts on request, changes notes, and pauses',async()=>{await js('document.getElementById("play-button").click()');await until('Spectra.isPlaying()');await wait(950);assert.equal(await js('document.getElementById("play-label").textContent'),'Pause soundscape');assert.equal(await js('document.getElementById("sound-meter").classList.contains("active")'),true);await js('document.getElementById("play-button").click()');assert.equal(await js('Spectra.isPlaying()'),false);});
 await test('Keyboard can select and play a canvas color',async()=>{await js('document.getElementById("art-canvas").focus()');await cdp('Input.dispatchKeyEvent',{type:'keyDown',key:'ArrowRight',code:'ArrowRight'});await cdp('Input.dispatchKeyEvent',{type:'keyUp',key:'ArrowRight',code:'ArrowRight'});assert.match(await js('document.getElementById("a11y-status").textContent'),/Selected color/);await cdp('Input.dispatchKeyEvent',{type:'keyDown',key:'3',code:'Digit3',text:'3'});await wait(50);assert.match(await js('document.getElementById("a11y-status").textContent'),/Color 3/);});
 await test('Presets, form, tempo, instrument and motion are editable',async()=>{await js('document.querySelector("[data-preset=\\"1\\"]").click()');assert.equal(await js('Spectra.getState().title'),'Midnight bloom');assert.equal(await js('Spectra.getState().form'),'bloom');await js(`document.querySelector('[data-form="orbit"]').click();const r=document.getElementById('tempo-range');r.value=96;r.dispatchEvent(new Event('input'));const s=document.getElementById('instrument-select');s.value='soft';s.dispatchEvent(new Event('change'));document.getElementById('motion-button').click();`);assert.equal(await js('Spectra.getState().tempo'),96);assert.equal(await js('Spectra.getState().instrument'),'soft');assert.equal(await js('Spectra.getState().still'),true);});
 await test('Experience tab supports keyboard navigation and text alternatives',async()=>{await js('document.getElementById("create-tab").focus()');await cdp('Input.dispatchKeyEvent',{type:'keyDown',key:'ArrowRight',code:'ArrowRight'});assert.equal(await js('document.getElementById("experience-tab").getAttribute("aria-selected")'),'true');assert.equal(await js('document.getElementById("experience-panel").hidden'),false);assert.equal(await js('document.querySelectorAll(".note-key").length'),5);await js('document.getElementById("high-contrast").click()');assert.equal(await js('document.body.classList.contains("high-contrast")'),true);await js('document.getElementById("high-contrast").click();document.getElementById("create-tab").click();');});
 await test('Image palette extraction works locally and invalid files are recoverable',async()=>{await js(`(async()=>{const c=document.createElement('canvas');c.width=200;c.height=100;const x=c.getContext('2d');['#ee4433','#eebc66','#559988','#224466','#aa5599'].forEach((v,i)=>{x.fillStyle=v;x.fillRect(i*40,0,40,100);});const blob=await new Promise(r=>c.toBlob(r,'image/png'));const dt=new DataTransfer();dt.items.add(new File([blob],'my-painting.png',{type:'image/png'}));const input=document.getElementById('image-input');input.files=dt.files;input.dispatchEvent(new Event('change'));})()`);await until('Spectra.getState().title==="Colors from your world"');assert.equal(await js('Spectra.getState().colors.length'),5);const before=await js('JSON.stringify(Spectra.getState().colors)');await js(`const dt=new DataTransfer();dt.items.add(new File(['bad'],'invalid.txt',{type:'text/plain'}));const el=document.getElementById('image-input');el.files=dt.files;el.dispatchEvent(new Event('change'));`);assert.equal(await js('JSON.stringify(Spectra.getState().colors)'),before);assert.match(await js('document.getElementById("toast").textContent'),/PNG, JPG or WebP/);});
 await test('Named collection saves and persists across a page reload',async()=>{await js('document.getElementById("save-button").click();document.getElementById("save-title").value="QA — A feeling worth keeping";document.getElementById("save-form").requestSubmit()');assert.equal(await js('document.getElementById("collection-count").textContent'),'1');await cdp('Page.reload');await until('!!window.Spectra');assert.equal(await js('document.getElementById("collection-count").textContent'),'1');await js('document.getElementById("nav-collection").click()');assert.equal(await js('document.querySelectorAll(".saved-card").length'),1);await js('document.querySelector("[data-open]").click()');assert.equal(await js('Spectra.getState().title'),'QA — A feeling worth keeping');});
 await test('Share link round-trips all core composition settings',async()=>{const before=await js('Spectra.getState()');await js('document.getElementById("share-button").click()');const url=await js('document.getElementById("share-url").value');assert.ok(url.includes('#s='));await cdp('Page.navigate',{url});await until('!!window.Spectra');const after=await js('Spectra.getState()');for(const k of ['title','colors','form','instrument','tempo','seed'])assert.deepEqual(after[k],before[k]);});
 await js(`window.__exports=[];const original=URL.createObjectURL.bind(URL);URL.createObjectURL=b=>{window.__exports.push(b);return original(b);};`);
 await test('Project export creates a valid reusable JSON composition',async()=>{await js('document.getElementById("export-button").click();document.getElementById("download-project").click()');const data=await js('window.__exports.at(-1).text().then(JSON.parse)');assert.equal(data.format,'spectra-project');assert.equal(data.version,1);assert.equal(data.colors.length,5);});
 await test('SVG export includes accessible labels, the score and description',async()=>{await js('document.getElementById("download-score").click()');const svg=await js('window.__exports.at(-1).text()');assert.match(svg,/<title id="title">/);assert.match(svg,/<desc id="desc">/);assert.match(svg,/SPECTRA \/ COLOR SCORE/);});
 await test('Artwork PNG export has the promised 2000 by 1600 dimensions',async()=>{const n=await js('window.__exports.length');await js('document.getElementById("download-png").click()');await until(`window.__exports.length>${n}`);const dimensions=await js(`(async()=>{const b=await window.__exports.at(-1).arrayBuffer();const d=new DataView(b);return [d.getUint32(16),d.getUint32(20),b.byteLength];})()`);assert.deepEqual(dimensions.slice(0,2),[2000,1600]);assert.ok(dimensions[2]>10000);});
 await test('WAV export is 16 seconds of stereo audio with nonzero samples',async()=>{const n=await js('window.__exports.length');await js('document.getElementById("download-wav").click()');await until(`window.__exports.length>${n}`,20000);const wav=await js(`(async()=>{const b=await window.__exports.at(-1).arrayBuffer(),d=new DataView(b);let max=0;for(let i=44;i<b.byteLength;i+=400)max=Math.max(max,Math.abs(d.getInt16(i,true)));return {length:b.byteLength,channels:d.getUint16(22,true),rate:d.getUint32(24,true),max};})()`);assert.equal(wav.channels,2);assert.equal(wav.rate,44100);assert.equal(wav.length,44+16*44100*4);assert.ok(wav.max>0);await js('document.getElementById("modal-close").click()');});
 await test('Project import restores a composition and rejects invalid JSON',async()=>{await js(`document.getElementById('nav-collection').click();const p={format:'spectra-project',version:1,...Spectra.getState(),title:'Imported proof',tempo:84};const dt=new DataTransfer();dt.items.add(new File([JSON.stringify(p)],'proof.json',{type:'application/json'}));const el=document.getElementById('project-input');el.files=dt.files;el.dispatchEvent(new Event('change'));`);await until('Spectra.getState().title==="Imported proof"');assert.equal(await js('Spectra.getState().tempo'),84);await js(`document.getElementById('nav-collection').click();const dt=new DataTransfer();dt.items.add(new File(['{}'],'bad.json',{type:'application/json'}));const el=document.getElementById('project-input');el.files=dt.files;el.dispatchEvent(new Event('change'));`);await wait(150);assert.match(await js('document.getElementById("toast").textContent'),/not a supported/);await js('document.getElementById("nav-studio").click()');});
 await test('Reset and removal require confirmation and can be cancelled',async()=>{await js('document.getElementById("reset-button").click();document.getElementById("cancel-reset").click()');assert.equal(await js('Spectra.getState().title'),'Imported proof');await js('document.getElementById("nav-collection").click();document.querySelector("[data-delete]").click();document.getElementById("cancel-delete").click()');assert.equal(await js('document.querySelectorAll(".saved-card").length'),1);await js('document.querySelector("[data-delete]").click();document.getElementById("confirm-delete").click()');assert.equal(await js('document.getElementById("empty-collection").hidden'),false);await js('document.getElementById("nav-studio").click()');});
 await test('Dialogs contain focus and close with Escape',async()=>{await js('document.getElementById("nav-about").click()');assert.equal(await js('document.getElementById("modal").open'),true);assert.equal(await js('document.getElementById("modal").contains(document.activeElement)'),true);await cdp('Input.dispatchKeyEvent',{type:'keyDown',key:'Escape',code:'Escape'});await cdp('Input.dispatchKeyEvent',{type:'keyUp',key:'Escape',code:'Escape'});assert.equal(await js('document.getElementById("modal").open'),false);});
 await test('Desktop and mobile layouts have no horizontal overflow',async()=>{await js('document.querySelector("[data-preset=\\"0\\"]").click();window.scrollTo(0,0)');for(const [name,width,height] of [['desktop',1440,1050],['tablet',768,1024],['mobile',390,844],['small-phone',320,568]]){await cdp('Emulation.setDeviceMetricsOverride',{width,height,deviceScaleFactor:1,mobile:width<700});await wait(200);const dims=await js('({body:document.documentElement.scrollWidth,viewport:innerWidth,canvas:document.getElementById("art-canvas").width})');assert.ok(dims.body<=dims.viewport+1,`${name}: ${dims.body}>${dims.viewport}`);assert.ok(dims.canvas>0);const screenshot=await cdp('Page.captureScreenshot',{format:'png',captureBeyondViewport:true});fs.writeFileSync('/tmp/spectra-'+name+'.png',Buffer.from(screenshot.data,'base64'));}});
 await test('Device reduced-motion preference is respected on first load',async()=>{await cdp('Emulation.setEmulatedMedia',{features:[{name:'prefers-reduced-motion',value:'reduce'}]});await cdp('Page.navigate',{url:'http://127.0.0.1:8765/spectra/'});await until('!!window.Spectra');assert.equal(await js('Spectra.getState().still'),true);assert.equal(await js('document.getElementById("canvas-mode").textContent'),'STILL ARTWORK');});
 await test('No uncaught browser runtime errors',async()=>assert.deepEqual(runtimeErrors,[]));
 const base='https://sweemingxx.github.io/spectra/';
 await test('Live GitHub Pages serves the exact tested HTML, CSS and JavaScript',async()=>{const files=['index.html','style.css','app.js'];let verified=false,last='';for(let attempt=0;attempt<36;attempt++){try{let matches=true;for(const file of files){const response=await fetch(base+file+'?verify='+results.revision,{signal:AbortSignal.timeout(15000),headers:{'Cache-Control':'no-cache'}});if(!response.ok)throw Error(file+': HTTP '+response.status);const remote=await response.text(),local=fs.readFileSync('spectra/'+file,'utf8');if(crypto.createHash('sha256').update(remote).digest('hex')!==crypto.createHash('sha256').update(local).digest('hex')){matches=false;last=file+' is not yet the tested revision';break;}}if(matches){verified=true;break;}}catch(e){last=e.message;}await wait(10000);}assert.ok(verified,'Pages publication not confirmed: '+last);results.live={verified:true,url:base,verifiedAt:new Date().toISOString(),assets:files};});
 results.passed=true;console.log('::notice::SPECTRA_VERIFIED '+results.tests.length+' checks passed; live at '+results.live.url);
}catch(e){results.passed=false;results.error=e.message;console.error('::error::'+e.message.replaceAll('\n',' '));process.exitCode=1;}
finally{fs.writeFileSync('/tmp/spectra-verification.json',JSON.stringify(results,null,2));if(ws)ws.close();browser.kill('SIGTERM');}
})();
