"use strict";
const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];
const reduced=matchMedia('(prefers-reduced-motion: reduce)');
const SUITS={classic:{name:'Classic Red & Blue',color:'#d32635',accent:'#ef3038',secondary:'#164b86',eye:'#e9f2fb',web:'#340d17',code:'001',class:'THE ORIGINAL',motto:'Great power. Greater responsibility.',lore:'A homemade beginning. An extraordinary legacy. Your friendly neighborhood original.',abilities:[['AGILITY',92],['WEB MASTERY',98]]},symbiote:{name:'Symbiote Black',color:'#141622',accent:'#b7adf4',secondary:'#111321',eye:'#f6f4ff',web:'#66718b',code:'002',class:'THE DARK WITHIN',motto:'More power. A greater price.',lore:'An alien bond that amplifies every instinct. The hardest battle is the one within.',abilities:[['RAW STRENGTH',99],['SYMBIOTE SURGE',96]]},miles:{name:'Miles Morales Suit',color:'#171b26',accent:'#ef354d',secondary:'#8e1c34',eye:'#f2e8ed',web:'#d32c43',code:'003',class:'BROOKLYN’S OWN',motto:'Be yourself. Be greater.',lore:'A new rhythm for a new generation. Brooklyn’s own brings bio-electric power to the skyline.',abilities:[['VENOM BLAST',97],['CAMOUFLAGE',95]]}};
const MODS={precision:'A clean shot. Maximum control. Built for the classic approach.',impact:'A concentrated web burst for high-impact, close-range control.',electric:'Bio-electric charge meets web technology. Give your shots a spark.',ricochet:'A clever angle goes a long way. Chain your shots across the action.'};
let currentSuit='classic',activeDialog=null,lastFocus=null,swingStart=0,threeView=null;
let targetX=0,targetY=0,currentX=0,currentY=0;
let loadout={suit:'classic',alias:'',mod:'precision',gadgets:['Spider-Drone','Sonic Burst']};
const knownGadgets=['Spider-Drone','Web Mine','Sonic Burst','Gravity Well'];
function sanitizeLoadout(v){if(!v||typeof v!=='object')return loadout;return {suit:Object.hasOwn(SUITS,v.suit)?v.suit:'classic',alias:typeof v.alias==='string'?v.alias.slice(0,24):'',mod:Object.hasOwn(MODS,v.mod)?v.mod:'precision',gadgets:Array.isArray(v.gadgets)?[...new Set(v.gadgets.filter(g=>knownGadgets.includes(g)))].slice(0,2):['Spider-Drone','Sonic Burst']};}
try{const stored=localStorage.getItem('spider-loadout-v1');if(stored)loadout=sanitizeLoadout(JSON.parse(stored));}catch{}
try{if(location.hash.startsWith('#loadout='))loadout=sanitizeLoadout(JSON.parse(decodeURIComponent(location.hash.slice(9))));}catch{}
function save(){try{localStorage.setItem('spider-loadout-v1',JSON.stringify(loadout));}catch{}}
let toastTimer;function toast(message){const t=$('.toast');t.textContent=message;t.classList.add('visible');clearTimeout(toastTimer);toastTimer=setTimeout(()=>t.classList.remove('visible'),3500);}
function selectSuit(key,notify=false){if(!Object.hasOwn(SUITS,key))return;currentSuit=key;loadout.suit=key;const s=SUITS[key];document.documentElement.style.setProperty('--accent',s.accent);$$('[data-suit]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.suit===key)));$('#suit-lore').textContent=s.lore;$('#suit-code').textContent='SUIT FILE / '+s.code;$('#suit-class').textContent=s.class;$('#suit-class').style.color=s.accent;$('#suit-name').textContent=s.motto;['one','two'].forEach((n,i)=>{$('#ability-'+n).textContent=s.abilities[i][0];$('#ability-'+n+'-value').textContent=s.abilities[i][1];$('#ability-'+n+'-bar').style.width=s.abilities[i][1]+'%';});$('#builder-suit').value=key;$('#mask-stage').setAttribute('aria-label','Interactive '+s.name+' Spider-Man mask. Move your pointer or drag to rotate. Arrow keys also rotate.');$('#symbiote-btn').innerHTML=key==='symbiote'?'<span>◈</span> Classic reveal':'<span>◈</span> Symbiote reveal';if(threeView)threeView.setSuit(key);drawPoster();save();if(notify)toast(s.name+' equipped');}
$$('[data-suit]').forEach(b=>b.addEventListener('click',()=>selectSuit(b.dataset.suit)));
$('.menu-toggle').addEventListener('click',function(){const open=$('#nav-links').classList.toggle('open');this.setAttribute('aria-expanded',open);this.setAttribute('aria-label',open?'Close navigation':'Open navigation');});
$$('.nav-links a').forEach(a=>a.addEventListener('click',()=>{$('#nav-links').classList.remove('open');$('.menu-toggle').setAttribute('aria-expanded','false');}));
$('.ticker-pause').addEventListener('click',function(){const paused=$('.ticker').classList.toggle('paused');this.textContent=paused?'▶':'Ⅱ';this.setAttribute('aria-pressed',paused);this.setAttribute('aria-label',paused?'Play news ticker':'Pause news ticker');});
if(reduced.matches){$('.ticker').classList.add('paused');$('.ticker-pause').disabled=true;$('.ticker-pause').setAttribute('aria-label','Ticker paused for reduced motion');}
function setBackgroundInert(value){$$('header,main,footer,.skip').forEach(el=>el.inert=value);}
function openDialog(id){if(activeDialog)closeDialog(false);lastFocus=document.activeElement;activeDialog=$('#'+id);$('#backdrop').classList.add('open');activeDialog.inert=false;activeDialog.classList.add('open');document.body.style.overflow='hidden';setBackgroundInert(true);requestAnimationFrame(()=>activeDialog&&$('button,input,a',activeDialog)?.focus());if(id==='builder')drawPoster();}
let teaserTimer=null;function closeDialog(restore=true){if(!activeDialog)return;clearInterval(teaserTimer);activeDialog.classList.remove('open');activeDialog.inert=true;activeDialog=null;$('#backdrop').classList.remove('open');document.body.style.overflow='';setBackgroundInert(false);if(restore&&lastFocus)lastFocus.focus();}
$$('[data-close]').forEach(b=>b.addEventListener('click',()=>closeDialog()));$('#backdrop').addEventListener('click',()=>closeDialog());
document.addEventListener('keydown',e=>{if(!activeDialog)return;if(e.key==='Escape'){e.preventDefault();closeDialog();}if(e.key==='Tab'){const items=$$('button:not(:disabled),a[href],input,select,[tabindex="0"]',activeDialog).filter(el=>el.offsetParent!==null);const first=items[0],last=items.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}}});
function info(kicker,html){$('#modal-kicker').textContent=kicker;$('#modal-content').innerHTML=html;openDialog('info-modal');}
const dossiers={heroes:{title:'The ones who rise.',tag:'DOSSIER / 001 — HEROES',intro:'The mask is a promise. These are the people who keep it.',people:[['Peter Parker','Queens-born. Science-minded. The original Spider-Man turns a life-changing bite into a lifelong promise to protect his city.'],['Miles Morales','Brooklyn’s Spider-Man. An artist and a hero with bio-electric venom powers, camouflage, and a style entirely his own.']]},villains:{title:'The darkness within.',tag:'DOSSIER / 002 — VILLAINS',intro:'Power without restraint. Obsession without an off switch.',people:[['Venom','An alien symbiote. A bond that blurs the line between enemy and antihero. Enormous strength comes with an appetite for chaos.'],['Green Goblin','Norman Osborn’s dangerous alter ego. A brilliant mind, a weaponized glider, and a deeply personal vendetta.']]},allies:{title:'The heart of the city.',tag:'DOSSIER / 003 — ALLIES',intro:'Not every kind of courage comes with a costume.',people:[['Mary Jane Watson','Fearless, independent, and never content to watch from the sidelines. MJ sees the person behind the mask.'],['Ganke Lee','Miles’s trusted friend and tech-minded partner. The voice in his ear when the city gets loud.']]}};
$$('[data-dossier]').forEach(b=>b.addEventListener('click',()=>{const d=dossiers[b.dataset.dossier];info(d.tag,'<h2 id="modal-title">'+d.title+'</h2><p>'+d.intro+'</p><ul class="modal-list">'+d.people.map(p=>'<li><strong>'+p[0]+'</strong><span>'+p[1]+'</span></li>').join('')+'</ul><p class="mono" style="font-size:8px">FAN-CONCEPT DOSSIER · CONTINUITIES MAY DIFFER</p>');}));
function openTickets(){info('YOUR NEXT BIG-SCREEN ADVENTURE','<h2 id="modal-title">See you at the movies.</h2><p class="ticket-disclaimer">This is an unofficial fan concept, not an announced film or ticket seller. No showtimes, prices, or seat availability are represented here.</p><p>Explore official Spider-Man movie information, or check a cinema booking service for real listings near you.</p><div class="ticket-options"><a href="https://www.sonypictures.com/movies" target="_blank" rel="noopener noreferrer">Sony Pictures movies <span>↗</span></a><a href="https://www.fandango.com/" target="_blank" rel="noopener noreferrer">Check Fandango <small>United States ↗</small></a><a href="https://www.gv.com.sg/" target="_blank" rel="noopener noreferrer">Check Golden Village <small>Singapore ↗</small></a></div>');}
function openTeaser(){info('AN ORIGINAL MOTION TEASER / FAN CONCEPT','<h2 id="modal-title">Every city needs a hero.</h2><div class="trailer-stage"><div class="trailer-type"><small>NEW YORK. AFTER DARK.</small><span id="teaser-line">THE CITY<br>NEVER SLEEPS.</span></div><div class="trailer-progress" id="teaser-progress"></div></div><p>A short, silent motion study made for this experience. Not an official Marvel or Sony trailer.</p><button class="primary-btn" id="replay-teaser">↻ Replay teaser</button>');$('#replay-teaser').addEventListener('click',playTeaser);playTeaser();}
function playTeaser(){clearInterval(teaserTimer);const phrases=['THE CITY<br>NEVER SLEEPS.','NEITHER DO<br>ITS HEROES.','ANYONE CAN<br>WEAR THE MASK.','BE<br><span class="red">GREATER.</span>'];const start=performance.now();const tick=()=>{const f=Math.min((performance.now()-start)/12000,1);const line=$('#teaser-line');if(!line)return;line.innerHTML=phrases[Math.min(3,Math.floor(f*4))];$('#teaser-progress').style.width=f*100+'%';if(f>=1)clearInterval(teaserTimer);};tick();teaserTimer=setInterval(tick,reduced.matches?1000:100);}
$$('[data-open]').forEach(b=>b.addEventListener('click',()=>{const kind=b.dataset.open;if(kind==='builder')openDialog('builder');else if(kind==='tickets')openTickets();else openTeaser();}));
$('#hero-alias').value=loadout.alias;$('#web-mod').value=loadout.mod;$$('.mod-option input').forEach(e=>e.checked=loadout.gadgets.includes(e.value));
function updateBuilder(){loadout.alias=$('#hero-alias').value.slice(0,24);loadout.mod=$('#web-mod').value;loadout.gadgets=$$('.mod-option input:checked').map(e=>e.value);$('#mod-description').textContent=MODS[loadout.mod];$('#gadget-count').textContent=loadout.gadgets.length+' / 2 gadget slots equipped';save();drawPoster();}
$('#hero-alias').addEventListener('input',updateBuilder);$('#web-mod').addEventListener('change',updateBuilder);$('#builder-suit').addEventListener('change',e=>selectSuit(e.target.value));
$$('.mod-option input').forEach(el=>el.addEventListener('change',()=>{if($$('.mod-option input:checked').length>2){el.checked=false;toast('Two gadget slots available. Unequip one to swap.');}updateBuilder();}));
$('#export-poster').addEventListener('click',()=>{drawPoster();$('#poster').toBlob(blob=>{if(!blob){toast('Could not export. Please try again.');return;}downloadBlob(blob,'your-ultimate-spider-man.png');toast('Your 900 × 1200 poster is ready.');},'image/png');});
function downloadBlob(blob,name){const u=URL.createObjectURL(blob),a=document.createElement('a');a.href=u;a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(u),10000);}
$('#share-loadout').addEventListener('click',async()=>{const url=location.href.split('#')[0]+'#loadout='+encodeURIComponent(JSON.stringify(loadout));if(location.protocol==='file:'){const blob=await new Promise(r=>$('#poster').toBlob(r,'image/png'));if(!blob){toast('Please use Download poster to share your hero.');return;}const file=new File([blob],'your-ultimate-spider-man.png',{type:'image/png'});try{if(navigator.canShare?.({files:[file]})){await navigator.share({files:[file],title:'Your Ultimate Spider-Man'});return;}}catch(e){if(e.name==='AbortError')return;}downloadBlob(blob,file.name);toast('Poster downloaded — send the PNG to share your hero.');return;}try{if(navigator.share){await navigator.share({title:'Your Ultimate Spider-Man',text:'My suit. My gadgets. My kind of hero.',url});}else{await navigator.clipboard.writeText(url);toast('Loadout link copied. Anyone with it can explore your build.');}}catch(e){if(e.name==='AbortError')return;const field=document.createElement('textarea');field.value=url;field.setAttribute('aria-label','Shareable loadout link');field.style.cssText='width:100%;height:85px;margin-top:14px;background:#090c12;color:white;border:1px solid #586073;padding:10px';$('.share-note').after(field);field.focus();field.select();toast('Copy the selected link to share your loadout.');}});
// All artwork is generated locally; no image services or copyrighted film stills are used.
function seeded(seed){return()=>{seed=(seed*1664525+1013904223)>>>0;return seed/4294967296;};}
function pathHead(ctx){ctx.beginPath();ctx.moveTo(0,-1.48);ctx.bezierCurveTo(-.79,-1.51,-1.14,-1.05,-1.1,-.35);ctx.bezierCurveTo(-1.08,.3,-.84,.89,-.5,1.23);ctx.bezierCurveTo(-.19,1.52,.19,1.52,.5,1.23);ctx.bezierCurveTo(.84,.89,1.08,.3,1.1,-.35);ctx.bezierCurveTo(1.14,-1.05,.79,-1.51,0,-1.48);ctx.closePath();}
function lensPath(c){c.beginPath();c.moveTo(.145,-.29);c.bezierCurveTo(.36,-.30,.75,-.51,.985,-.77);c.bezierCurveTo(.985,-.14,.89,.16,.66,.27);c.bezierCurveTo(.41,.39,.26,.21,.145,-.29);c.closePath();}
function drawMask(ctx,cx,cy,scale,key,turn=0,venom=false){const suit=SUITS[key];ctx.save();ctx.translate(cx,cy);ctx.rotate(turn*.06);ctx.scale(scale*(1-Math.abs(turn)*.04),scale);ctx.transform(1,0,turn*.09,1,0,0);ctx.shadowColor=key==='classic'?'#d52b3a88':key==='miles'?'#f1325488':'#7984bb77';ctx.shadowBlur=scale*.15;pathHead(ctx);ctx.fillStyle=suit.color;ctx.fill();ctx.shadowBlur=0;ctx.save();pathHead(ctx);ctx.clip();let g=ctx.createLinearGradient(-1.1,-.2,1.1,.4);if(key==='classic'){g.addColorStop(0,'#200a16');g.addColorStop(.17,'#9c1329');g.addColorStop(.42,'#dc3541');g.addColorStop(.58,'#b42031');g.addColorStop(.83,'#510e1d');g.addColorStop(1,'#113853');}else{g.addColorStop(0,'#090d17');g.addColorStop(.3,key==='miles'?'#30333e':'#434251');g.addColorStop(.5,'#151823');g.addColorStop(.82,'#080b14');g.addColorStop(1,'#293956');}ctx.fillStyle=g;ctx.fillRect(-1.2,-1.6,2.4,3.2);
// Woven fabric highlights and curved web geometry.
ctx.fillStyle=key==='classic'?'#ffd4c115':'#cfdef315';for(let y=-1.5;y<1.5;y+=.034)for(let x=-1.1;x<1.15;x+=.029){ctx.fillRect(x+((Math.round(y/.034)%2)*.014),y,.008,.012);}
ctx.strokeStyle=suit.web;ctx.lineWidth=key==='classic'?.017:.011;ctx.globalAlpha=key==='symbiote'?.27:.82;const ox=turn*.07,oy=-.32;for(let i=0;i<18;i++){let a=i*Math.PI/9;ctx.beginPath();ctx.moveTo(ox,oy);ctx.quadraticCurveTo(ox+Math.cos(a)*.75,oy+Math.sin(a)*.95,ox+Math.cos(a)*2,oy+Math.sin(a)*2.5);ctx.stroke();}for(let ring=1;ring<9;ring++){const rr=ring*.23;ctx.beginPath();for(let j=0;j<=18;j++){const a=j*Math.PI/9;const x=ox+Math.cos(a)*rr,y=oy+Math.sin(a)*rr*1.13;if(j===0)ctx.moveTo(x,y);else{const m=a-Math.PI/18;ctx.quadraticCurveTo(ox+Math.cos(m)*rr*.93,oy+Math.sin(m)*rr*1.13*.93,x,y);}}ctx.stroke();}
ctx.globalAlpha=1;g=ctx.createRadialGradient(-.36,-.86,.04,-.22,-.3,1.7);g.addColorStop(0,'#ffbda922');g.addColorStop(.48,'#00000000');g.addColorStop(1,'#000000cf');ctx.fillStyle=g;ctx.fillRect(-1.2,-1.6,2.4,3.2);g=ctx.createLinearGradient(-1.1,0,1.1,0);g.addColorStop(0,'#ef7e4522');g.addColorStop(.12,'#00000000');g.addColorStop(.88,'#00000000');g.addColorStop(1,'#7db6ffb5');ctx.fillStyle=g;ctx.fillRect(-1.2,-1.6,2.4,3.2);
ctx.strokeStyle='#090c1660';ctx.lineWidth=.014;ctx.beginPath();ctx.moveTo(-.08,.07);ctx.quadraticCurveTo(-.1,.3,-.18,.47);ctx.quadraticCurveTo(0,.56,.18,.47);ctx.stroke();ctx.restore();
for(const side of [-1,1]){ctx.save();ctx.scale(side,1);if(venom){ctx.scale(1.06,1.13);ctx.translate(-.02,-.11);}lensPath(ctx);ctx.lineJoin='round';ctx.strokeStyle=key==='miles'?'#ed334c':'#060c14';ctx.lineWidth=venom?.05:.145;ctx.stroke();let eye=ctx.createLinearGradient(.25,-.6,.85,.28);eye.addColorStop(0,'#ffffff');eye.addColorStop(.55,suit.eye);eye.addColorStop(1,'#7693ae');ctx.fillStyle=eye;ctx.fill();ctx.save();lensPath(ctx);ctx.clip();ctx.strokeStyle='#53657720';ctx.lineWidth=.0035;for(let x=.1;x<1.1;x+=.022){ctx.beginPath();ctx.moveTo(x,-.8);ctx.lineTo(x+.3,.5);ctx.stroke();}ctx.restore();ctx.restore();}
if(venom){ctx.beginPath();ctx.moveTo(-.79,.35);ctx.bezierCurveTo(-.62,1.06,.62,1.06,.79,.35);ctx.quadraticCurveTo(0,.89,-.79,.35);ctx.fillStyle='#020207';ctx.fill();for(let i=0;i<12;i++){let x=-.69+i*.125,y=.56+.22*(1-Math.abs(x));ctx.beginPath();ctx.moveTo(x,y-.08);ctx.lineTo(x+.058,y+.15+(i%2)*.06);ctx.lineTo(x+.103,y-.05);ctx.fillStyle='#d9e5dc';ctx.fill();ctx.beginPath();ctx.moveTo(x,y+.23);ctx.lineTo(x+.06,y+.04);ctx.lineTo(x+.11,y+.21);ctx.fill();}ctx.beginPath();ctx.moveTo(.05,.84);ctx.bezierCurveTo(.75,.91,.65,1.35,.07,1.61);ctx.bezierCurveTo(.48,1.12,.12,1.05,-.08,.97);ctx.fillStyle='#9c324e';ctx.fill();}
// Wet surface glints.
ctx.save();pathHead(ctx);ctx.clip();const rnd=seeded(57);for(let i=0;i<62;i++){const x=rnd()*2.2-1.1,y=rnd()*3-1.5;ctx.fillStyle='rgba(220,231,255,'+(rnd()*.23)+')';ctx.beginPath();ctx.ellipse(x,y,.004,.009+rnd()*.023,.16,0,Math.PI*2);ctx.fill();}ctx.restore();ctx.restore();}
function drawSpider(c,x,y,s,color){c.save();c.translate(x,y);c.scale(s,s);c.fillStyle=color;c.beginPath();c.ellipse(0,0,.12,.25,0,0,Math.PI*2);c.fill();c.beginPath();c.ellipse(0,-.24,.09,.09,0,0,Math.PI*2);c.fill();c.strokeStyle=color;c.lineWidth=.045;c.lineJoin='miter';for(const sign of [-1,1])for(let i=0;i<4;i++){c.beginPath();c.moveTo(sign*.08,-.18+i*.11);c.lineTo(sign*(.3+i*.026),-.4+i*.26);c.lineTo(sign*(.34+i*.055),-.9+i*.58);c.stroke();}c.restore();}
function paintCity(c,w,h,seed=31,alpha=1){const rnd=seeded(seed);c.save();c.globalAlpha=alpha;for(let layer=0;layer<3;layer++){let x=-15;while(x<w+20){let bw=22+rnd()*55,bh=h*(.08+rnd()*(.35+layer*.06)),y=h-bh;c.fillStyle=['#17202d','#111722','#0a1019'][layer];c.fillRect(x,y,bw,bh);if(rnd()>.77){c.fillRect(x+bw*.3,y-9,bw*.4,9);c.fillRect(x+bw*.48,y-34,1,25);}for(let wy=y+9;wy<h-7;wy+=10)for(let wx=x+5;wx<x+bw-4;wx+=8){if(rnd()>.58){c.fillStyle=rnd()>.38?'rgba(214,164,91,'+(.12+rnd()*.4)+')':'rgba(131,178,216,'+(.08+rnd()*.35)+')';c.fillRect(wx,wy,2,3);}}x+=bw+3+rnd()*10;}}c.restore();}
function makePortrait(type){const c=document.createElement('canvas');c.width=780;c.height=860;const ctx=c.getContext('2d');let g=ctx.createLinearGradient(0,0,780,860);const color=type==='heroes'?'#783037':type==='villains'?'#303752':'#a26b43';g.addColorStop(0,color);g.addColorStop(1,'#111622');ctx.fillStyle=g;ctx.fillRect(0,0,780,860);paintCity(ctx,780,700,41,.6);const rnd=seeded(42);for(let i=0;i<40;i++){ctx.fillStyle='rgba(245,191,118,'+rnd()*.3+')';ctx.beginPath();ctx.arc(rnd()*780,rnd()*860,1+rnd()*4,0,7);ctx.fill();}
if(type==='heroes'||type==='villains'){const venom=type==='villains';ctx.save();ctx.translate(390,490);ctx.rotate(venom?-.08:.12);let torso=ctx.createLinearGradient(-320,0,350,250);torso.addColorStop(0,venom?'#1f293c':'#172d50');torso.addColorStop(.5,venom?'#080c18':'#972430');torso.addColorStop(1,'#07101d');ctx.fillStyle=torso;ctx.beginPath();ctx.moveTo(-85,-80);ctx.bezierCurveTo(-120,60,-300,-40,-350,190);ctx.lineTo(-390,460);ctx.lineTo(390,460);ctx.lineTo(340,175);ctx.bezierCurveTo(300,20,150,35,85,-80);ctx.fill();drawSpider(ctx,0,188,venom?157:100,venom?'#c7cddd':'#090d16');ctx.restore();drawMask(ctx,390,303,176,venom?'symbiote':'classic',venom?-.7:.6,venom);if(venom){ctx.strokeStyle='#93a1cc29';ctx.lineWidth=5;for(let j=0;j<8;j++){ctx.beginPath();ctx.moveTo(390,520);ctx.bezierCurveTo(280+j*20,380,100+j*80,800,50+j*100,780);ctx.stroke();}}}
else{ctx.save();ctx.translate(400,300);ctx.rotate(-.09);let hair=ctx.createLinearGradient(-200,0,190,200);hair.addColorStop(0,'#30151a');hair.addColorStop(.4,'#9e482c');hair.addColorStop(.7,'#5c2420');hair.addColorStop(1,'#dc8d52');ctx.fillStyle=hair;ctx.beginPath();ctx.moveTo(-145,-90);ctx.bezierCurveTo(-190,-267,169,-259,188,-70);ctx.bezierCurveTo(195,30,140,85,235,299);ctx.lineTo(-247,300);ctx.bezierCurveTo(-153,163,-207,13,-145,-90);ctx.fill();ctx.fillStyle='#996448';ctx.beginPath();ctx.moveTo(-47,112);ctx.lineTo(-49,214);ctx.lineTo(70,234);ctx.lineTo(58,102);ctx.fill();let skin=ctx.createLinearGradient(-130,-65,130,80);skin.addColorStop(0,'#815044');skin.addColorStop(.4,'#d39b79');skin.addColorStop(.85,'#efc39a');skin.addColorStop(1,'#c38b6e');ctx.fillStyle=skin;ctx.beginPath();ctx.moveTo(-117,-73);ctx.bezierCurveTo(-112,-187,135,-184,136,-54);ctx.bezierCurveTo(132,68,78,142,8,151);ctx.bezierCurveTo(-72,141,-125,64,-117,-73);ctx.fill();ctx.fillStyle='#211e27';ctx.beginPath();ctx.moveTo(-50,175);ctx.lineTo(16,259);ctx.lineTo(75,178);ctx.bezierCurveTo(263,209,300,303,334,510);ctx.lineTo(-352,510);ctx.bezierCurveTo(-313,294,-231,213,-50,175);ctx.fill();ctx.fillStyle='#343845';ctx.beginPath();ctx.moveTo(-51,177);ctx.lineTo(-115,219);ctx.lineTo(-72,290);ctx.lineTo(-29,252);ctx.lineTo(13,405);ctx.closePath();ctx.fill();ctx.beginPath();ctx.moveTo(75,176);ctx.lineTo(126,225);ctx.lineTo(81,302);ctx.lineTo(35,251);ctx.lineTo(13,405);ctx.closePath();ctx.fill();ctx.strokeStyle='#6a493e';ctx.lineWidth=7;ctx.lineCap='round';ctx.beginPath();ctx.moveTo(-85,-21);ctx.quadraticCurveTo(-56,-34,-27,-19);ctx.moveTo(38,-20);ctx.quadraticCurveTo(68,-35,97,-18);ctx.stroke();for(const x of [-55,68]){ctx.fillStyle='#e8ddc9';ctx.beginPath();ctx.ellipse(x,3,24,8,.05,0,7);ctx.fill();ctx.fillStyle='#526151';ctx.beginPath();ctx.arc(x+4,2,7,0,7);ctx.fill();ctx.fillStyle='#13191c';ctx.beginPath();ctx.arc(x+4,2,3.5,0,7);ctx.fill();ctx.strokeStyle='#493127';ctx.lineWidth=3;ctx.beginPath();ctx.moveTo(x-25,2);ctx.quadraticCurveTo(x,-10,x+25,3);ctx.stroke();}ctx.strokeStyle='#a06750';ctx.lineWidth=3;ctx.beginPath();ctx.moveTo(8,9);ctx.lineTo(-2,51);ctx.quadraticCurveTo(10,60,24,51);ctx.stroke();ctx.fillStyle='#ae6660';ctx.beginPath();ctx.moveTo(-24,85);ctx.quadraticCurveTo(6,68,37,82);ctx.quadraticCurveTo(12,107,-24,85);ctx.fill();ctx.strokeStyle='#693838';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(-24,85);ctx.quadraticCurveTo(7,89,37,82);ctx.stroke();ctx.fillStyle=hair;ctx.beginPath();ctx.moveTo(-144,-35);ctx.bezierCurveTo(-150,-245,152,-244,147,-56);ctx.bezierCurveTo(48,-180,-63,-75,-140,72);ctx.closePath();ctx.fill();ctx.strokeStyle='#d888473f';ctx.lineWidth=3;for(let i=0;i<16;i++){ctx.beginPath();ctx.moveTo(-145+i*17,-126-Math.sin(i*.2)*30);ctx.bezierCurveTo(-113+i*9,-100,-145+i*3,77,-166+i*5,250);ctx.stroke();}ctx.restore();}
const shade=ctx.createLinearGradient(0,0,0,860);shade.addColorStop(0,'#11152000');shade.addColorStop(.6,'#090b0e00');shade.addColorStop(1,'#090b0ecc');ctx.fillStyle=shade;ctx.fillRect(0,0,780,860);ctx.strokeStyle='#b9c4df22';ctx.lineWidth=1;for(let i=0;i<80;i++){let x=rnd()*780,y=rnd()*860;ctx.beginPath();ctx.moveTo(x,y);ctx.lineTo(x-6,y+23+rnd()*38);ctx.stroke();}return c.toDataURL('image/png');}
function drawPoster(){const canvas=$('#poster');if(!canvas)return;const ctx=canvas.getContext('2d'),s=SUITS[loadout.suit];ctx.clearRect(0,0,900,1200);const g=ctx.createRadialGradient(520,400,40,450,400,730);g.addColorStop(0,loadout.suit==='classic'?'#42202e':'#2b2d46');g.addColorStop(.6,'#111a2b');g.addColorStop(1,'#070b12');ctx.fillStyle=g;ctx.fillRect(0,0,900,1200);paintCity(ctx,900,1010,32,.75);ctx.strokeStyle=s.accent+'30';ctx.lineWidth=1;for(let i=0;i<12;i++){ctx.beginPath();ctx.moveTo(940,-30);ctx.lineTo(-300+i*160,1000);ctx.stroke();}ctx.strokeStyle='#ffffff35';ctx.strokeRect(35,35,830,1130);ctx.fillStyle=s.accent;ctx.fillRect(60,65,53,4);ctx.fillStyle='#c9cbd5';ctx.font='bold 13px Arial';ctx.fillText('YOUR ULTIMATE SPIDER-MAN / SUIT '+s.code,130,73);drawMask(ctx,450,433,200,loadout.suit,.28);ctx.save();ctx.textAlign='center';ctx.fillStyle='#f4efe8';ctx.font='800 122px "Barlow Condensed", Impact, sans-serif';ctx.fillText('BE GREATER.',450,854,775);ctx.fillStyle=s.accent;ctx.font='bold 23px Arial';ctx.fillText((loadout.alias.trim()||'YOUR FRIENDLY NEIGHBORHOOD HERO').toUpperCase(),450,900,775);ctx.fillStyle='#dddfe6';ctx.font='18px Arial';ctx.fillText(s.name.toUpperCase(),450,950);ctx.fillStyle='#94a1b6';ctx.font='14px Arial';const mod=$('#web-mod').selectedOptions[0]?.textContent||'Precision Webbing';ctx.fillText('WEB MOD / '+mod.toUpperCase(),450,990);ctx.fillText('GADGETS / '+(loadout.gadgets.length?loadout.gadgets.join(' + '):'PURE INSTINCT').toUpperCase(),450,1023,770);drawSpider(ctx,450,1092,24,s.accent);ctx.fillStyle='#6c778b';ctx.font='10px Arial';ctx.fillText('UNOFFICIAL FAN CONCEPT · NOT AFFILIATED WITH MARVEL OR SONY',450,1144);ctx.restore();}
// Animated New York skyline, rain, wet reflections, and ember particles.
const cityCanvas=$("#city"),cityCtx=cityCanvas.getContext("2d"),cityLayer=document.createElement("canvas");
let cityW=1,cityH=1,stageW=1,stageH=1,dpr=1;const stage=$("#mask-stage"),fallback=$("#mask-fallback"),fallbackCtx=fallback.getContext("2d");
const random=seeded(918),rain=Array.from({length:95},()=>({x:random(),y:random(),len:9+random()*30,speed:.2+random()*.7,alpha:.06+random()*.18})),embers=Array.from({length:30},()=>({x:random(),y:random(),size:.6+random()*1.6,speed:.015+random()*.05,phase:random()*7}));
function resize(){dpr=Math.min(devicePixelRatio||1,1.6);const cityRect=cityCanvas.getBoundingClientRect();cityW=cityRect.width;cityH=cityRect.height;cityCanvas.width=Math.max(1,Math.round(cityW*dpr));cityCanvas.height=Math.max(1,Math.round(cityH*dpr));cityCtx.setTransform(dpr,0,0,dpr,0,0);cityLayer.width=Math.max(1,Math.round(cityW*dpr));cityLayer.height=Math.max(1,Math.round(cityH*dpr));const b=cityLayer.getContext("2d");b.setTransform(dpr,0,0,dpr,0,0);let sky=b.createRadialGradient(cityW*.65,cityH*.3,0,cityW*.65,cityH*.3,cityW*.7);sky.addColorStop(0,"#343643");sky.addColorStop(.4,"#141e30");sky.addColorStop(1,"#070c14");b.fillStyle=sky;b.fillRect(0,0,cityW,cityH);b.save();b.translate(0,cityH*.15);paintCity(b,cityW,cityH*.78,124,.9);b.restore();
// Empire State-inspired central spire, with glowing amber windows.
const bx=cityW*.79,by=cityH*.30,bw=cityW<600?31:53,bh=cityH*.52;b.fillStyle="#17212f";b.fillRect(bx-bw/2,by,bw,bh);b.fillStyle="#263341";b.fillRect(bx-bw*.28,by-26,bw*.56,26);b.fillRect(bx-bw*.14,by-45,bw*.28,22);b.fillStyle="#7699b077";b.fillRect(bx-1,by-102,2,60);b.fillStyle="#d59469";b.fillRect(bx-1.5,by-103,3,3);const r=seeded(91);for(let y=by+7;y<by+bh;y+=9)for(let x=bx-bw/2+5;x<bx+bw/2-3;x+=6){b.fillStyle=r()>.5?"#ca9b6355":"#78add42a";b.fillRect(x,y,2,4);}
// Slick foreground streets mirror the city lights.
b.fillStyle="#070c15cc";b.fillRect(0,cityH*.87,cityW,cityH*.13);for(let i=0;i<65;i++){let x=r()*cityW,y=cityH*(.87+r()*.13);b.fillStyle=i%3?"#d99b5117":"#81b4ee1c";b.fillRect(x,y,5+r()*30,1+r()*2);}const rect=stage.getBoundingClientRect();stageW=rect.width;stageH=rect.height;fallback.width=Math.max(1,Math.round(stageW*dpr));fallback.height=Math.max(1,Math.round(stageH*dpr));fallbackCtx.setTransform(dpr,0,0,dpr,0,0);if(threeView)threeView.resize(stageW,stageH);}
let resizeTimer;addEventListener("resize",()=>{clearTimeout(resizeTimer);resizeTimer=setTimeout(resize,100);});
let dragging=false,pointerStart=null;stage.addEventListener("pointerdown",e=>{if(e.target.closest("button"))return;dragging=true;pointerStart={x:e.clientX,y:e.clientY,tx:targetX,ty:targetY};if(e.pointerType==="mouse")stage.setPointerCapture(e.pointerId);});stage.addEventListener("pointermove",e=>{if(e.target.closest("button"))return;const r=stage.getBoundingClientRect();if(dragging&&pointerStart){targetX=Math.max(-.8,Math.min(.8,pointerStart.tx+(e.clientX-pointerStart.x)/220));targetY=Math.max(-.35,Math.min(.35,pointerStart.ty+(e.clientY-pointerStart.y)/400));}else if(e.pointerType!=="touch"){targetX=((e.clientX-r.left)/r.width-.5)*.8;targetY=((e.clientY-r.top)/r.height-.5)*.35;}});stage.addEventListener("pointerup",()=>{dragging=false;pointerStart=null;});stage.addEventListener("pointercancel",()=>{dragging=false;pointerStart=null;});stage.addEventListener("pointerleave",()=>{if(!dragging){targetX=0;targetY=0;}});stage.addEventListener("keydown",e=>{if(e.target!==stage)return;let handled=true;if(e.key==="ArrowLeft")targetX=Math.max(-.8,targetX-.13);else if(e.key==="ArrowRight")targetX=Math.min(.8,targetX+.13);else if(e.key==="ArrowUp")targetY=Math.max(-.35,targetY-.08);else if(e.key==="ArrowDown")targetY=Math.min(.35,targetY+.08);else if(e.key==="Home"){targetX=0;targetY=0;}else handled=false;if(handled)e.preventDefault();});
$("#swing-btn").addEventListener("click",()=>{if(swingStart)return;if(reduced.matches){toast("Web line secured. Ready to swing — motion reduced.");return;}swingStart=performance.now();stage.classList.add("swinging");$("#swing-btn").disabled=true;setTimeout(()=>{swingStart=0;stage.classList.remove("swinging");$("#swing-btn").disabled=false;},1400);});
$("#symbiote-btn").addEventListener("click",()=>{selectSuit(currentSuit==="symbiote"?"classic":"symbiote",true);if(!reduced.matches){const flash=$(".effect-flash");flash.classList.remove("flash");void flash.offsetWidth;flash.classList.add("flash");}});
$(".hero-copy").addEventListener("pointermove",e=>{if(reduced.matches||innerWidth<800)return;const r=$(".hero-copy").getBoundingClientRect();$("#hero-title").style.transform=`translate(${((e.clientX-r.left)/r.width-.5)*5}px,${((e.clientY-r.top)/r.height-.5)*4}px)`;});$(".hero-copy").addEventListener("pointerleave",()=>$("#hero-title").style.transform="");
let heroVisible=true;const visibilityObserver=new IntersectionObserver(entries=>{heroVisible=entries[0].isIntersecting;},{rootMargin:"100px"});visibilityObserver.observe($(".hero"));let previous=0;
function animate(now){requestAnimationFrame(animate);if(document.hidden||!heroVisible)return;if(now-previous<1000/(reduced.matches?12:40))return;previous=now;const time=reduced.matches?0:now*.001;cityCtx.clearRect(0,0,cityW,cityH);cityCtx.drawImage(cityLayer,0,0,cityW,cityH);for(const drop of rain){const x=(drop.x*cityW-time*drop.speed*32%cityW+cityW)%cityW,y=(drop.y*cityH+time*drop.speed*340)%cityH;cityCtx.strokeStyle=`rgba(174,194,222,${drop.alpha})`;cityCtx.lineWidth=.6;cityCtx.beginPath();cityCtx.moveTo(x,y);cityCtx.lineTo(x-3,y+drop.len);cityCtx.stroke();}for(const e of embers){const x=(e.x*cityW+Math.sin(time*.4+e.phase)*25),y=(e.y*cityH-time*e.speed*190%cityH+cityH)%cityH;cityCtx.fillStyle=`rgba(255,${130+Math.floor(e.size*28)},95,${.22+Math.sin(time+e.phase)*.17})`;cityCtx.shadowColor="#f87d33";cityCtx.shadowBlur=7;cityCtx.beginPath();cityCtx.arc(x,y,e.size,0,Math.PI*2);cityCtx.fill();}cityCtx.shadowBlur=0;currentX+=(targetX-currentX)*.08;currentY+=(targetY-currentY)*.08;let sx=0,sy=0,spin=0;if(swingStart){const p=Math.min((now-swingStart)/1400,1),arc=Math.sin(p*Math.PI*2)*Math.sin(p*Math.PI);sx=arc*stageW*.54;sy=-Math.sin(p*Math.PI)*stageH*.27;spin=arc*.7;}if(threeView){threeView.frame(time,currentX,currentY,sx,sy,spin);}else{fallbackCtx.clearRect(0,0,stageW,stageH);fallbackCtx.save();fallbackCtx.translate(stageW*.54+sx,stageH*.445+sy+Math.sin(time*1.2)*5);fallbackCtx.rotate(-.085+spin+currentX*.10);drawMask(fallbackCtx,0,currentY*18,Math.min(stageW*.222,stageH*.272),currentSuit,currentX*1.4);fallbackCtx.restore();}}
// Three.js enhancement. The interactive original canvas mask remains available offline.
function makeSuitTexture(key){const c=document.createElement("canvas");c.width=1024;c.height=1024;const ctx=c.getContext("2d"),s=SUITS[key],rnd=seeded(721);ctx.fillStyle=s.color;ctx.fillRect(0,0,1024,1024);for(let y=0;y<1024;y+=4)for(let x=0;x<1024;x+=4){ctx.fillStyle=`rgba(230,218,232,${.035+rnd()*.08})`;ctx.fillRect(x+(y%8?2:0),y,1,2);}ctx.strokeStyle=s.web;ctx.lineWidth=key==="classic"?3:2;ctx.globalAlpha=key==="symbiote"?.45:.9;for(let x=0;x<=1024;x+=64){ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,1024);ctx.stroke();}for(let y=36;y<1000;y+=70){ctx.beginPath();ctx.moveTo(0,y);for(let x=0;x<1024;x+=64)ctx.quadraticCurveTo(x+32,y+18,x+64,y);ctx.stroke();}ctx.globalAlpha=1;if(key==="symbiote"){ctx.strokeStyle="#a6acc9";ctx.globalAlpha=.14;for(let i=0;i<35;i++){let x=rnd()*1024;ctx.beginPath();ctx.moveTo(x,0);ctx.bezierCurveTo(x+120,300,x-180,650,x+80,1024);ctx.stroke();}ctx.globalAlpha=1;}return c;}
function startThree(){if(!window.THREE||threeView)return;try{const T=THREE,scene=new T.Scene(),camera=new T.PerspectiveCamera(43,stageW/stageH,.1,50);camera.position.set(0,0,5.25);const renderer=new T.WebGLRenderer({alpha:true,antialias:true,powerPreference:"low-power"});renderer.setPixelRatio(Math.min(devicePixelRatio||1,1.7));renderer.setSize(stageW,stageH);renderer.outputColorSpace=T.SRGBColorSpace;renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=1.25;renderer.domElement.id="three-canvas";renderer.domElement.setAttribute("aria-hidden","true");renderer.setClearColor(0x000000,0);const group=new T.Group();scene.add(group);group.position.set(.16,.18,0);
const headGeometry=new T.SphereGeometry(1,96,64),pos=headGeometry.attributes.position;for(let i=0;i<pos.count;i++){let x=pos.getX(i),y=pos.getY(i),z=pos.getZ(i);const taper=1-Math.max(0,-y-.12)*.3;x*=1.08*taper;const nose=z>.3?Math.exp(-Math.pow(x/.22,2)-Math.pow((y+.14)/.24,2))*.14:0;pos.setXYZ(i,x,y*1.48,z*.99+nose);}headGeometry.computeVertexNormals();const texture=new T.CanvasTexture(makeSuitTexture(currentSuit));texture.colorSpace=T.SRGBColorSpace;texture.anisotropy=Math.min(8,renderer.capabilities.getMaxAnisotropy());const material=new T.MeshStandardMaterial({map:texture,roughness:.67,metalness:.14});const head=new T.Mesh(headGeometry,material);group.add(head);
function lensGeometry(side,scale=1){const shape=new T.Shape();shape.moveTo(.145,-.29);shape.bezierCurveTo(.36,-.30,.75,-.51,.985,-.77);shape.bezierCurveTo(.985,-.14,.89,.16,.66,.27);shape.bezierCurveTo(.41,.39,.26,.21,.145,-.29);const points=shape.getPoints(32);if(points[0].distanceTo(points[points.length-1])<.001)points.pop();const N=points.length,rings=14,vertices=[],indices=[];function project(x,y){x=(.56+(x-.56)*scale)*side*.85;y=-(-.22+(y+.22)*scale)*.85;const n=Math.exp(-Math.pow(x/.22,2)-Math.pow((y/1.48+.14)/.24,2))*.14;const z=Math.sqrt(Math.max(.01,1-(x/1.08)**2-(y/1.48)**2))*.99+n+(scale===1?.059:.025);vertices.push(x,y,z);}project(.56,-.16);for(let r=1;r<=rings;r++){const f=r/rings;for(const p of points)project(.56+(p.x-.56)*f,-.16+(p.y+.16)*f);}for(let i=0;i<N;i++)indices.push(0,1+i,1+(i+1)%N);for(let r=0;r<rings-1;r++)for(let i=0;i<N;i++){const a=1+r*N+i,b=1+r*N+(i+1)%N,c=a+N,d=b+N;indices.push(a,c,b,b,c,d);}const geo=new T.BufferGeometry();geo.setAttribute("position",new T.Float32BufferAttribute(vertices,3));geo.setIndex(indices);geo.computeVertexNormals();return geo;}
const rimMat=new T.MeshStandardMaterial({color:0x070a10,roughness:.4,metalness:.3,side:T.DoubleSide}),eyeMat=new T.MeshStandardMaterial({color:0xe9f4ff,emissive:0x738da2,emissiveIntensity:.22,roughness:.25,metalness:.25,side:T.DoubleSide});for(const side of [-1,1]){group.add(new T.Mesh(lensGeometry(side,1.15),rimMat));group.add(new T.Mesh(lensGeometry(side),eyeMat));}
scene.add(new T.HemisphereLight(0xc8d8f9,0x120609,2));const key=new T.DirectionalLight(0xffcfbf,4.3);key.position.set(-3,5,4);scene.add(key);const red=new T.PointLight(0xf33448,35,12);red.position.set(-3,0,1);scene.add(red);const blue=new T.PointLight(0x5b9eff,50,12);blue.position.set(3,1,-1);scene.add(blue);const top=new T.DirectionalLight(0xdce6ff,2);top.position.set(1,4,-2);scene.add(top);
const textures={[currentSuit]:texture};function setSuit(key){if(!textures[key]){const map=new T.CanvasTexture(makeSuitTexture(key));map.colorSpace=T.SRGBColorSpace;map.anisotropy=texture.anisotropy;textures[key]=map;}material.map=textures[key];material.roughness=key==="symbiote"?.28:key==="miles"?.7:.67;material.metalness=key==="symbiote"?.35:.14;material.needsUpdate=true;rimMat.color.set(key==="miles"?0xd92841:0x070a10);eyeMat.emissiveIntensity=key==="symbiote"?.42:.22;red.color.set(key==="symbiote"?0xa88bff:0xf33448);}
threeView={setSuit,resize(w,h){camera.aspect=w/h;camera.updateProjectionMatrix();renderer.setSize(w,h);},frame(time,rx,ry,sx,sy,spin){group.rotation.set(.045+ry,-.19+rx,-.08+spin);group.position.set(.16+sx/stageW*4.3,.18+Math.sin(time*1.2)*.025-sy/stageH*4.3,0);renderer.render(scene,camera);}};setSuit(currentSuit);threeView.frame(0,0,0,0,0,0);stage.insertBefore(renderer.domElement,stage.firstChild);fallback.style.visibility="hidden";stage.dataset.renderer="threejs";renderer.domElement.addEventListener("webglcontextlost",e=>{e.preventDefault();renderer.domElement.style.visibility="hidden";fallback.style.visibility="visible";threeView=null;stage.dataset.renderer="canvas";$("#render-hint").textContent="INTERACTIVE CANVAS · ARROW KEYS TO ROTATE";});}catch(err){stage.dataset.renderer="canvas";$("#render-hint").textContent="INTERACTIVE CANVAS · ARROW KEYS TO ROTATE";}}
function loadThree(){const sources=["https://cdnjs.cloudflare.com/ajax/libs/three.js/0.160.0/three.min.js","https://unpkg.com/three@0.160.0/build/three.min.js"];let i=0;function attempt(){if(i>=sources.length){stage.dataset.renderer="canvas";$("#render-hint").textContent="INTERACTIVE CANVAS · ARROW KEYS TO ROTATE";return;}const script=document.createElement("script");script.src=sources[i++];script.crossOrigin="anonymous";script.async=true;script.onload=startThree;script.onerror=attempt;document.head.appendChild(script);}attempt();}
["heroes","villains","allies"].forEach(k=>$("#"+k+"-art").src=makePortrait(k));
resize();updateBuilder();selectSuit(loadout.suit);requestAnimationFrame(animate);loadThree();
if(document.fonts)document.fonts.ready.then(drawPoster);
if(location.hash.startsWith("#loadout="))setTimeout(()=>{openDialog("builder");toast("Shared hero loadout loaded.");},250);
