import {chromium} from 'playwright';
import {createServer} from 'node:http';
import {readFile,writeFile,mkdir} from 'node:fs/promises';
import {resolve,extname,dirname} from 'node:path';
import {fileURLToPath,pathToFileURL} from 'node:url';
import {createRequire} from 'node:module';
import {createHash} from 'node:crypto';
import assert from 'node:assert/strict';
const require=createRequire(import.meta.url),here=dirname(fileURLToPath(import.meta.url)),root=resolve(here,'..'),results=resolve(here,'results');await mkdir(results,{recursive:true});
const checks=[],errors=[];let browser,server;const pass=s=>{checks.push(s);console.log('PASS '+s);};const snapshot=p=>p.evaluate(()=>window.PrismStudio.getState());const waitPreview=p=>p.waitForFunction(()=>!!document.querySelector('#composer-preview svg'));
async function close(p){await p.locator('#dialog-close').click();}
async function download(p,selector){const [d]=await Promise.all([p.waitForEvent('download'),p.locator(selector).click()]);const file=resolve(results,d.suggestedFilename());await d.saveAs(file);return file;}
async function axe(p,name){await p.addScriptTag({path:require.resolve('axe-core/axe.min.js')});const r=await p.evaluate(async()=>await axe.run(document,{runOnly:{type:'tag',values:['wcag2a','wcag2aa','wcag21aa']}}));await writeFile(resolve(results,name+'-accessibility.json'),JSON.stringify(r.violations,null,2));assert.deepEqual(r.violations.filter(x=>['critical','serious'].includes(x.impact)).map(x=>({id:x.id,nodes:x.nodes.map(y=>({target:y.target,summary:y.failureSummary}))})),[]);pass(name+': no serious/critical automated WCAG A/AA violations');}
try{
 server=createServer(async(req,res)=>{try{const path=decodeURIComponent(new URL(req.url,'http://local').pathname),file=resolve(root,'.'+(path==='/'?'/index.html':path));if(!file.startsWith(root+'/'))throw Error();const body=await readFile(file);res.writeHead(200,{'Content-Type':({'.html':'text/html','.js':'text/javascript','.css':'text/css','.svg':'image/svg+xml'})[extname(file)]||'application/octet-stream'});res.end(body);}catch(e){res.writeHead(404);res.end();}});await new Promise(r=>server.listen(0,'127.0.0.1',r));const url='http://127.0.0.1:'+server.address().port+'/';browser=await chromium.launch({headless:true,args:['--no-sandbox']});const context=await browser.newContext({viewport:{width:1440,height:1080},reducedMotion:'reduce'});const page=await context.newPage();page.on('pageerror',e=>errors.push(e.message));await page.goto(url);await page.locator('#composer-open').waitFor();const original=await snapshot(page);assert.equal(await page.locator('meta[name="prism-version"]').getAttribute('content'),'1.1.0');pass('1.1 entrypoint and validated extension API load');
 await page.locator('#composer-open').click();await waitPreview(page);const artBefore=await page.locator('#composer-preview').innerHTML();await page.locator('#row-value-0').fill('9');await page.waitForFunction(html=>document.querySelector('#composer-preview').innerHTML!==html,artBefore);assert.deepEqual(await snapshot(page),original);await page.locator('#composer-cancel').click();assert.deepEqual(await snapshot(page),original);pass('Data edits update the live preview without mutating the original; cancel discards drafts');
 await page.locator('#composer-inline').click();await waitPreview(page);await page.locator('#row-value-1').fill('');assert.equal(await page.locator('#composer-error').isVisible(),true);assert.equal(await page.locator('#composer-apply').isDisabled(),true);await page.locator('#row-value-1').fill('1000000001');assert.equal(await page.locator('#composer-apply').isDisabled(),true);await page.locator('#row-value-1').fill('-2.5');assert.equal(await page.locator('#composer-apply').isDisabled(),false);await page.locator('#row-label-0').fill('');assert.equal(await page.locator('#composer-apply').isDisabled(),true);await page.locator('#row-label-0').fill('Morning <calm>');pass('Blank labels, empty values and out-of-range values block invalid commits with recovery');
 await page.locator('#composer-add').click();assert.equal(await page.locator('[data-value]').count(),13);await page.locator('[data-remove="12"]').click();assert.equal(await page.locator('[data-value]').count(),12);await page.locator('#composer-name').fill('My observation journal');await page.locator('#composer-title').fill('A quiet experiment');await page.locator('#composer-unit').fill('mm');await page.locator('#composer-source').fill('Personal observations, edited for a workshop.');await axe(page,'Composer desktop');await page.screenshot({path:resolve(results,'composer-desktop.png'),fullPage:true});await page.locator('[data-audition="1"]').click();assert.match(await page.locator('#composer-summary').innerText(),/Playing/);await page.locator('#composer-apply').click();const edited=await snapshot(page);assert.equal(edited.source,'custom');assert.equal(edited.data.values[1],-2.5);assert.equal(edited.data.labels[0],'Morning <calm>');assert.equal(edited.data.unit,'mm');assert.match(edited.data.provenance,/Edited in the Prism Atlas/);await page.locator('#undo').click();assert.deepEqual(await snapshot(page),original);await page.locator('#redo').click();assert.deepEqual(await snapshot(page),edited);pass('Add/remove, note audition and metadata apply as one undoable, provenance-labelled change');
 await page.locator('#composer-open').click();await page.locator('#row-value-0').fill('123');await page.keyboard.press('Escape');assert.deepEqual(await snapshot(page),edited);assert.equal(await page.locator('#composer-open').evaluate(el=>el===document.activeElement),true);pass('Escape discards a draft and restores keyboard focus');
 await page.locator('#exhibition-open').click();await axe(page,'Exhibition builder');const wavPath=await download(page,'#soundtrack-download'),wav=await readFile(wavPath);assert.equal(wav.subarray(0,4).toString(),'RIFF');assert.equal(wav.subarray(8,12).toString(),'WAVE');assert.equal(wav.readUInt16LE(20),1);assert.equal(wav.readUInt16LE(22),1);assert.equal(wav.readUInt32LE(24),22050);assert.equal(wav.readUInt16LE(34),16);const duration=(wav.length-44)/2/22050;assert.ok(Math.abs(duration-((edited.data.values.length-1)*.52+1))<1/22050);assert.ok(wav.subarray(44).some(v=>v!==0));pass('WAV download is non-silent mono 22,050 Hz 16-bit PCM with exact data-dependent duration');
 await page.locator('#exhibition-credit').fill('Creator <&>');const hostile='A story <img src=x onerror="window.__injected=1"> and </script><script>window.__injected=1</script>';await page.locator('#exhibition-statement').fill(hostile);const exhibitPath=await download(page,'#exhibition-download');await page.waitForFunction(()=>!document.querySelector('#exhibition-download').disabled);assert.deepEqual(await snapshot(page),edited);const html=await readFile(exhibitPath,'utf8');assert.ok(html.includes('data:audio/wav;base64,'));assert.ok(html.includes('&lt;img'));assert.ok(!html.includes('<img src=x'));pass('Exhibition packs audio and safely escaped creator content without mutating the session');
 const offline=await browser.newContext({offline:true,viewport:{width:1280,height:900}});const exhibit=await offline.newPage(),requests=[];exhibit.on('pageerror',e=>errors.push(e.message));exhibit.on('request',r=>{if(/^https?:/.test(r.url()))requests.push(r.url());});await exhibit.goto(pathToFileURL(exhibitPath).href);await exhibit.locator('.art svg').waitFor();assert.equal(await exhibit.locator('h1').innerText(),edited.title);assert.equal(await exhibit.locator('.statement').innerText(),hostile);assert.equal(await exhibit.evaluate(()=>window.__injected),undefined);assert.equal(await exhibit.locator('audio').evaluate(a=>a.paused),true);await exhibit.locator('audio').evaluate(a=>{a.preload='auto';a.load();});await exhibit.waitForFunction(()=>document.querySelector('audio').readyState>=1);assert.ok(Math.abs(await exhibit.locator('audio').evaluate(a=>a.duration)-duration)<.01);assert.deepEqual(requests,[]);pass('Downloaded exhibition opens with networking disabled; embedded audio decodes and does not autoplay');
 const exported=await exhibit.locator('#creative-recipe').textContent(),receipt=JSON.parse(exported);assert.equal(receipt.recipe.creator,'Creator <&>');assert.deepEqual(receipt.recipe.data,edited.data);assert.equal(receipt.recipeSHA256,createHash('sha256').update(JSON.stringify(receipt.recipe)).digest('hex'));await exhibit.locator('#immersive').click();assert.equal(await exhibit.locator('#immersive').getAttribute('aria-pressed'),'true');await exhibit.keyboard.press('Escape');assert.equal(await exhibit.locator('#immersive').getAttribute('aria-pressed'),'false');await exhibit.locator('summary').click();assert.equal(await exhibit.locator('tbody tr').count(),12);const downloadedRecipe=await download(exhibit,'#recipe');assert.equal(JSON.parse(await readFile(downloadedRecipe,'utf8')).recipe.title,edited.title);await exhibit.screenshot({path:resolve(results,'offline-exhibition.png'),fullPage:true});await axe(exhibit,'Offline exhibition');await offline.close();pass('Offline immersive view, accessible source table and checksummed recipe download work');
 await page.locator('#exhibition-audio').uncheck();const silentPath=await download(page,'#exhibition-download');assert.ok(!(await readFile(silentPath,'utf8')).includes('data:audio/wav'));await close(page);pass('Audio can be omitted from the portable exhibition');
 await page.locator('#import-open').click();await page.locator('#recipe-file').setInputFiles(downloadedRecipe);await page.waitForFunction(()=>!document.querySelector('#dialog').open);assert.deepEqual(await snapshot(page),receipt.recipe);pass('The exhibition recipe reimports into the studio without loss');
 const three={...original,data:{...original.data,labels:['A','B','C'],values:[5,5,5]}};await page.evaluate(s=>window.PrismStudio.commit(s),three);await page.locator('#composer-open').click();await waitPreview(page);assert.equal(await page.locator('[data-remove]:disabled').count(),3);assert.ok(!(await page.locator('#composer-preview').innerHTML()).includes('NaN'));await close(page);const max={...original,data:{...original.data,labels:Array.from({length:120},(_,i)=>'Point '+i),values:Array.from({length:120},(_,i)=>i)}};await page.evaluate(s=>window.PrismStudio.commit(s),max);await page.locator('#composer-open').click();assert.equal(await page.locator('#composer-add').isDisabled(),true);assert.equal(await page.locator('[data-value]').count(),120);await close(page);await page.evaluate(s=>window.PrismStudio.commit(s),original);pass('Three-row minimum, 120-row maximum and constant-valued datasets are handled');
 const mobile=await browser.newContext({viewport:{width:390,height:844},isMobile:true,hasTouch:true,reducedMotion:'reduce'});const m=await mobile.newPage();m.on('pageerror',e=>errors.push(e.message));await m.goto(url);await m.locator('#composer-open').click();await waitPreview(m);for(const width of [320,390,768]){await m.setViewportSize({width,height:844});assert.ok(await m.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),'Page overflows at '+width);assert.ok(await m.locator('#dialog').evaluate(d=>d.scrollWidth<=d.clientWidth+1),'Composer overflows at '+width);}await m.setViewportSize({width:390,height:844});await m.locator('#row-value-0').fill('7');await m.screenshot({path:resolve(results,'composer-mobile.png'),fullPage:true});await axe(m,'Composer mobile');await m.locator('#composer-apply').click();assert.equal((await snapshot(m)).data.values[0],7);await mobile.close();pass('Mobile composer works at 320/390/768px without horizontal overflow');
 const blocked=await browser.newContext();await blocked.addInitScript(()=>{Storage.prototype.setItem=function(){throw new DOMException('Storage blocked','SecurityError');};});const b=await blocked.newPage();b.on('pageerror',e=>errors.push(e.message));await b.goto(url);await b.locator('#composer-open').click();await b.locator('#row-value-0').fill('7.5');await b.locator('#composer-apply').click();assert.equal((await snapshot(b)).data.values[0],7.5);await b.locator('#exhibition-open').click();await b.locator('#exhibition-audio').uncheck();const blockedHTML=await download(b,'#exhibition-download');assert.ok((await readFile(blockedHTML,'utf8')).includes('7.5'));await blocked.close();pass('Composer and exhibition export remain usable when browser storage is blocked');
 assert.deepEqual(errors,[]);pass('No runtime errors across composer, exports and offline viewing');
 const live='https://sweemingxx.github.io/prism-atlas/';const lc=await browser.newContext(),lp=await lc.newPage();await lp.goto(live+'?release=1.1.0');await lp.locator('#composer-open').waitFor();await lp.locator('#composer-open').click();await lp.locator('#row-value-0').fill('8.5');await lp.locator('#composer-apply').click();assert.equal((await snapshot(lp)).data.values[0],8.5);await lp.locator('#exhibition-open').click();const liveWave=await download(lp,'#soundtrack-download');assert.equal((await readFile(liveWave)).subarray(0,4).toString(),'RIFF');await lc.close();pass('Live GitHub Pages 1.1 composer and soundtrack export verified');
 await writeFile(resolve(results,'advanced-report.json'),JSON.stringify({status:'passed',checks,errors,live,checkedAt:new Date().toISOString()},null,2));console.log('::notice title=Prism Atlas 1.1 verified::'+checks.length+' enhanced browser checks passed, including the live composer and offline exhibition.');
}catch(e){await writeFile(resolve(results,'advanced-failure.txt'),String(e.stack));console.error('::error title=Prism Atlas 1.1 failed::'+String(e.stack).replace(/%/g,'%25').replace(/\r/g,'%0D').replace(/\n/g,'%0A'));process.exitCode=1;}finally{if(browser)await browser.close();if(server)await new Promise(r=>server.close(r));}
