import { chromium } from 'playwright';
import { createServer } from 'node:http';
import { readFile, writeFile, mkdir } from 'node:fs/promises';
import { resolve, extname, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { createHash } from 'node:crypto';
import { createRequire } from 'node:module';
import assert from 'node:assert/strict';
const require=createRequire(import.meta.url),here=dirname(fileURLToPath(import.meta.url)),root=resolve(here,'..'),results=resolve(here,'results');
await mkdir(results,{recursive:true});
const checks=[],errors=[],accessibility=[];let browser,server;
function pass(name){checks.push(name);console.log('PASS '+name);}
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
const state=page=>page.evaluate(()=>JSON.parse(localStorage.getItem('prism-atlas:session:v1')));
async function close(page){if(await page.locator('#dialog').evaluate(d=>d.open))await page.locator('#dialog-close').click();}
async function axe(page,name){await page.addScriptTag({path:require.resolve('axe-core/axe.min.js')});const result=await page.evaluate(async()=>await axe.run(document,{runOnly:{type:'tag',values:['wcag2a','wcag2aa','wcag21aa']}}));const violations=result.violations.map(v=>({id:v.id,impact:v.impact,description:v.description,nodes:v.nodes.map(n=>({target:n.target,summary:n.failureSummary}))}));accessibility.push({name,violations});await writeFile(resolve(results,'accessibility.json'),JSON.stringify(accessibility,null,2));const severe=violations.filter(v=>['critical','serious'].includes(v.impact));assert.equal(severe.length,0,JSON.stringify({name,violations:severe}));pass(name+' automated accessibility: no serious/critical WCAG A/AA violations');}
async function download(page,kind){const [d]=await Promise.all([page.waitForEvent('download'),page.locator(`[data-export="${kind}"]`).click()]);const path=resolve(results,d.suggestedFilename());await d.saveAs(path);return path;}
try{
 server=createServer(async(req,res)=>{try{const pathname=decodeURIComponent(new URL(req.url,'http://localhost').pathname);const p=resolve(root,'.'+(pathname==='/'?'/index.html':pathname));if(!p.startsWith(root+'/')){res.writeHead(403);res.end();return;}const content=await readFile(p);res.writeHead(200,{'Content-Type':({'.html':'text/html','.css':'text/css','.js':'text/javascript','.svg':'image/svg+xml','.json':'application/json'})[extname(p)]||'text/plain'});res.end(content);}catch(e){res.writeHead(404);res.end('Not found');}});await new Promise(r=>server.listen(0,'127.0.0.1',r));
 const url='http://127.0.0.1:'+server.address().port+'/';browser=await chromium.launch({headless:true,args:['--no-sandbox']});const context=await browser.newContext({viewport:{width:1440,height:1080},deviceScaleFactor:1});const page=await context.newPage();page.on('pageerror',e=>errors.push(e.message));
 await page.goto(url);await page.locator('#artwork svg').waitFor();assert.equal(await page.title(),'Prism Atlas — A little data. Infinite expression.');assert.equal((await state(page)).source,'ocean');assert.ok(await page.locator('#artwork path').count()>70);pass('Initial studio renders original SVG artwork and persists session');
 await page.screenshot({path:resolve(results,'desktop-studio.png'),fullPage:true});await axe(page,'Desktop studio');
 await page.locator('#source').selectOption('warmth');assert.equal((await state(page)).data.values[6],26);await page.locator('[data-form="bloom"]').click();assert.equal((await state(page)).form,'bloom');await page.locator('[data-palette="ember"]').click();assert.equal((await state(page)).palette,'ember');
 await page.locator('#flow').evaluate(el=>{el.value='74';el.dispatchEvent(new Event('input',{bubbles:true}));el.dispatchEvent(new Event('change',{bubbles:true}));});assert.equal((await state(page)).flow,74);pass('Data, form, palette and slider controls update the recipe');
 const prior=(await state(page)).seed;await page.locator('#remix').click();const after=(await state(page)).seed;assert.notEqual(prior,after);await page.locator('#undo').click();assert.equal((await state(page)).seed,prior);await page.locator('#redo').click();assert.equal((await state(page)).seed,after);pass('Seeded variations and undo/redo work');
 await page.locator('#data-open').click();assert.equal(await page.locator('#dialog tbody tr').count(),12);await axe(page,'Data explorer dialog');await page.keyboard.press('Escape');assert.equal(await page.locator('#data-open').evaluate(el=>document.activeElement===el),true);pass('Exact data table, accessible dialog and keyboard focus return');
 await page.locator('#import-open').click();await page.locator('#csv-text').fill('label,value\nMonday,nope\nTuesday,4\nWednesday,8');await page.locator('#import-create').click();assert.equal(await page.locator('#csv-error').isVisible(),true);assert.match(await page.locator('#csv-error').innerText(),/finite decimal/);assert.equal((await state(page)).source,'warmth');
 await page.locator('#data-name').fill('My tidal journal');await page.locator('#csv-text').fill('label,value\n"Quiet, morning",4\nMidday,8\nDusk,-2\nNight,5');await page.locator('#import-create').click();assert.deepEqual((await state(page)).data.values,[4,8,-2,5]);assert.equal((await state(page)).data.labels[0],'Quiet, morning');pass('Malformed CSV preserves work; quoted labels and negative values import correctly');
 await page.locator('#describe').click();assert.match(await page.locator('#dialog-body').innerText(),/lowest value is -2.*Dusk/);assert.match(await page.locator('#dialog-body').innerText(),/highest is 8.*Midday/);await close(page);await page.locator('#listen').click();await sleep(700);assert.equal(await page.locator('#listen').getAttribute('aria-pressed'),'true');assert.equal(await page.locator('#sound-display').isVisible(),true);await page.locator('#listen').click();assert.equal(await page.locator('#listen').getAttribute('aria-pressed'),'false');pass('Grounded description and user-controlled Web Audio sonification');
 await page.locator('#motion').click();assert.equal(await page.locator('#art-stage').evaluate(el=>el.classList.contains('moving')),false);pass('Motion can be paused');
 await page.locator('#save').click();await page.locator('#save').click();assert.equal(await page.locator('#collection-count').innerText(),'1');await page.reload();assert.equal((await state(page)).source,'custom');assert.equal(await page.locator('#collection-count').innerText(),'1');await page.locator('#collection-open').click();await page.locator('[data-delete]').click();assert.equal(await page.locator('#collection-count').innerText(),'0');await page.locator('#toast button').click();assert.equal(await page.locator('#collection-count').innerText(),'1');await close(page);pass('Collection deduplication, reload persistence and removal undo');
 await page.locator('#export-open').click();await page.locator('#export-title').fill('Moon & tides <study>');await page.locator('#export-creator').fill('A curious creator');await axe(page,'Export dialog');const recipePath=await download(page,'json');const receipt=JSON.parse(await readFile(recipePath,'utf8'));assert.equal(receipt.recipe.title,'Moon & tides <study>');assert.equal(receipt.recipe.data.values.length,4);assert.equal(receipt.recipeSHA256,createHash('sha256').update(JSON.stringify(receipt.recipe)).digest('hex'));pass('JSON recipe export includes data and verifiable SHA-256 checksum');
 const svgPath=await download(page,'svg');const svg=await readFile(svgPath,'utf8');assert.ok(svg.includes('<metadata>'));assert.ok(svg.includes('Moon &amp; tides &lt;study&gt;'));assert.ok(!svg.includes('<study>'));const pngPath=await download(page,'png');const png=await readFile(pngPath);assert.equal(png.readUInt32BE(16),2400);assert.equal(png.readUInt32BE(20),1800);assert.ok(png.length>20000);const csvPath=await download(page,'csv');assert.ok((await readFile(csvPath,'utf8')).includes('"Quiet, morning",4'));await close(page);pass('Escaped vector SVG, 2400×1800 PNG and original CSV exports');
 await page.locator('#share-open').click();const share=await page.locator('#share-url').inputValue();assert.ok(share.includes('#recipe='));const other=await browser.newContext();const page2=await other.newPage();page2.on('pageerror',e=>errors.push(e.message));await page2.goto(share);assert.deepEqual(await state(page2),receipt.recipe);await page2.locator('#remix').click();assert.notEqual((await state(page2)).seed,receipt.recipe.seed);await page2.locator('#import-open').click();await page2.locator('#recipe-file').setInputFiles(recipePath);assert.deepEqual(await state(page2),receipt.recipe);await other.close();await close(page);pass('Recipe links round-trip without storage; JSON restores exact state');
 await page.locator('#help-open').click();await page.locator('#reset-open').click();await page.locator('#reset-confirm').click();assert.equal((await state(page)).source,'ocean');await page.locator('#undo').click();assert.equal((await state(page)).source,'custom');pass('Fresh-canvas confirmation and undo protect existing work');
 await page.locator('#tour-open').click();for(let i=0;i<4;i++)await page.locator('#tour-next').click();assert.equal(await page.locator('#dialog').evaluate(d=>d.open),false);pass('Four-step guided introduction completes');
 const reduced=await browser.newContext({reducedMotion:'reduce',viewport:{width:390,height:844},isMobile:true,hasTouch:true});const mobile=await reduced.newPage();mobile.on('pageerror',e=>errors.push(e.message));await mobile.goto(url);assert.equal(await mobile.locator('#art-stage').evaluate(el=>el.classList.contains('moving')),false);await mobile.locator('#motion').click();assert.equal(await mobile.locator('#art-stage').evaluate(el=>el.classList.contains('moving')),false);for(const width of [390,320,768]){await mobile.setViewportSize({width,height:844});assert.ok(await mobile.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),'Horizontal overflow at '+width);}await mobile.setViewportSize({width:390,height:844});await mobile.screenshot({path:resolve(results,'mobile-studio.png'),fullPage:true});await mobile.locator('#import-open').click();await mobile.locator('#import-example').click();await mobile.locator('#import-create').click();assert.equal((await state(mobile)).data.values.length,7);await mobile.locator('#export-open').click();await mobile.screenshot({path:resolve(results,'mobile-export.png'),fullPage:true});await close(mobile);await axe(mobile,'Mobile reduced-motion studio');await reduced.close();pass('Responsive 320/390/768px layouts, mobile import and reduced-motion priority');
 assert.deepEqual(errors,[]);pass('No browser runtime errors');
 console.log('Waiting for GitHub Pages to serve version 1.0.0…');const live='https://SweeMingXx.github.io/prism-atlas/';let liveResponse;
 for(let i=0;i<40;i++){try{liveResponse=await fetch(live+'?verify='+Date.now());if(liveResponse.ok&&(await liveResponse.text()).includes('name="prism-version" content="1.0.0"'))break;liveResponse=null;}catch(e){liveResponse=null;}await sleep(15000);}
 assert.ok(liveResponse,'GitHub Pages did not publish within 10 minutes');const liveContext=await browser.newContext({viewport:{width:1440,height:1080}});const livePage=await liveContext.newPage();const liveErrors=[];livePage.on('pageerror',e=>liveErrors.push(e.message));const response=await livePage.goto(live);assert.equal(response.status(),200);await livePage.locator('#artwork svg').waitFor();assert.equal(await livePage.locator('#art-title').innerText(),'Tidal memory');await livePage.locator('[data-form="contours"]').click();assert.equal((await state(livePage)).form,'contours');await livePage.screenshot({path:resolve(results,'live-desktop.png'),fullPage:true});assert.deepEqual(liveErrors,[]);await liveContext.close();pass('Live GitHub Pages HTTP 200, SVG rendering and interactive controls verified');
 const report={status:'passed',checks,errors,accessibility,live,checkedAt:new Date().toISOString()};await writeFile(resolve(results,'report.json'),JSON.stringify(report,null,2));console.log('::notice title=Prism Atlas verified::'+checks.length+' browser checks passed. Live: '+live);console.log(JSON.stringify(report,null,2));
}catch(e){await writeFile(resolve(results,'failure.txt'),String(e.stack));console.error('::error title=Prism Atlas validation failed::'+String(e.stack).replace(/%/g,'%25').replace(/\r/g,'%0D').replace(/\n/g,'%0A'));process.exitCode=1;}finally{if(browser)await browser.close();if(server)await new Promise(r=>server.close(r));}
